Adesto Flash Demo: SPI
SPI
Peripheral_Functions
Macros
#define PASTE_(A, B) A##B
#define PASTE(A, B) PASTE_(A, B)
#define PASTE3_(A, B, C) A##B##C
#define PASTE3(A, B, C) PASTE3_(A, B, C)
#define SPI_PORT PASTE(USART, USART_NUM)
#define SPI_TX_IRQn PASTE3(USART, USART_NUM, _TX_IRQn)
#define SPI_RX_IRQn PASTE3(USART, USART_NUM, _RX_IRQn)
#define SERIAL_TX_IRQHandler PASTE3(USART, USART_NUM, _TX_IRQHandler
#define SERIAL_RX_IRQHandler PASTE3(USART, USART_NUM, _RX_IRQHandler
#define SPI_cmuClock PASTE(cmuClock_USART, USART_NUM)
#define CK_PORT gpioPortD
#define CK_PIN 2
#define CS_PORT gpioPortD
#define CS_PIN 3
#define RX_PORT gpioPortD
#define RX_PIN 1
#define TX_PORT gpioPortD
#define TX_PIN 0
#define USART_NUM 1
#define USART_LOC 1
#define USE_SO_IRQ 1
Typedefs
typedef void spi_completion_fn_t (void *ref)
Functions
bool spi_active (void)
Called to determine if SPI bus is active.
void USART1_RX_IRQHandler (void)
USART/SPI1 RX Interrupt Handler.
void USART1_TX_IRQHandler (void)
USART/SPI1 RX Interrupt Handler.
void spi_xfer (size_t tx_len, const uint8_t *tx_data, size_t tx2_len, const uint8_t *tx2_data, bool half_duplex, size_t rx_len, uint8_t *rx_data, bool hold_cs_active, spi_completion_fn_t *completion, void *completion_ref)
SPI transfer function.
void SO_IRQ (void *ref)
Active SO Interrupt handler.
void spi_wait_so (uint8_t level, spi_completion_fn_t *completion, void *completion_ref)
Active SO Interrupt handler.
void spi_init (int bit_rate)
SPI/USART Initialization.
Variables
static bool spi_busy
static spi_completion_fn_t * spi_completion
static void * spi_completion_ref
static size_t spi_tx_len
static const uint8_t * spi_tx_data
static size_t spi_tx2_len
static const uint8_t * spi_tx2_data
static size_t spi_tx_post_padding_len
static size_t spi_rx_pre_padding_len
static size_t spi_rx_len
static uint8_t * spi_rx_data
static size_t spi_rx_post_padding_len
static bool spi_hold_cs_active
static bool so_busy
static spi_completion_fn_t * so_completion
static void * so_completion_ref
volatile uint32_t so_irq_count
volatile uint32_t so_spurious_irq_count
volatile uint32_t so_irq_fake_count
volatile unsigned p1
USART_InitSync_TypeDef spiInit
static const gpio_init_t spi_pins []
Detailed Description
Macro Definition Documentation
#define SPI_PORT PASTE(USART, USART_NUM)
#include <spi.c>
*  The defines below are intended to allow any Leopard Gecko or Giant Gecko
*  USART number and location to be used, but only USART1 location 1 has been
*  tested.
*
Definition at line 65 of file spi.c.
Referenced by spi_init(), spi_xfer(), USART1_RX_IRQHandler(), and USART1_TX_IRQHandler().
Function Documentation
bool spi_active (void)
#include <spi.c>
Called to determine if SPI bus is active.
Note
Typically used to determine if Low Power/EM Modes can be entered.
Returns
spi_busy TRUE/FALSE
Definition at line 214 of file spi.c.
Referenced by enter_low_power_state().
 {
     return spi_busy;
 }
void USART1_RX_IRQHandler (void)
#include <spi.c>
USART/SPI1 RX Interrupt Handler.
Note
Copies Received data in spi_rx_data buffer.
Definition at line 227 of file spi.c.
References SPI_PORT.
 {
     uint8_t dummy;
     if (SPI_PORT->IF & USART_IF_RXDATAV)
     {
         if (spi_rx_pre_padding_len)
         {
             dummy = SPI_PORT->RXDATA;
             (void) dummy;
             spi_rx_pre_padding_len--;
         }
         else if (spi_rx_len)
         {
             *spi_rx_data++ = SPI_PORT->RXDATA;
             spi_rx_len--;
         }
         else if (spi_rx_post_padding_len)
         {
             dummy = SPI_PORT->RXDATA;
             (void) dummy;
             spi_rx_post_padding_len--;
         }
         if ((spi_rx_pre_padding_len == 0) && (spi_rx_len == 0) && (spi_rx_post_padding_len == 0))
         {
             // copy completion fn ptr and ref arg, to avoid race condition
             // if completion fn starts another SPI xfer
             spi_completion_fn_t *completion = spi_completion;
             void *completion_ref = spi_completion_ref;
             SPI_PORT->IEN &= ~ USART_IEN_RXDATAV;  // disable rx interrupt
             if (! spi_hold_cs_active)
                 GPIO_PinOutSet(CS_PORT, CS_PIN);  // deassert CS
             spi_busy = false;
             if (completion)
                 completion(completion_ref);
         }
     }
 }
void USART1_TX_IRQHandler (void)
#include <spi.c>
USART/SPI1 RX Interrupt Handler.
Note
Copies TX data into spi_tx_data buffer.
Definition at line 272 of file spi.c.
References SPI_PORT.
 {
     if (SPI_PORT->IF & USART_IF_TXBL)
     {
         if (spi_tx_len)
         {
             SPI_PORT->TXDATA = *spi_tx_data++;
             spi_tx_len--;
         }
         else if (spi_tx2_len)
         {
             SPI_PORT->TXDATA = *spi_tx2_data++;
             spi_tx2_len--;
         }
         else if (spi_tx_post_padding_len)
         {
             SPI_PORT->TXDATA = 0x00;  // still more to rx, so tx dummy byte
             spi_tx_post_padding_len--;
         }
         if((spi_tx_len == 0) && (spi_tx2_len == 0) && (spi_tx_post_padding_len == 0))
             SPI_PORT->IEN &= ~ USART_IEN_TXBL;  // disable tx interrupt
     }
 }
void spi_xfer (size_t tx_len, const uint8_t * tx_data, size_t tx2_len, const uint8_t * tx2_data, bool half_duplex, size_t rx_len, uint8_t * rx_data, bool hold_cs_active, spi_completion_fn_t * completion, void * completion_ref)
#include <spi.c>
SPI transfer function.
Performs one SPI transaction. Fundamentally SPI does a write and read of the same length (byte count) at the same time. Often only a few bytes are to be written, and the data returned while those bytes are written is to be discarded. This can be done using the "half_duplex" flag. The data to be written may optionally be split into two separate buffers in order to handle discontiguous data. Set tx_len or tx_len2 to 0 if the corresponding buffer is not used. Will block if NULL passed for completion function; otherwise will call completion function passing ref argument. Note that completion function may be called either before or after the function returns.
Parameters
[in] tx_len Number of bytes to transfer from tx buffer
[in] *tx_data Pointer to data to be transferred/TX'd
[in] tx2_len Number of bytes to transfer from tx2 buffer
[in] *tx2_data Pointer to data to be transferred from tx2 buffer.
[in] hold_cs_active TRUE/FALSE, Determines whether to hold CS active
[in] *completion Completion state machine callback function
[in] *completion_ref Argument to be passed to completion callback
Definition at line 327 of file spi.c.
References SPI_PORT.
Referenced by spiflash_command_with_address(), spiflash_multiple_byte_command(), and spiflash_single_byte_command().
 {
     spi_rx_len = rx_len;
     spi_rx_data = rx_data;
     spi_tx_len = tx_len;
     spi_tx_data = tx_data;
     spi_tx2_len = tx2_len;
     spi_tx2_data = tx2_data;
     spi_tx_post_padding_len = 0;
     spi_rx_pre_padding_len = 0;
     spi_rx_post_padding_len = 0;
     spi_hold_cs_active = hold_cs_active;
     if (half_duplex)
     {
         spi_rx_pre_padding_len = tx_len + tx2_len;
         spi_tx_post_padding_len = spi_rx_len;
     }
     else if ((tx_len + tx2_len) < rx_len)
         spi_tx_post_padding_len = rx_len - (tx_len + tx2_len);
     else
         spi_rx_post_padding_len = (tx_len + tx2_len) - rx_len;
     //printf("tx: %d, tx2: %d, tx_post: %d\r\n", tx_len, tx2_len, spi_tx_post_padding_len);
     //printf("rx_pre: %d, rx: %d, rx_post: %d\r\n", spi_rx_pre_padding_len, rx_len, spi_rx_post_padding_len);
     spi_completion = completion;
     spi_completion_ref = completion_ref;
     spi_busy = true;
     GPIO_PinOutClear(CS_PORT, CS_PIN);  // assert CS
     // enable interrupts to start transfer
     SPI_PORT->IEN |= (USART_IEN_TXBL | USART_IEN_RXDATAV);
     if (! completion)
         while (spi_busy)
             EMU_EnterEM1();
 }
void SO_IRQ (void * ref)
#include <spi.c>
Active SO Interrupt handler.
Parameters
[in] *ref
Definition at line 397 of file spi.c.
Referenced by spi_init(), and spi_wait_so().
 {
     (void) ref;
     int p = GPIO_PinInGet(RX_PORT, RX_PIN);
     if (p != 0)
     {
         // should never happen - we should only get the interrupt when the pin goes low
         GPIO->IFC = 1 << RX_PIN;
         so_spurious_irq_count++;
         return;
     }
     // disable IRQ
     GPIO_IntConfig(RX_PORT, RX_PIN,
                    false,   // risingEdge
                    false,   // fallingEdge
                    false);  // enable
     so_irq_count++;
     if (! so_busy)
     {
         // should never happen
         while (1)
             ;
     }
     GPIO_PinOutSet(CS_PORT, CS_PIN);  // deassert CS
     // copy completion fn ptr and ref arg, to avoid race condition
     // if completion fn starts another SPI xfer
     spi_completion_fn_t *completion = so_completion;
     void *completion_ref = so_completion_ref;
     so_busy = false;
     if (completion)
         completion(completion_ref);
 }
void spi_wait_so (uint8_t level, spi_completion_fn_t * completion, void * completion_ref)
#include <spi.c>
Active SO Interrupt handler.
Note
Note: may be called synchronously (completion == NULL), in which case this function does not return until the SO interrupt occurs, or asynchronously (completion != NULL), in which case this function merely sets up the interrupt, returns to the caller, and the caller should do whatever is desired until the SO interrupt occurs, at which time the completion function is called.
Parameters
[in] level Determines Edge Level Interrupt: Rising/Falling, spiflash_info->so_done_level is the variable that is passed into the function and is initialized in the Device table found in spiflash.c
[in] *completion Completion State machine callback function
[in] *completion_ref Argument to be passed to completion callback
Definition at line 459 of file spi.c.
References enter_low_power_state(), and SO_IRQ().
Referenced by spiflash_erase_completion4(), and spiflash_write_completion4().
 {
     so_completion = completion;
     so_completion_ref = completion_ref;
     so_busy = true;
     INT_Disable();
     // enable IRQ
     // The EFM32 has edge-triggered interrupts, so we'll never get an
     // interrupt if the port pin was already at the desired level.  To
     // avoid deadlock, we check the pin state here, and if it's already
     // at the desired level, simulate an edge interrupt.
     p1 = GPIO_PinInGet(RX_PORT, RX_PIN);
     if (p1 == level)
     {
         so_irq_fake_count++;
         SO_IRQ(NULL);
     }
     else
     {
         // Note that GPIO_IntConfig will clear any pending IRQ for the pin
         GPIO_IntConfig(RX_PORT, RX_PIN,
                        level,  // risingEdge
                        !level, // fallingEdge
                        true);  // enable
     }
     INT_Enable();
     // if called synchronously, actually wait here
     if (!completion)
         while (so_busy)
             enter_low_power_state();
 }
void spi_init (int bit_rate)
#include <spi.c>
SPI/USART Initialization.
Parameters
[in] bit_rate Bit rate for SPI Bus in MHz: Either 2000000 or 12000000
Definition at line 526 of file spi.c.
References gpio_init(), gpio_irq_handler_install(), SO_IRQ(), and SPI_PORT.
Referenced by spiflash_init().
 {
     CMU_ClockEnable(cmuClock_GPIO, true);
     CMU_ClockEnable(SPI_cmuClock, true);
     gpio_init(spi_pins, sizeof(spi_pins)/sizeof(gpio_init_t));
     USART_Reset(SPI_PORT);
     USART_InitSync(SPI_PORT, &spiInit);
     SPI_PORT->CTRL |= USART_CTRL_TXBIL_HALFFULL;
     SPI_PORT->ROUTE = USART_ROUTE_TXPEN | USART_ROUTE_RXPEN | USART_ROUTE_CLKPEN | (USART_LOC << _USART_ROUTE_LOCATION_SHIFT);
     if (bit_rate)
         USART_BaudrateSyncSet(SPI_PORT, 0, bit_rate);
     USART_IntClear(SPI_PORT, USART_IF_RXDATAV | USART_IF_TXBL);
     NVIC_ClearPendingIRQ(SPI_TX_IRQn);
     NVIC_EnableIRQ(SPI_TX_IRQn);
     NVIC_ClearPendingIRQ(SPI_RX_IRQn);
     NVIC_EnableIRQ(SPI_RX_IRQn);
     so_busy = false;
     so_irq_count = 0;
     so_spurious_irq_count = 0;
     so_irq_fake_count = 0;
     // register (but don't enable) rx pin GPIO interrupt
     gpio_irq_handler_install(RX_PORT, RX_PIN, SO_IRQ, NULL);
     }
Variable Documentation
USART_InitSync_TypeDef spiInit
#include <spi.c>
Initial value:
=
{
  .enable       = usartEnableRx | usartEnableTx,
  .refFreq      = 0,
  .baudrate     = 1000000,
  .databits     = usartDatabits8,
  .master       = true,
  .msbf         = true,
  .clockMode    = usartClockMode0,
  .prsRxEnable  = false,
  .prsRxCh      = usartPrsRxCh0,
  .autoTx       = false,
}
Definition at line 496 of file spi.c.
const gpio_init_t spi_pins[] static
#include <spi.c>
Initial value:
=
{
  {  gpioPortD ,  2 , gpioModePushPull,  0 },
  {  gpioPortD ,  3 , gpioModePushPull,  1 },
  {  gpioPortD ,  1 , gpioModeInputPull, 1 },
  {  gpioPortD ,  0 , gpioModePushPull,  1 },
}
Definition at line 510 of file spi.c.