Adesto Flash Demo: Adesto_FlashDrivers
Adesto_FlashDrivers
Data Structures
struct erase_info_t
struct spiflash_info_t
Macros
#define LED_DEBUG
#define CMD_READ_ARRAY 0x0b
#define CMD_READ_ARRAY_SLOW 0x03 /* no dummy byte, but limited to lower clock rate */
#define CMD_READ_ARRAY_DUAL 0x3b /* not used, as we don't have dual-SPI hardware */
#define CMD_PAGE_ERASE 0x81
#define CMD_RM25C_PAGE_ERASE 0x42 /* RM26C256DS only */
#define CMD_BLOCK_ERASE 0x20
#define CMD_BLOCK_ERASE_LARGE 0x52
#define CMD_BLOCK_ERASE_LARGER 0xd8
#define CMD_CHIP_ERASE 0x60
#define CMD_CHIP_ERASE2 0xc7 /* not used, exactly the same as CMD_CHIP_ERASE */
#define CMD_BYTE_PAGE_PROGRAM 0x02
#define CMD_SEQUENTIAL_PROGRAM 0xad /* not used, page program is more efficient */
#define CMD_SEQUENTIAL_PROGRAM2 0xaf /* not used, page program is more efficient */
#define CMD_BYTE_PAGE_PROGRAM_DUAL 0xa2 /* not used, as we don't have dual-SPI hardware */
#define CMD_WRITE_ENABLE 0x06
#define CMD_WRITE_DISABLE 0x04
#define CMD_PROTECT_SECTOR 0x36
#define CMD_UNPROTECT_SECTOR 0x39
#define CMD_READ_SECTOR_PROTECTION 0x3c
#define CMD_PROGRAM_OTP 0x9b
#define CMD_READ_OTP 0x77
#define CMD_READ_STATUS 0x05
#define CMD_DATAFLASH_READ_STATUS 0xd7
#define CMD_ACTIVE_STATUS_INTERRUPT 0x25
#define CMD_WRITE_STATUS_REG_BYTE_1 0x01
#define CMD_WRITE_STATUS_REG_BYTE_2 0x31
#define CMD_RESET 0xf0
#define CMD_READ_ID 0x9f
#define CMD_DEEP_POWER_DOWN 0xb9
#define CMD_RESUME_FROM_DEEP_POWER_DOWN 0xab
#define CMD_ULTRA_DEEP_POWER_DOWN 0x79
#define ARG_RESET 0xd0 /* second byte required for reset command */
#define CMD_DATAFLASH_BLOCK_ERASE 0x50 /* 8 pages, 2KB */
#define CMD_DATAFLASH_SECTOR_ERASE 0x7c
#define CMD_DATAFLASH_RMW_BUF1 0x58
#define CMD_DATAFLASH_RMW_BUF2 0x59
#define SPIFLASH_INFO_TABLE_SIZE (sizeof(spiflash_info_table) / sizeof(spiflash_info_t))
#define MAX_FLASH_ID_LEN 8
#define MAX_ERASE_SIZES 5
Typedefs
typedef void spiflash_completion_fn_t (void *ref)
Enumerations
enum spiflash_id_t {
AT25SF041, AT25XE021A, AT25XE041B, AT25DB081E,
AT25DB641E, RM25C256DS, PART_UNKNOWN
}
Functions
static bool addr_aligned (uint32_t addr, size_t alignment_size)
Checks if address is aligned on a power of 2.
static void spiflash_spi_simple_completion (void *ref)
Simple spi simple completion routine.
void spiflash_single_byte_command (uint8_t cmd, size_t rx_len, uint8_t *rx_buf, spiflash_completion_fn_t *completion, void *completion_ref)
SPI Flash Single Byte Command.
void spiflash_multiple_byte_command (size_t tx_len, const uint8_t *tx_buf, size_t rx_len, uint8_t *rx_buf, bool hold_cs_active, spiflash_completion_fn_t *completion, void *completion_ref)
SPI Flash Multi-Byte Command.
void spiflash_command_with_address (uint8_t cmd, uint32_t addr, unsigned int dummy_bytes, size_t tx_len, uint8_t *tx_buf, size_t rx_len, uint8_t *rx_buf, spiflash_completion_fn_t *completion, void *completion_ref)
SPI Flash Command with Address.
void spiflash_read (uint32_t addr, size_t len, uint8_t *buffer, spiflash_completion_fn_t *completion, void *completion_ref)
SPI Flash Read.
static void spiflash_erase_completion1 (void *ref)
SPI Erase Completion State 1(initial state)
static void spiflash_erase_completion2 (void *ref)
SPI Erase Completion State 2.
static void spiflash_erase_completion3 (void *ref)
SPI Erase Completion State 3.
static void spiflash_erase_completion4 (void *ref)
SPI Erase Completion State 4.
static void spiflash_erase_completion5 (void *ref)
SPI Erase Completion State 5.
bool spiflash_erase (uint32_t addr, size_t len, uint32_t cmd_size, bool use_so_irq, spiflash_completion_fn_t *completion, void *completion_ref)
SPI Flash Erase.
static void spiflash_write_completion1 (void *ref)
SPI Write Completion State 1(initial state)
static void spiflash_write_completion2 (void *ref)
SPI Write Completion State 2.
static void spiflash_write_completion3 (void *ref)
SPI Write Completion State 3.
static void spiflash_write_completion4 (void *ref)
SPI Write Completion State 4.
static void spiflash_write_completion5 (void *ref)
SPI Write Completion State 5.
void spiflash_write (uint32_t addr, size_t len, uint8_t *buffer, bool use_so_irq, spiflash_completion_fn_t *completion, void *completion_ref)
SPI Flash Write.
static void dataflash_rmw_completion1 (void *ref)
DataFlash Read-Modify-Write Completion State 1(initial state)
static void dataflash_rmw_completion2 (void *ref)
DataFlash Read-Modify-Write Completion State 2.
static void dataflash_rmw_completion3 (void *ref)
DataFlash Read-Modify-Write Completion State 3.
void dataflash_rmw (uint32_t addr, size_t len, uint8_t *buffer, spiflash_completion_fn_t *completion, void *completion_ref)
SPI DataFlash Read-Modify-Write Function.
void spiflash_set_write_enable (bool enable, spiflash_completion_fn_t *completion, void *completion_ref)
Send Write Enable/Disable Command.
void spiflash_set_sector_protection (bool protect, uint32_t addr, spiflash_completion_fn_t *completion, void *completion_ref)
Send Sector Protect/Unprotect Command.
void spiflash_set_global_protect (bool protect, spiflash_completion_fn_t *completion, void *completion_ref)
Send Global Protect Command.
void spiflash_reset (spiflash_completion_fn_t *completion, void *completion_ref)
Send Reset Command.
void spiflash_read_otp (uint32_t addr, size_t len, uint8_t *buffer, spiflash_completion_fn_t *completion, void *completion_ref)
Send Read OTP command.
void spiflash_write_otp (uint32_t addr, size_t len, uint8_t *buffer, spiflash_completion_fn_t *completion, void *completion_ref)
Send Write OTP command.
void spiflash_read_status (size_t len, uint8_t *buffer, spiflash_completion_fn_t *completion, void *completion_ref)
Read Status Register.
void spiflash_write_status (uint8_t data, spiflash_completion_fn_t *completion, void *completion_ref)
Write First Status Register.
void spiflash_write_status2 (uint8_t data, spiflash_completion_fn_t *completion, void *completion_ref)
Write Second Status Register.
void spiflash_read_id (size_t len, uint8_t *buffer, spiflash_completion_fn_t *completion, void *completion_ref)
Read Device ID.
void spiflash_deep_power_down (bool power_down, spiflash_completion_fn_t *completion, void *completion_ref)
Enter/Resume from Deep PowerDown.
void spiflash_ultra_deep_power_down (bool power_down, spiflash_completion_fn_t *completion, void *completion_ref)
Enter/Resume from Ultra Deep PowerDown.
bool spiflash_is_dataflash (void)
Determines if Device is DataFlash or note.
uint32_t dataflash_get_page_size (void)
Get DataFlash Page Size.
bool dataflash_set_page_size (uint32_t page_size)
Set DataFlash Page Size.
spiflash_id_t spiflash_init (int bit_rate)
Initialize SPI Bus, Read Device ID, Determine Device properties.
uint32_t spiflash_smallest_erase_size_above (uint32_t size)
Determine smallest Erase Page Size.
Variables
int i
int cycle_count = 0
static const uint8_t at25xe021a_id_bytes [] = { 0x1f, 0x43, 0x01, 0x00 }
static const size_t at25xe021a_protection_sector_sizes [] = { 65536, 65536, 65536, 65536 }
static const uint8_t at25xe041b_id_bytes [] = { 0x1f, 0x44, 0x02, 0x00 }
static const size_t at25xe041b_protection_sector_sizes [] = { 65536, 65536, 65536, 65536, 65536, 65536, 65536, 32768, 8192, 8192, 16384 }
static const uint8_t dataflash_cmd_set_256b_page [] = { 0x3d, 0x2a, 0x80, 0xa6 }
static const uint8_t dataflash_cmd_set_264b_page [] = { 0x3d, 0x2a, 0x80, 0xa7 }
static const uint8_t dataflash_cmd_chip_erase [] = { 0xc7, 0x94, 0x80, 0x9a }
static const uint8_t dataflash_cmd_disable_sector_protection [] = { 0x3d, 0x2a, 0x7f, 0x9a }
const spiflash_info_t spiflash_info_table []
static const spiflash_info_t * spiflash_info
static bool spiflash_use_so_irq
static bool spiflash_busy
static spiflash_completion_fn_t * spiflash_completion
static void * spiflash_completion_ref
static uint8_t spiflash_scratch_buf [257]
static const erase_info_t * erase_info_fixed
static const erase_info_t * erase_info
static uint32_t erase_addr
static size_t erase_len
static uint8_t erase_status_buf [2]
static volatile bool spiflash_erase_busy
static uint8_t * write_data
static uint32_t write_addr
static size_t write_len
static size_t write_size
static uint8_t write_status_buf [2]
static volatile bool spiflash_write_busy
const spiflash_info_t spiflash_info_table []
Detailed Description
Function Documentation
static bool addr_aligned (uint32_t addr, size_t alignment_size) static
#include <spiflash.c>
Checks if address is aligned on a power of 2.
Note
Determines if address is aligned to a multiple of alignment_size which is a power of 2. Alignment_size is read from Device table in spiflash.c
Parameters
[in] addr Address to check Power of 2 alignment
[in] alignment_size Alignment_size used to validate if Power of 2
Returns
TRUE if aligned on Power of 2, False if not.
Definition at line 271 of file spiflash.c.
Referenced by spiflash_erase(), and spiflash_erase_completion2().
 {
     return (addr & (alignment_size-1)) == 0;
 }
static void spiflash_spi_simple_completion (void * ref) static
#include <spiflash.c>
Simple spi simple completion routine.
Note
Parameters
[in] *ref TODO What is *ref ???
Definition at line 285 of file spiflash.c.
Referenced by dataflash_rmw_completion3(), spiflash_command_with_address(), spiflash_erase_completion1(), spiflash_multiple_byte_command(), spiflash_single_byte_command(), and spiflash_write_completion1().
 {
     (void) ref;
     // copy completion fn ptr and ref arg, to avoid race condition
     // if completion fn starts another spiflash command
     spiflash_completion_fn_t *completion = spiflash_completion;
     void *spiflash_ref = spiflash_completion_ref;
     spiflash_completion = NULL;
     spiflash_busy = false;
     if (completion)
         completion(spiflash_ref);
 }
void spiflash_single_byte_command (uint8_t cmd, size_t rx_len, uint8_t * rx_buf, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
SPI Flash Single Byte Command.
Note
spiflash_single_byte_command() can be used to issue any single-byte command. The reading of the response will begin after the command byte is written. If no response is to be read, pass rx_len == 0.
Parameters
[in] cmd Command to send
[in] rx_len Expected response length, set to 0 if no response is expected.
[in] *rx_buf Pointer to Rx buffer where response is placed.
[in] *completion Completion function for Completion State_Machine
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 319 of file spiflash.c.
References enter_low_power_state(), spi_xfer(), and spiflash_spi_simple_completion().
Referenced by dataflash_rmw_completion3(), spiflash_deep_power_down(), spiflash_erase_completion1(), spiflash_erase_completion2(), spiflash_erase_completion5(), spiflash_read_id(), spiflash_read_status(), spiflash_set_write_enable(), spiflash_ultra_deep_power_down(), spiflash_write_completion1(), and spiflash_write_completion5().
 {
     spiflash_scratch_buf[0] = cmd;
     spiflash_completion = completion;
     spiflash_completion_ref = completion_ref;
     spiflash_busy = true;
     spi_xfer(1, spiflash_scratch_buf,  // tx1
              0, NULL,                  // tx2
              true,                     // half duplex
              rx_len, rx_buf,           // rx
              false,                    // hold cs active
              spiflash_spi_simple_completion,
              NULL);
     if (! completion)
         while (spiflash_busy)
             enter_low_power_state();
 }
void spiflash_multiple_byte_command (size_t tx_len, const uint8_t * tx_buf, size_t rx_len, uint8_t * rx_buf, bool hold_cs_active, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
SPI Flash Multi-Byte Command.
Note
spiflash_multiple_byte_command() can be used to issue commands of any length. The reading of the response will begin after the last command byte is written. If no response is to be read, pass rx_len == 0.
Parameters
[in] tx_len Length of command to send in bytes
[in] *tx_buf Pointer to command buffer to send
[in] rx_len Expected response length, set to 0 if no response is expected.
[in] *rx_buf Pointer to Rx buffer where response is placed.
[in] hold_cs_active Hold Chip Select High: True/False
[in] *completion Completion function for Completion State_Machine
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 367 of file spiflash.c.
References enter_low_power_state(), spi_xfer(), and spiflash_spi_simple_completion().
Referenced by dataflash_rmw(), dataflash_set_page_size(), spiflash_erase(), spiflash_erase_completion2(), spiflash_erase_completion3(), spiflash_reset(), spiflash_set_global_protect(), spiflash_write(), and spiflash_write_completion3().
 {
     spiflash_completion = completion;
     spiflash_completion_ref = completion_ref;
     spiflash_busy = true;
     spi_xfer(tx_len, tx_buf,  // tx1
              0, NULL,         // tx2
              true,            // half duplex
              rx_len, rx_buf,  // rx
              hold_cs_active,  // hold cs active
              spiflash_spi_simple_completion,
              NULL);
     if (! completion)
         while (spiflash_busy)
             enter_low_power_state();
 }
void spiflash_command_with_address (uint8_t cmd, uint32_t addr, unsigned int dummy_bytes, size_t tx_len, uint8_t * tx_buf, size_t rx_len, uint8_t * rx_buf, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
SPI Flash Command with Address.
Note
spiflash_multiple_command_with_adddress() can be used to issue commands of any length. The reading of the response will begin after the last command byte is written. If no response is to be read, pass rx_len == 0.
Parameters
[in] cmd Command to send
[in] addr Address for command to use
[in] dumm_bytes Dummy bytes
[in] tx_len Length of command to send in bytes
[in] *tx_buf Pointer to command buffer to send
[in] rx_len Expected response length, set to 0 if no response is expected.
[in] *rx_buf Pointer to Rx buffer where response is placed.
[in] *completion Completion function for Completion State_Machine
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 419 of file spiflash.c.
References enter_low_power_state(), spi_xfer(), and spiflash_spi_simple_completion().
Referenced by dataflash_rmw_completion1(), spiflash_erase_completion2(), spiflash_read(), spiflash_read_otp(), spiflash_set_sector_protection(), spiflash_write_completion2(), and spiflash_write_otp().
 {
     int i = 0;
     spiflash_scratch_buf[i++] = cmd;
     if (spiflash_info->address_bytes >= 3)
         spiflash_scratch_buf[i++] = addr >> 16;
     if (spiflash_info->address_bytes >= 2)
         spiflash_scratch_buf[i++] = (addr >> 8) & 0xff;
     if (spiflash_info->address_bytes >= 1)
         spiflash_scratch_buf[i++] = addr & 0xff;
     memset(&spiflash_scratch_buf[i], 0, dummy_bytes);
     i += dummy_bytes;
     spiflash_completion = completion;
     spiflash_completion_ref = completion_ref;
     spiflash_busy = true;
     spi_xfer(i, spiflash_scratch_buf,  // tx1
              tx_len, tx_buf,                         // tx2
              true,                                   // half duplex
              rx_len, rx_buf,
              false,                    // hold cs active
              spiflash_spi_simple_completion,
              NULL);
     if (! completion)
         while (spiflash_busy)
             enter_low_power_state();
 }
void spiflash_read (uint32_t addr, size_t len, uint8_t * buffer, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
SPI Flash Read.
Note
Calls spiflash_command_with_address to perform Read operation Will block if NULL passed for completion function; otherwise will call completion function passing ref argument
Parameters
[in] addr Address to read from
[in] len How many bytes to read
[in] *buffer Buffer to place read data into. Passed into spiflash_command_with_address function.
[in] *completion Completion function for Completion State_Machine
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 479 of file spiflash.c.
References spiflash_command_with_address().
Referenced by appl_read(), demo_serial(), run_read(), and run_rmw_normal().
 {
     uint8_t cmd;
     int dummy_bytes;
     if (spiflash_info->read_slow)
     {
         cmd = CMD_READ_ARRAY_SLOW;
         dummy_bytes = 0;
     }
     else
     {
         cmd = CMD_READ_ARRAY;
         dummy_bytes = 1;
     }
     spiflash_command_with_address(cmd,
                                   addr,
                                   dummy_bytes,
                                   0, NULL,      // tx
                                   len, buffer,  // rx
                                   completion,
                                   completion_ref);
 }
static void spiflash_erase_completion1 (void * ref) static
#include <spiflash.c>
SPI Erase Completion State 1(initial state)
Note
First state in Erase completion process. Configures Write Enable.
Parameters
[in] *ref Completion Function Pointer
Definition at line 531 of file spiflash.c.
References spiflash_erase_completion2(), spiflash_single_byte_command(), and spiflash_spi_simple_completion().
Referenced by spiflash_erase(), spiflash_erase_completion4(), and spiflash_erase_completion5().
 {
     if (! erase_len)
     {
         spiflash_erase_busy = false;
         spiflash_spi_simple_completion(ref);
         return;
     }
     if (spiflash_info->dataflash)
         spiflash_erase_completion2(NULL);
     else
         spiflash_single_byte_command(CMD_WRITE_ENABLE,
                                      0, NULL,  // rx
                                      spiflash_erase_completion2,
                                      NULL);
 }
static void spiflash_erase_completion2 (void * ref) static
#include <spiflash.c>
SPI Erase Completion State 2.
Note
Issues ERASE Commands and checks what type of Erase is available on Device, checks address alignment
Parameters
[in] *ref Completion Function Pointer
Definition at line 558 of file spiflash.c.
References addr_aligned(), spiflash_command_with_address(), spiflash_erase_completion3(), spiflash_multiple_byte_command(), and spiflash_single_byte_command().
Referenced by spiflash_erase_completion1().
 {
     int i;
     if (erase_info_fixed)
         erase_info = erase_info_fixed;
     else
     {
         for (i = spiflash_info->erase_info_count - 1; i >= 0; i--)
         {
             erase_info = & spiflash_info->erase_info [i];
             if ((erase_len >= erase_info->size) &&
                 addr_aligned(erase_addr, erase_info->size))
                 break;
         }
         if (i < 0)
         {
             // no suitable erase command found!
             // should never happen
             erase_info = NULL;
             while (true)
                 ;
         }
     }
     if (erase_info->addr_needed)
     {
         spiflash_command_with_address(erase_info->cmd,
                                       erase_addr,
                                       0,        // dummy bytes
                                       0, NULL,  // tx
                                       0, NULL,  // rx
                                       spiflash_erase_completion3,
                                       NULL);
     }
     else if (spiflash_info->dataflash)
     {
         // chip erase for dataflash doesn't need an address, but is a multibyte command
         spiflash_multiple_byte_command(sizeof(dataflash_cmd_chip_erase), dataflash_cmd_chip_erase,
                                        0, NULL, // rx
                                        false, // hold_cs_active
                                        spiflash_erase_completion3,
                                        NULL);
     }
     else
     {
         // chip erase doesn't need an address
         spiflash_single_byte_command(erase_info->cmd,
                                      0, NULL,  // rx
                                      spiflash_erase_completion3,
                                      NULL);
     }
 }
static void spiflash_erase_completion3 (void * ref) static
#include <spiflash.c>
SPI Erase Completion State 3.
Note
An erase command has been issued. Advance the address and decrease the length in preparation for the next iteration. If erase_len drops to zero, that will be handled when it gets back to Completion 1. Determines whether or not to use Active SO or not. If Active SO is used go to Read completion 4 if not skip to Read completion 5.
Parameters
[in] *ref Completion Function Pointer
Definition at line 623 of file spiflash.c.
References spiflash_erase_completion4(), spiflash_erase_completion5(), and spiflash_multiple_byte_command().
Referenced by spiflash_erase_completion2().
 {
     erase_addr += erase_info->size;
     erase_len -= erase_info->size;
     if (spiflash_use_so_irq)
     {
         // use of SO is enabled, so issue ASI command
         spiflash_scratch_buf[0] = CMD_ACTIVE_STATUS_INTERRUPT;
         spiflash_scratch_buf[1] = 0x00;
         spiflash_multiple_byte_command(1, spiflash_scratch_buf,  // tx
                                        0, NULL,                  // rx
                                        true,                     // hold CS active
                                        spiflash_erase_completion4,
                                        NULL);
     }
     else
     {
         // use of SO is disabled, so start polling status register
         erase_status_buf[0] = spiflash_info->status_busy_level;  // prime pump w/ BUSY
         spiflash_erase_completion5(NULL);
     }
 }
static void spiflash_erase_completion4 (void * ref) static
#include <spiflash.c>
SPI Erase Completion State 4.
Note
This Read Completion State is ONLY used if Active SO is enabled. Returns to Completion 1 when completed.
Parameters
[in] *ref Completion Function Pointer
Definition at line 657 of file spiflash.c.
References spi_wait_so(), and spiflash_erase_completion1().
Referenced by spiflash_erase_completion3().
 {
     spi_wait_so(spiflash_info->so_done_level,
                     spiflash_erase_completion1,
                     NULL);
 }
static void spiflash_erase_completion5 (void * ref) static
#include <spiflash.c>
SPI Erase Completion State 5.
Note
This Read Completion State is ONLY used if Active SO is NOT used. Returns to Completion 1 when completed.
Parameters
[in] *ref Completion Function Pointer
Definition at line 673 of file spiflash.c.
References spiflash_erase_completion1(), and spiflash_single_byte_command().
Referenced by spiflash_erase_completion3().
 {
     if ((erase_status_buf[0] & spiflash_info->status_busy_mask) == spiflash_info->status_busy_level)
     {
         // BUSY
         spiflash_single_byte_command(spiflash_info->read_status_cmd,
                                      1,
                                      erase_status_buf,
                                      spiflash_erase_completion5,
                                      NULL);
     }
     else
     {
         // DONE
         spiflash_erase_completion1(NULL);
     }
 }
bool spiflash_erase (uint32_t addr, size_t len, uint32_t cmd_size, bool use_so_irq, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
SPI Flash Erase.
Note
Top Level SPI Erase function, steps through Erase completion states. Determines if Active SO is to be used or not. Checks address alignment. Enters Low Power State during Erase. The erase commands will be ignored by the flash chip unless it has been previously write-enabled. Will return false, and never call completion function, if address is not erase page aligned or len is not a multiple of erase page size.
Parameters
[in] addr Address to read from
[in] len How many bytes to read
[in] cmd_size Size of Command in Bytes
[in] use_so_irq Determines whether or not Active SO is used or not.
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
Returns
true If successful
Definition at line 717 of file spiflash.c.
References addr_aligned(), enter_low_power_state(), spiflash_erase_completion1(), and spiflash_multiple_byte_command().
Referenced by appl_erase(), demo_serial(), run_erase(), and run_rmw_normal().
 {
     int i;
     bool found = false;
     spiflash_use_so_irq = use_so_irq && spiflash_info->has_so_irq;
     if (cmd_size)
     {
         // The desired erase size per command was specified.
         // Find the matching erase command, and ensure the address is
         // suitably aligned and the erase size is a multiple of the
         // command size.
         if (len % cmd_size)
             return false;
         for (i = spiflash_info->erase_info_count - 1; i >= 0; i--)
         {
             erase_info_fixed = & spiflash_info->erase_info [i];
             if (cmd_size == erase_info_fixed->size)
             {
                 found = true;
                 break;
             }
         }
         if (! found)
         {
             erase_info_fixed = NULL;
             return false;
         }
     }
     else
     {
         // No erase size per command was specified.
         // Ensure that there is a suitable choice.
         for (i = spiflash_info->erase_info_count - 1; i >= 0; i--)
         {
             erase_info = & spiflash_info->erase_info [i];
             if (len % erase_info->size)
                 continue;
             if (! addr_aligned(addr, erase_info->size))
                 continue;
             found = true;
             break;
         }
         erase_info = NULL;  // will be chosen in spiflash_erase_completion2;
         if (! found)
             return false;
     }
     erase_addr = addr;
     erase_len = len;
     spiflash_completion = completion;
     spiflash_completion_ref = completion_ref;
     spiflash_erase_busy = true;
     if (spiflash_info->dataflash)
         spiflash_multiple_byte_command(sizeof(dataflash_cmd_disable_sector_protection), dataflash_cmd_disable_sector_protection,
                                        0, NULL, // rx
                                        false, // hold_cs_active
                                        spiflash_erase_completion1,
                                        NULL);
     else
         spiflash_erase_completion1(NULL);
     // if called synchronously, wait for entire write sequence to complete
     if (! completion)
     {
         while (spiflash_erase_busy)
         {
             enter_low_power_state();
         }
     }
     return true;
 }
static void spiflash_write_completion1 (void * ref) static
#include <spiflash.c>
SPI Write Completion State 1(initial state)
Note
First State in Write completion process. Configures Write Enable.
Parameters
[in] *ref Completion Function Pointer
Definition at line 820 of file spiflash.c.
References spiflash_single_byte_command(), spiflash_spi_simple_completion(), and spiflash_write_completion2().
Referenced by spiflash_write(), spiflash_write_completion4(), spiflash_write_completion5(), and spiflash_write_otp().
 {
     if (! write_len)
     {
         spiflash_write_busy = false;
         spiflash_spi_simple_completion(ref);
         return;
     }
     if (spiflash_info->dataflash)
         spiflash_write_completion2(NULL);
     else
         spiflash_single_byte_command(CMD_WRITE_ENABLE,
                                      0, NULL,  // rx
                                      spiflash_write_completion2,
                                      NULL);
 }
static void spiflash_write_completion2 (void * ref) static
#include <spiflash.c>
SPI Write Completion State 2.
Note
Issues Write Command with Address and check Program Page size
Parameters
[in] *ref Completion Function Pointer
Definition at line 846 of file spiflash.c.
References spiflash_command_with_address(), and spiflash_write_completion3().
Referenced by spiflash_write_completion1().
 {
     write_size = write_len;
     if ((write_addr & ~(spiflash_info->program_page_size-1)) !=
         ((write_addr + write_size - 1) & ~(spiflash_info->program_page_size-1)))
         write_size = spiflash_info->program_page_size - (write_addr & (spiflash_info->program_page_size-1));
     spiflash_command_with_address(CMD_BYTE_PAGE_PROGRAM,
                                   write_addr,
                                   0, // dummy bytes
                                   write_size, write_data,  // tx
                                   0, NULL,                 // rx
                                   spiflash_write_completion3,
                                   NULL);
 }
static void spiflash_write_completion3 (void * ref) static
#include <spiflash.c>
SPI Write Completion State 3.
Note
A write command has been issued. Advance the address and decrease the length in preparation for the next iteration. If erase_len drops to zero, that will be handled when it gets back to Completion 1. Determines whether or not to use Active SO or not. If Active SO is used go to Write completion 4 if not skip to Write completion 5.
Parameters
[in] *ref Completion Function Pointer
Definition at line 875 of file spiflash.c.
References spiflash_multiple_byte_command(), spiflash_write_completion4(), and spiflash_write_completion5().
Referenced by spiflash_write_completion2().
 {
     // Write is in progress, but advance the address
     // and decrease the length in preparation for next
     // iteration.  If write_len drops to zero, that will
     // be handled when we get to
     // spiflash_write_completion1().
     write_data += write_size;
     write_addr += write_size;
     write_len -= write_size;
     if (spiflash_use_so_irq == 1)
     {
         // use of SO is enabled, so issue ASI command
         spiflash_scratch_buf[0] = CMD_ACTIVE_STATUS_INTERRUPT;
         spiflash_scratch_buf[1] = 0x00;
         spiflash_multiple_byte_command(2, spiflash_scratch_buf,  // tx
                                        0, NULL,                  // rx
                                        true,                     // hold CS active
                                        spiflash_write_completion4,
                                        NULL);
     }
     else
     {
         // use of SO is disabled, so start polling status register
         write_status_buf[0] = spiflash_info->status_busy_level;  // prime pump w/ BUSY
         spiflash_write_completion5(NULL);
     }
 }
static void spiflash_write_completion4 (void * ref) static
#include <spiflash.c>
SPI Write Completion State 4.
Note
This Write completion state is ONLY used if Active SO is enabled. Returns to Write completion 1 when completed.
Parameters
[in] *ref Completion Function Pointer
Definition at line 915 of file spiflash.c.
References spi_wait_so(), and spiflash_write_completion1().
Referenced by spiflash_write_completion3().
 {
     // wait for flash chip to be done with command,
     // then invoke completion1
     spi_wait_so(spiflash_info->so_done_level,
                 spiflash_write_completion1,
                 NULL);
 }
static void spiflash_write_completion5 (void * ref) static
#include <spiflash.c>
SPI Write Completion State 5.
Note
This Write completion state is ONLY used if Active SO is NOT used. Returns to Write completion 1 when completed.
Parameters
[in] *ref Completion Function Pointer
Definition at line 933 of file spiflash.c.
References spiflash_single_byte_command(), and spiflash_write_completion1().
Referenced by spiflash_write_completion3().
 {
     if ((write_status_buf[0] & spiflash_info->status_busy_mask) == spiflash_info->status_busy_level)
     {
         // BUSY
         spiflash_single_byte_command(spiflash_info->read_status_cmd,
                                      1,
                                      write_status_buf,
                                      spiflash_write_completion5,
                                      NULL);
     }
     else
     {
         // DONE
         spiflash_write_completion1(NULL);
     }
 }
void spiflash_write (uint32_t addr, size_t len, uint8_t * buffer, bool use_so_irq, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
SPI Flash Write.
Note
Top Level SPI Write function, steps through Write completion states. Determines if Active SO is to be used or not. Enters Low Power State during Write.
Parameters
[in] addr Address to write to
[in] len How many bytes to write
[in] *buffer Pointer to data buffer to use for write.
[in] use_so_irq Determines whether or not Active SO is used or not.
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 971 of file spiflash.c.
References enter_low_power_state(), spiflash_multiple_byte_command(), and spiflash_write_completion1().
Referenced by appl_write(), demo_serial(), run_program(), and run_rmw_normal().
 {
     spiflash_use_so_irq = use_so_irq && spiflash_info->has_so_irq;
     write_data = buffer;
     write_addr = addr;
     write_len = len;
     spiflash_completion = completion;
     spiflash_completion_ref = completion_ref;
     spiflash_write_busy = true;
     if (spiflash_info->dataflash)
         spiflash_multiple_byte_command(sizeof(dataflash_cmd_disable_sector_protection), dataflash_cmd_disable_sector_protection,
                                        0, NULL, // rx
                                        false, // hold_cs_active
                                        spiflash_write_completion1,
                                        NULL);
     else
         spiflash_write_completion1(NULL);
     // if called synchronously, wait for entire write sequence to complete
     if (! completion)
         while (spiflash_write_busy)
             enter_low_power_state();
 }
static void dataflash_rmw_completion1 (void * ref) static
#include <spiflash.c>
DataFlash Read-Modify-Write Completion State 1(initial state)
Note
First State in Write completion process. Sends RMW command
Parameters
[in] *ref Completion Function Pointer
Definition at line 1016 of file spiflash.c.
References dataflash_rmw_completion2(), and spiflash_command_with_address().
Referenced by dataflash_rmw().
 {
     spiflash_command_with_address(CMD_DATAFLASH_RMW_BUF1,
                                   write_addr,
                                   0, // dummy bytes
                                   write_size, write_data,  // tx
                                   0, NULL,                 // rx
                                   dataflash_rmw_completion2,
                                   NULL);
 }
static void dataflash_rmw_completion2 (void * ref) static
#include <spiflash.c>
DataFlash Read-Modify-Write Completion State 2.
Note
Second State in DataFlash Read-Modify-Write completion process. Starts polling Status Register.
Parameters
[in] *ref Completion Function Pointer
Definition at line 1036 of file spiflash.c.
References dataflash_rmw_completion3().
Referenced by dataflash_rmw_completion1().
 {
     // start polling status register
     write_status_buf[0] = spiflash_info->status_busy_level;  // prime pump w/ BUSY
     dataflash_rmw_completion3(NULL);
 }
static void dataflash_rmw_completion3 (void * ref) static
#include <spiflash.c>
DataFlash Read-Modify-Write Completion State 3.
Note
Third(last) State in DataFlash Read-Modify-Write completion process. Continues polling Status Register.
Parameters
[in] *ref Completion Function Pointer
Definition at line 1052 of file spiflash.c.
References spiflash_single_byte_command(), and spiflash_spi_simple_completion().
Referenced by dataflash_rmw_completion2().
 {
     // poll the status register
     // until the flash indicates that the RMW is done.
     if ((write_status_buf[0] & spiflash_info->status_busy_mask) == spiflash_info->status_busy_level)
     {
         // BUSY
         spiflash_single_byte_command(spiflash_info->read_status_cmd,
                                      1,
                                      write_status_buf,
                                      dataflash_rmw_completion3,
                                      NULL);
     }
     else
     {
         // DONE
         spiflash_write_busy = false;
         spiflash_spi_simple_completion(ref);
     }
 }
void dataflash_rmw (uint32_t addr, size_t len, uint8_t * buffer, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
SPI DataFlash Read-Modify-Write Function.
Note
Perform RMW operation on a page of dataflash, steps through RMW completion states. Enters Low Power State during Write.
Reponsibilities of caller: ensure that check that part is dataflash ensure that len is not greater than page length ensure that addr + len does not cross a page boundary
Parameters
[in] addr Address to read from
[in] len How many bytes to update/perform RMW
[in] *buffer Pointer to data buffer to use for write.
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 1095 of file spiflash.c.
References dataflash_rmw_completion1(), enter_low_power_state(), and spiflash_multiple_byte_command().
Referenced by run_rmw_dataflash().
 {
     write_data = buffer;
     write_addr = addr;
     write_len = len;
     spiflash_completion = completion;
     spiflash_completion_ref = completion_ref;
     spiflash_write_busy = true;
     spiflash_multiple_byte_command(sizeof(dataflash_cmd_disable_sector_protection), dataflash_cmd_disable_sector_protection,
                                    0, NULL, // rx
                                    false, // hold_cs_active
                                    dataflash_rmw_completion1,
                                    NULL);
     // if called synchronously, wait for entire write sequence to complete
     if (! completion)
         while (spiflash_write_busy)
             enter_low_power_state();
 }
void spiflash_set_write_enable (bool enable, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Send Write Enable/Disable Command.
Parameters
[in] *ref Completion Function Pointer
Definition at line 1127 of file spiflash.c.
References spiflash_single_byte_command().
Referenced by run_program(), test_start(), and write_enable().
 {
     spiflash_single_byte_command(enable ? CMD_WRITE_ENABLE : CMD_WRITE_DISABLE,
                                  0, NULL,  // rx
                                  completion,
                                  completion_ref);
 }
void spiflash_set_sector_protection (bool protect, uint32_t addr, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Send Sector Protect/Unprotect Command.
Parameters
[in] protect True/False
[in] addr Address/Sector to protect
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 1149 of file spiflash.c.
References spiflash_command_with_address().
Referenced by demo_serial().
 {
     spiflash_command_with_address(protect? CMD_PROTECT_SECTOR : CMD_UNPROTECT_SECTOR,
                                   addr,
                                   0, // dummy bytes
                                   0, NULL,  // tx
                                   0, NULL,  // rx
                                   completion,
                                   completion_ref);
 }
void spiflash_set_global_protect (bool protect, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Send Global Protect Command.
Parameters
[in] protect True/False
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 1174 of file spiflash.c.
References spiflash_multiple_byte_command().
Referenced by test_start().
 {
     spiflash_scratch_buf[0] = CMD_WRITE_STATUS_REG_BYTE_1;
     spiflash_scratch_buf[1] = protect ? 0x3c : 0x00;
     spiflash_multiple_byte_command(2, spiflash_scratch_buf,  // tx
                                    0, NULL, // rx
                                    false,  // hold_cs_active
                                    completion,
                                    completion_ref);
 }
void spiflash_reset (spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Send Reset Command.
Note
Currently not being used...untested The reset command will be ignored by the flash chip unless it has been previously enabled by writing a 1 to the RSTE bit of the status register
Parameters
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 1202 of file spiflash.c.
References spiflash_multiple_byte_command().
 {
     spiflash_scratch_buf[0] = CMD_RESET;
     spiflash_scratch_buf[1] = ARG_RESET;
     spiflash_multiple_byte_command(2, spiflash_scratch_buf,  // tx
                                    0, NULL, // rx
                                    false,  // hold_cs_active
                                    completion,
                                    completion_ref);
 }
void spiflash_read_otp (uint32_t addr, size_t len, uint8_t * buffer, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Send Read OTP command.
Note
Currently not being used...untested
Parameters
[in] addr OTP Address to read
[in] len How many OTP bytes to read
[in] Pointer to buffer to store read bytes.
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 1231 of file spiflash.c.
References spiflash_command_with_address().
 {
     spiflash_command_with_address(CMD_READ_OTP,
                                   addr,
                                   2,  // dummy bytes
                                   0, NULL,      // tx
                                   len, buffer,  // rx
                                   completion,
                                   completion_ref);
 }
void spiflash_write_otp (uint32_t addr, size_t len, uint8_t * buffer, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Send Write OTP command.
Note
Currently not being used...untested
Parameters
[in] addr OTP Address to write
[in] len How many OTP bytes to write
[in] *buffer Pointer to buffer with data to write.
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 1262 of file spiflash.c.
References spiflash_command_with_address(), and spiflash_write_completion1().
 {
     spiflash_command_with_address(CMD_PROGRAM_OTP,
                                   addr,
                                   0, // dummy bytes
                                   len, buffer,  // tx
                                   0, NULL,      // rx
                                   spiflash_write_completion1,
                                   NULL);
 }
void spiflash_read_status (size_t len, uint8_t * buffer, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Read Status Register.
Note
For Adesto AT25XE021A and AT25XE041B, there are two bytes which can be read with a single call with len == 2.
Parameters
[in] len Number bytes to read
[in] *buffer Pointer to buffer store read bytes to.
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 1292 of file spiflash.c.
References spiflash_single_byte_command().
Referenced by dataflash_get_page_size(), dataflash_set_page_size(), get_status(), and test_start().
 {
     spiflash_single_byte_command(spiflash_info->read_status_cmd,
                                  len,
                                  buffer,
                                  completion,
                                  completion_ref);
 }
void spiflash_write_status (uint8_t data, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Write First Status Register.
Parameters
[in] data Byte to write to status register
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
void spiflash_write_status2 (uint8_t data, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Write Second Status Register.
Parameters
[in] data Byte to write to status register
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
void spiflash_read_id (size_t len, uint8_t * buffer, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Read Device ID.
Parameters
[in] len Byte to write to status register
[in] *buffer Pointer to buffer to store Device ID
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 1344 of file spiflash.c.
References spiflash_single_byte_command().
Referenced by read_id(), and spiflash_init().
 {
     spiflash_single_byte_command(CMD_READ_ID,
                                  len, buffer, // rx
                                  completion,
                                  completion_ref);
 }
void spiflash_deep_power_down (bool power_down, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Enter/Resume from Deep PowerDown.
Parameters
[in] power_down True=Enter Deep PowerDown, False=Resume from Deep PowerDown
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 1365 of file spiflash.c.
References spiflash_single_byte_command().
Referenced by run_powerdn(), and spiflash_init().
 {
     spiflash_single_byte_command(power_down ? CMD_DEEP_POWER_DOWN : CMD_RESUME_FROM_DEEP_POWER_DOWN,
                                  0, NULL,  // rx
                                  completion,
                                  completion_ref);
 }
void spiflash_ultra_deep_power_down (bool power_down, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Enter/Resume from Ultra Deep PowerDown.
Parameters
[in] power_down True=Enter Ultra Deep PowerDown, False=Resume from Ultra Deep PowerDown
[in] *completion Completion Function pointer.
[in] *completion_ref Argument to be passed to completion callback function
Definition at line 1386 of file spiflash.c.
References spiflash_single_byte_command().
Referenced by demo_serial(), main(), run_powerdn(), test_start(), and test_stop().
 {
     // any command can be used to resume; device will otherwise ignore the cmd
     spiflash_single_byte_command(power_down ? CMD_ULTRA_DEEP_POWER_DOWN : CMD_RESUME_FROM_DEEP_POWER_DOWN,
                                  0, NULL,  // rx
                                  completion,
                                  completion_ref);
 }
bool spiflash_is_dataflash (void)
#include <spiflash.c>
Determines if Device is DataFlash or note.
Returns
TRUE/FALSE Looks up in Device table if device is Dataflash type: True/False
Definition at line 1404 of file spiflash.c.
Referenced by run_rmw().
 {
     return spiflash_info->dataflash;
 }
uint32_t dataflash_get_page_size (void)
#include <spiflash.c>
Get DataFlash Page Size.
Definition at line 1414 of file spiflash.c.
References spiflash_read_status().
Referenced by main().
 {
     uint8_t status_buf[2];
     if (! spiflash_info->dataflash)
         return false;
     spiflash_read_status(sizeof(status_buf), status_buf, NULL, NULL);
     if (status_buf[0] & 1)
         return 256;
     else
         return 264;
 }
bool dataflash_set_page_size (uint32_t page_size)
#include <spiflash.c>
Set DataFlash Page Size.
Parameters
[in] page_size Page size to set for DataFlash
Definition at line 1436 of file spiflash.c.
References spiflash_multiple_byte_command(), and spiflash_read_status().
Referenced by main().
 {
     const uint8_t *cmd;
     uint8_t status_buf[2];
     int cmd_len;
     if (! spiflash_info->dataflash)
         return false;
     if (page_size == 256)
     {
         cmd = dataflash_cmd_set_256b_page;
         cmd_len = sizeof(dataflash_cmd_set_256b_page);
     }
     else if (page_size == 264)
     {
         cmd = dataflash_cmd_set_264b_page;
         cmd_len = sizeof(dataflash_cmd_set_264b_page);
     }
     else
         return false;
     spiflash_multiple_byte_command(cmd_len, cmd,  // tx
                                    0, NULL, // rx
                                    false,  // hold_cs_active
                                    NULL,
                                    NULL);
     do
         spiflash_read_status(sizeof(status_buf), status_buf, NULL, NULL);
     while ((status_buf[0] & spiflash_info->status_busy_mask) == spiflash_info->status_busy_level);
     if (status_buf[0] & 1)
         return page_size == 256;
     else
         return page_size == 264;
 }
spiflash_id_t spiflash_init (int bit_rate)
#include <spiflash.c>
Initialize SPI Bus, Read Device ID, Determine Device properties.
Parameters
[in] bit_rate Sets SPI Bit Rate
Definition at line 1480 of file spiflash.c.
References spi_init(), spiflash_deep_power_down(), and spiflash_read_id().
Referenced by demo_serial(), and spiflash_setup().
 {
     int i;
     const spiflash_info_t *p;
     spi_init(bit_rate);
     spiflash_busy = false;
     spiflash_info = NULL;
     // issue a resume from deep power down synchronously
     spiflash_deep_power_down(false, NULL, NULL);
     spiflash_deep_power_down(false, NULL, NULL);
     // issue a read ID command synchronously
     spiflash_read_id(MAX_FLASH_ID_LEN, spiflash_scratch_buf, NULL, NULL);
     for (i = 0; i < SPIFLASH_INFO_TABLE_SIZE; i++)
     {
         p = & spiflash_info_table[i];
         if (memcmp(spiflash_scratch_buf, p->id_bytes, p->id_size) == 0)
         {
             spiflash_info = p;
             return i;
         }
     }
     return PART_UNKNOWN;
 }
uint32_t spiflash_smallest_erase_size_above (uint32_t size)
#include <spiflash.c>
Determine smallest Erase Page Size.
Parameters
[in] size Erase size
Definition at line 1516 of file spiflash.c.
Referenced by leave_conf_erase_size(), and main().
 {
     int i;
     const erase_info_t *ei;
     for (i = 0; i < spiflash_info->erase_info_count; i++)
     {
         ei = & spiflash_info->erase_info [i];
         if (ei->size > size)
             return ei->size;
     }
     return 0;
 }