Adesto Flash Demo: UART
UART
Functions
UART definitions and functions.
.
Macros
#define PASTE_(A, B) A##B
#define PASTE(A, B) PASTE_(A, B)
#define PASTE3_(A, B, C) A##B##C
#define PASTE3(A, B, C) PASTE3_(A, B, C)
#define SPORT PASTE(LEUART, LEUART_NUM)
#define SERIAL_ROUTE_TXPEN LEUART_ROUTE_TXPEN
#define SERIAL_ROUTE_RXPEN LEUART_ROUTE_RXPEN
#define SERIAL_ROUTE_LOCATION_SHIFT _LEUART_ROUTE_LOCATION_SHIFT
#define SERIAL_TX_IRQn PASTE3(LEUART, LEUART_NUM, _IRQn)
#define SERIAL_RX_IRQn PASTE3(LEUART, LEUART_NUM, _IRQn)
#define SERIAL_TX_IRQHandler PASTE3(LEUART, LEUART_NUM, _TX_IRQHandler)
#define SERIAL_RX_IRQHandler PASTE3(LEUART, LEUART_NUM, _RX_IRQHandler)
#define SERIAL_IRQHandler PASTE3(LEUART, LEUART_NUM, _IRQHandler)
#define serial_cmuclock1 cmuClock_CORELE
#define serial_cmuclock2 PASTE(cmuClock_LEUART, LEUART_NUM)
#define serial_reset LEUART_Reset
#define serial_initasync LEUART_Init
#define serial_baudrateset LEUART_BaudrateSet
#define serial_intclear LEUART_IntClear
#define serial_intenable LEUART_IntEnable
#define STATUS_TXC LEUART_STATUS_TXC
#define IF_RXDATAV LEUART_IF_RXDATAV
#define IF_TXBL LEUART_IF_TXBL
#define IEN_RXDATAV LEUART_IEN_RXDATAV
#define IEN_TXBL LEUART_IEN_TXBL
#define INIT_STRUCT LEUART_Init_Typedef
#define RX_PORT gpioPortD
#define RX_PIN 5
#define TX_PORT gpioPortD
#define TX_PIN 4
Functions
void LEUART0_RX_IRQHandler (void)
void LEUART0_TX_IRQHandler (void)
void LEUART0_IRQHandler (void)
void serial_blocking_write_char (char c)
void serial_blocking_write_str (const char *p)
void serial_close (void)
void serial_init (int bit_rate, uint8_t *raw_rx_buf, size_t raw_rx_buf_size, uint8_t *raw_tx_buf, size_t raw_tx_buf_size)
void serial_tx_flush (void)
int RETARGET_WriteChar (char c)
int RETARGET_ReadChar (void)
Variables
static buf_t * serial_tx_buf
static buf_t * serial_rx_buf
const gpio_init_t serial_pins []
LEUART_Init_TypeDef sportInit
Detailed Description
UART definitions and functions.
.
Macro Definition Documentation
#define PASTE_ (A, B) A##B
#include <serial.c>
Definition at line 60 of file serial.c.
#define PASTE (A, B) PASTE_(A, B)
#include <serial.c>
Definition at line 61 of file serial.c.
#define PASTE3_ (A, B, C) A##B##C
#include <serial.c>
Definition at line 63 of file serial.c.
#define PASTE3 (A, B, C) PASTE3_(A, B, C)
#include <serial.c>
Definition at line 64 of file serial.c.
#define SPORT PASTE(LEUART, LEUART_NUM)
#include <serial.c>
Definition at line 72 of file serial.c.
Referenced by LEUART0_RX_IRQHandler(), LEUART0_TX_IRQHandler(), serial_blocking_write_char(), serial_close(), and serial_init().
#define SERIAL_ROUTE_TXPEN LEUART_ROUTE_TXPEN
#include <serial.c>
Definition at line 73 of file serial.c.
Referenced by serial_init().
#define SERIAL_ROUTE_RXPEN LEUART_ROUTE_RXPEN
#include <serial.c>
Definition at line 74 of file serial.c.
Referenced by serial_init().
#define SERIAL_ROUTE_LOCATION_SHIFT _LEUART_ROUTE_LOCATION_SHIFT
#include <serial.c>
Definition at line 75 of file serial.c.
Referenced by serial_init().
#define SERIAL_TX_IRQn PASTE3(LEUART, LEUART_NUM, _IRQn)
#include <serial.c>
Definition at line 76 of file serial.c.
Referenced by serial_init().
#define SERIAL_RX_IRQn PASTE3(LEUART, LEUART_NUM, _IRQn)
#include <serial.c>
Definition at line 77 of file serial.c.
Referenced by serial_init().
#define SERIAL_TX_IRQHandler PASTE3(LEUART, LEUART_NUM, _TX_IRQHandler)
#include <serial.c>
Definition at line 78 of file serial.c.
Referenced by LEUART0_IRQHandler().
#define SERIAL_RX_IRQHandler PASTE3(LEUART, LEUART_NUM, _RX_IRQHandler)
#include <serial.c>
Definition at line 79 of file serial.c.
Referenced by LEUART0_IRQHandler().
#define SERIAL_IRQHandler PASTE3(LEUART, LEUART_NUM, _IRQHandler)
#include <serial.c>
Definition at line 80 of file serial.c.
#define serial_cmuclock1 cmuClock_CORELE
#include <serial.c>
Definition at line 81 of file serial.c.
Referenced by serial_init().
#define serial_cmuclock2 PASTE(cmuClock_LEUART, LEUART_NUM)
#include <serial.c>
Definition at line 82 of file serial.c.
Referenced by serial_init().
#define serial_reset LEUART_Reset
#include <serial.c>
Definition at line 83 of file serial.c.
Referenced by serial_close(), and serial_init().
#define serial_initasync LEUART_Init
#include <serial.c>
Definition at line 84 of file serial.c.
Referenced by serial_init().
#define serial_baudrateset LEUART_BaudrateSet
#include <serial.c>
Definition at line 85 of file serial.c.
Referenced by serial_init().
#define serial_intclear LEUART_IntClear
#include <serial.c>
Definition at line 86 of file serial.c.
Referenced by serial_init().
#define serial_intenable LEUART_IntEnable
#include <serial.c>
Definition at line 87 of file serial.c.
Referenced by serial_init().
#define STATUS_TXC LEUART_STATUS_TXC
#include <serial.c>
Definition at line 88 of file serial.c.
#define IF_RXDATAV LEUART_IF_RXDATAV
#include <serial.c>
Definition at line 89 of file serial.c.
Referenced by LEUART0_RX_IRQHandler(), and serial_init().
#define IF_TXBL LEUART_IF_TXBL
#include <serial.c>
Definition at line 90 of file serial.c.
Referenced by LEUART0_TX_IRQHandler(), and serial_init().
#define IEN_RXDATAV LEUART_IEN_RXDATAV
#include <serial.c>
Definition at line 91 of file serial.c.
Referenced by LEUART0_RX_IRQHandler().
#define IEN_TXBL LEUART_IEN_TXBL
#include <serial.c>
Definition at line 92 of file serial.c.
Referenced by LEUART0_TX_IRQHandler(), and serial_blocking_write_char().
#define INIT_STRUCT LEUART_Init_Typedef
#include <serial.c>
Definition at line 93 of file serial.c.
#define RX_PORT gpioPortD
#include <serial.c>
Definition at line 96 of file serial.c.
#define RX_PIN 5
#include <serial.c>
Definition at line 97 of file serial.c.
#define TX_PORT gpioPortD
#include <serial.c>
Definition at line 98 of file serial.c.
#define TX_PIN 4
#include <serial.c>
Definition at line 99 of file serial.c.
Function Documentation
void LEUART0_RX_IRQHandler (void)
#include <serial.c>
Definition at line 317 of file serial.c.
References buf_full(), buf_write_byte(), buf::data, IEN_RXDATAV, IF_RXDATAV, and SPORT.
 {
     if (SPORT->IF & IF_RXDATAV)
     {
         uint8_t data = SPORT->RXDATA;
         buf_write_byte(serial_rx_buf, data);
         if (buf_full(serial_rx_buf))
             SPORT->IEN &= ~ IEN_RXDATAV;  // disable rx interrupt
     }
 }
void LEUART0_TX_IRQHandler (void)
#include <serial.c>
Definition at line 328 of file serial.c.
References buf_read_byte(), buf::data, IEN_TXBL, IF_TXBL, and SPORT.
 {
     if (SPORT->IF & IF_TXBL)
     {
         uint8_t data;
         if (buf_read_byte(serial_tx_buf, & data))
             SPORT->TXDATA = data;
         else
             SPORT->IEN &= ~ IEN_TXBL;  // disable tx interrupt
     }
 }
void LEUART0_IRQHandler (void)
#include <serial.c>
Definition at line 341 of file serial.c.
References SERIAL_RX_IRQHandler, and SERIAL_TX_IRQHandler.
 {
     SERIAL_RX_IRQHandler();
     SERIAL_TX_IRQHandler();
 }
void serial_blocking_write_char (char c)
#include <serial.c>
Definition at line 348 of file serial.c.
References buf_write_char(), IEN_TXBL, and SPORT.
Referenced by RETARGET_WriteChar(), and serial_blocking_write_str().
 {
     while (! buf_write_char(serial_tx_buf, c))
     {
         ;
     }
     SPORT->IEN |= IEN_TXBL;  // enable tx if not already going
 }
void serial_blocking_write_str (const char * p)
#include <serial.c>
Definition at line 357 of file serial.c.
References serial_blocking_write_char().
 {
     while (*p)
         serial_blocking_write_char(*p++);
 }
void serial_close (void)
#include <serial.c>
Definition at line 410 of file serial.c.
References serial_reset, and SPORT.
Referenced by demo_serial().
 {
     serial_reset(SPORT);
 }
void serial_init (int bit_rate, uint8_t * raw_rx_buf, size_t raw_rx_buf_size, uint8_t * raw_tx_buf, size_t raw_tx_buf_size)
#include <serial.c>
Definition at line 415 of file serial.c.
References gpio_init(), IF_RXDATAV, IF_TXBL, init_buf(), serial_baudrateset, serial_cmuclock1, serial_cmuclock2, serial_initasync, serial_intclear, serial_intenable, SERIAL_LOC, serial_reset, SERIAL_ROUTE_LOCATION_SHIFT, SERIAL_ROUTE_RXPEN, SERIAL_ROUTE_TXPEN, SERIAL_RX_IRQn, SERIAL_TX_IRQn, and SPORT.
Referenced by demo_serial().
 {
     serial_rx_buf = init_buf(raw_rx_buf, raw_rx_buf_size);
     serial_tx_buf = init_buf(raw_tx_buf, raw_tx_buf_size);
     CMU_ClockEnable(cmuClock_GPIO, true);
 #ifdef serial_cmuclock1
     CMU_ClockEnable(serial_cmuclock1, true);
 #endif
     CMU_ClockEnable(serial_cmuclock2, true);
     gpio_init(serial_pins, sizeof(serial_pins)/sizeof(gpio_init_t));
     serial_reset(SPORT);
     serial_initasync(SPORT, &sportInit);
     SPORT->ROUTE = SERIAL_ROUTE_TXPEN | SERIAL_ROUTE_RXPEN | (SERIAL_LOC << SERIAL_ROUTE_LOCATION_SHIFT);
     if (bit_rate)
 #if defined(LEUART_NUM)
         serial_baudrateset(SPORT, 0, bit_rate);
 #else
         serial_baudrateset(SPORT, 0, bit_rate, usartOVS16);
 #endif
     serial_intclear(SPORT, IF_RXDATAV | IF_TXBL);
     serial_intenable(SPORT, IF_RXDATAV);
     NVIC_ClearPendingIRQ(SERIAL_RX_IRQn);
     NVIC_EnableIRQ(SERIAL_RX_IRQn);
 #if SERIAL_RX_IRQn != SERIAL_TX_IRQn
     NVIC_ClearPendingIRQ(SERIAL_TX_IRQn);
     NVIC_EnableIRQ(SERIAL_TX_IRQn);
 #endif
 }
void serial_tx_flush (void)
#include <serial.c>
Definition at line 455 of file serial.c.
References buf_empty().
Referenced by demo_serial(), get_status(), and write_enable().
 {
     while (! buf_empty(serial_tx_buf))
         ;
 }
int RETARGET_WriteChar (char c)
#include <serial.c>
Definition at line 461 of file serial.c.
References serial_blocking_write_char().
 {
     serial_blocking_write_char(c);
     return 0;
 }
int RETARGET_ReadChar (void)
#include <serial.c>
Definition at line 467 of file serial.c.
 {
     return 0;
 }
Variable Documentation
buf_t* serial_tx_buf static
#include <serial.c>
Definition at line 313 of file serial.c.
buf_t* serial_rx_buf static
#include <serial.c>
Definition at line 314 of file serial.c.
const gpio_init_t serial_pins[]
#include <serial.c>
Initial value:
=
{
    {  gpioPortD ,  4 , gpioModePushPull,  1 },
    {  gpioPortD ,  5 , gpioModeInputPull, 1 },
}
Definition at line 379 of file serial.c.
LEUART_Init_TypeDef sportInit
#include <serial.c>
Initial value:
=
{
  .enable       = leuartEnableRx | leuartEnableTx,
  .refFreq      = 0,
  .baudrate     = 9600,
}
Definition at line 386 of file serial.c.