Adesto Flash Demo: Buttons
Buttons
Peripheral_Functions
STK Push-button definitions and function handlers for PB0/PB1.
.
Data Structures
struct button_info_t
Macros
#define BUTTON0_PORT gpioPortB
#define BUTTON0_PIN 9
#define BUTTON1_PORT gpioPortB
#define BUTTON1_PIN 10
Typedefs
typedef void button_callback_fn_t (int button, bool pressed)
Functions
void button_gpio_callback (void *ref)
Button Callback function.
void button_init (button_callback_fn_t *callback)
Push-button initialization.
Variables
static const button_info_t button_info []
static button_callback_fn_t * button_callback
gpio_init_t button_gpio_init []
Detailed Description
STK Push-button definitions and function handlers for PB0/PB1.
.
Function Documentation
void button_gpio_callback (void * ref)
#include <button.c>
Button Callback function.
Parameters
[in] *ref Pointer to Button callback function.
Definition at line 77 of file button.c.
Referenced by button_init().
 {
     int num = (int) ref;
     int state;
     const button_info_t *info = & button_info[num];
     state = ! GPIO_PinInGet(info->port, info->pin);
     button_callback(num, state);
 }
void button_init (button_callback_fn_t * callback)
#include <button.c>
Push-button initialization.
Parameters
[in] *callback Pointer to Button callback function.
Definition at line 102 of file button.c.
References button_gpio_callback(), gpio_init(), and gpio_irq_handler_install().
Referenced by main().
 {
     button_callback = callback;
     gpio_irq_handler_install(BUTTON0_PORT, BUTTON0_PIN, button_gpio_callback, (void *) 0);
     gpio_irq_handler_install(BUTTON1_PORT, BUTTON1_PIN, button_gpio_callback, (void *) 1);
     gpio_init(button_gpio_init, sizeof(button_gpio_init)/sizeof(gpio_init_t));
     // Set both falling and rising edge interrupts for both buttons
     GPIO_IntConfig(BUTTON0_PORT, BUTTON0_PIN, true, true, true);
     GPIO_IntConfig(BUTTON1_PORT, BUTTON1_PIN, true, true, true);
 }
Variable Documentation
const button_info_t button_info[] static
#include <button.c>
Initial value:
=
{
    {  gpioPortB ,  9  },
    {  gpioPortB ,  10  }
}
Definition at line 61 of file button.c.
gpio_init_t button_gpio_init[]
#include <button.c>
Initial value:
=
{
    {  gpioPortB ,  9 , gpioModeInputPullFilter, 1 },
    {  gpioPortB ,  10 , gpioModeInputPullFilter, 1 },
}
Definition at line 88 of file button.c.