Adesto Flash Demo: LED
LED
Peripheral_Functions
Macros
#define LED0_PORT gpioPortE
#define LED0_PIN 2
#define LED1_PORT gpioPortE
#define LED1_PIN 3
Functions
void led_init (void)
Initialize GPIO to drive LED.
void led_set (int num, int value)
Turn ON/OFF LED based on input Value.
Variables
static const gpio_init_t led_info []
Detailed Description
Function Documentation
void led_init (void)
#include <led.c>
Initialize GPIO to drive LED.
Definition at line 66 of file led.c.
References gpio_init().
Referenced by main().
 {
     gpio_init(led_info, sizeof(led_info)/sizeof(gpio_init_t));
 }
void led_set (int num, int value)
#include <led.c>
Turn ON/OFF LED based on input Value.
Parameters
[in] num Input from LED table translate to GPIO Pin.
[in] Value Value = 1 => LED ON, Value = 0 => LED OFF
Definition at line 81 of file led.c.
Referenced by test_start(), and test_stop().
 {
     if (value)
         GPIO_PinOutSet(led_info[num].port, led_info[num].pin);
     else
         GPIO_PinOutClear(led_info[num].port, led_info[num].pin);
 }
Variable Documentation
const gpio_init_t led_info[] static
#include <led.c>
Initial value:
=
{
    {  gpioPortE ,  2 , gpioModePushPull, 0 },
    {  gpioPortE ,  3 , gpioModePushPull, 0 }
}
Definition at line 55 of file led.c.