Adesto Flash Demo: GPIO
GPIO
Peripheral_Functions
STK Push-button definitions and function handlers for PB0/PB1.
.
Data Structures
struct gpio_init_t
Macros
#define MAX_PIN 16
Typedefs
typedef void gpio_callback_t (void *ref)
Functions
void gpio_init (const gpio_init_t *table, unsigned int count)
GPIO Initialization.
void GPIO_EVEN_IRQHandler (void)
Even Numbered GPIO Interrupt Handler.
void GPIO_ODD_IRQHandler (void)
Odd Numbered GPIO Interrupt Handler.
void gpio_irq_init (void)
GPIO Interrupt Initialize EVEN and ODD.
void gpio_irq_handler_install (GPIO_Port_TypeDef port, unsigned int pin, gpio_callback_t *callback, void *ref)
GPIO Interrupt Callback Configuration.
void gpio_irq_handler_remove (GPIO_Port_TypeDef port, unsigned int pin)
Remove GPIO Interrupt Handler.
Variables
static gpio_callback_t * gpio_callback [16]
static void * gpio_callback_ref [16]
Detailed Description
STK Push-button definitions and function handlers for PB0/PB1.
.
Function Documentation
void gpio_init (const gpio_init_t * table, unsigned int count)
#include <gpio.c>
GPIO Initialization.
Parameters
[in] *table Pointer to GPIO table.
[in] count Number of GPIO to initialize
Definition at line 65 of file gpio.c.
Referenced by button_init(), led_init(), low_power_init(), serial_init(), and spi_init().
 {
     while(count--)
     {
         GPIO_PinModeSet(table->port, table->pin, table->mode, table->out);
         table++;
     }
 }
void GPIO_EVEN_IRQHandler (void)
#include <gpio.c>
Even Numbered GPIO Interrupt Handler.
Definition at line 83 of file gpio.c.
 {
     int pin;
     uint32_t int_flags = GPIO_IntGet();
     for (pin = 0; pin < MAX_PIN; pin += 2)
         if (int_flags & (1 << pin))
         {
             GPIO_IntClear(1 << pin);
             gpio_callback[pin](gpio_callback_ref[pin]);
         }
 }
void GPIO_ODD_IRQHandler (void)
#include <gpio.c>
Odd Numbered GPIO Interrupt Handler.
Definition at line 101 of file gpio.c.
 {
     int pin;
     uint32_t int_flags = GPIO_IntGet();
     for (pin = 1; pin < MAX_PIN; pin += 2)
         if (int_flags & (1 << pin))
         {
             GPIO_IntClear(1 << pin);
             gpio_callback[pin](gpio_callback_ref[pin]);
         }
 }
void gpio_irq_init (void)
#include <gpio.c>
GPIO Interrupt Initialize EVEN and ODD.
Note
Call gpio_irq_init() before installing any interrupt handlers using gpio_irq_handler_install().
Definition at line 121 of file gpio.c.
Referenced by main().
 {
     memset(gpio_callback, 0, sizeof(gpio_callback));
     NVIC_ClearPendingIRQ(GPIO_EVEN_IRQn);
     NVIC_EnableIRQ(GPIO_EVEN_IRQn);
     NVIC_ClearPendingIRQ(GPIO_ODD_IRQn);
     NVIC_EnableIRQ(GPIO_ODD_IRQn);
 }
void gpio_irq_handler_install (GPIO_Port_TypeDef port, unsigned int pin, gpio_callback_t * callback, void * ref)
#include <gpio.c>
GPIO Interrupt Callback Configuration.
Note
gpio_irq_handler_install() presently will not support interrupt handlers for multiple pins with the same number, i.e., PB7 and PE7. gpio_irq_install() does not actually enable the interrupt; to enable, call e.g. GPIO_IntConfig(port, pin, risingEdge, fallingEdge, enable);
Parameters
[in] port Port Definition
[in] pin Pin Number
[in] *callback Pointer to callback function
[in] *ref Referring Function
Definition at line 152 of file gpio.c.
Referenced by button_init(), and spi_init().
 {
     gpio_callback[pin] = callback;
     gpio_callback_ref[pin] = ref;
 }
void gpio_irq_handler_remove (GPIO_Port_TypeDef port, unsigned int pin)
#include <gpio.c>
Remove GPIO Interrupt Handler.
Parameters
[in] port Port Definition
[in] pin Pin Number
Definition at line 170 of file gpio.c.
 {
     gpio_callback[pin] = NULL;
 }