Adesto Flash Demo: Serial_Demo_Functions
Serial_Demo_Functions
Serial_Demo
Functions for Serial Output Demo.
.
Functions
void read_id (void)
read and print flash ID
bool all_ones (uint8_t *buf, size_t len)
Create a buffer of all 1's.
void get_status (void)
Read Status Register of Device, Clear UART Tx Buffer.
void write_enable (void)
Set WRITE ENABLE, Clear UART Tx Buffer, Get Status.
void demo_serial (void)
Serial Output Demo, Prints out Data Wrote and Read back from Device.
Variables
static uint8_t raw_serial_rx_buf [200]
static uint8_t raw_serial_tx_buf [1000]
Detailed Description
Functions for Serial Output Demo.
.
Function Documentation
void read_id (void)
#include <demo_serial.c>
read and print flash ID
Definition at line 60 of file demo_serial.c.
References hex_dump(), and spiflash_read_id().
 {
   uint8_t id[4];
   spiflash_read_id(sizeof(id),
                    id,
                    NULL,
                    NULL);
   printf("ID:");
   hex_dump(id, sizeof(id), 0);
   printf("\r\n");
 }
bool all_ones (uint8_t * buf, size_t len)
#include <demo_serial.c>
Create a buffer of all 1's.
Parameters
[in] *buf Pointer to buffer.
[in] len Size of Buffer
Returns
true if successful
Definition at line 83 of file demo_serial.c.
 {
   size_t i;
   for (i = 0; i < len; i++)
       if (buf[i] != 0xff)
           return false;
   return true;
 }
void get_status (void)
#include <demo_serial.c>
Read Status Register of Device, Clear UART Tx Buffer.
Definition at line 97 of file demo_serial.c.
References serial_tx_flush(), and spiflash_read_status().
Referenced by demo_serial(), and write_enable().
 {
   uint8_t status[2];
   spiflash_read_status(2, status, NULL, NULL);
   printf("status = %02x %02x\r\n", status[0], status[1]);
   serial_tx_flush();
 }
void write_enable (void)
#include <demo_serial.c>
Set WRITE ENABLE, Clear UART Tx Buffer, Get Status.
Definition at line 111 of file demo_serial.c.
References get_status(), serial_tx_flush(), and spiflash_set_write_enable().
Referenced by demo_serial().
 {
   printf("setting write enable\r\n");
   serial_tx_flush();
   spiflash_set_write_enable(true, NULL, NULL);
   printf("write enabled\r\n");
   serial_tx_flush();
   get_status();
 }
void demo_serial (void)
#include <demo_serial.c>
Serial Output Demo, Prints out Data Wrote and Read back from Device.
Definition at line 140 of file demo_serial.c.
References get_status(), hex_dump(), raw_serial_rx_buf, serial_close(), serial_init(), serial_tx_flush(), spiflash_erase(), spiflash_init(), spiflash_read(), spiflash_set_sector_protection(), spiflash_ultra_deep_power_down(), spiflash_write(), and write_enable().
Referenced by run_serial().
 {
     int i;
     int hex_dump_size = 256;
     CMU_ClockEnable(cmuClock_CORELE, true);
     CMU_ClockSelectSet(cmuClock_LFA, cmuSelect_LFXO);
     CMU_ClockSelectSet(cmuClock_LFB, cmuSelect_LFXO);
     serial_init(9600,
                 raw_serial_rx_buf, sizeof(raw_serial_rx_buf),
                 raw_serial_tx_buf, sizeof(raw_serial_tx_buf));
     printf("\r\nEmbedded Masters SPI Flash Demo\r\n");
     if (! spiflash_init(2000000))
       {
         printf("SPI flash failed to initialize\r\n");
         while(true)
             ;
       }
     get_status();
     printf("reading\r\n");
     spiflash_read(0x00000, sizeof(buf1), buf1, NULL, NULL);
     printf("read done\r\n");
     serial_tx_flush();
     printf("data read");
     if (hex_dump_size != sizeof(buf1))
         printf(", first %d bytes", hex_dump_size);
     printf (":\r\n");
     hex_dump(buf1, hex_dump_size, 0);
     serial_tx_flush();
     printf("erasing\r\n");
     spiflash_erase(0x00000, sizeof(buf1), 0, true, NULL, NULL);
     printf("erase done\r\n");
     serial_tx_flush();
     get_status();
     printf("setting buffer to increment from %02x\r\n", buf1[0]+1);
     buf2[0]++;
     for (i = 1; i < sizeof(buf2); i++)
         buf2[i] = buf2[i-1] + 1;
     serial_tx_flush();
     write_enable();
     printf("setting sector unprotect\r\n");
     spiflash_set_sector_protection(false, 0x00000, NULL, NULL);
     get_status();
     printf("writing\r\n");
     serial_tx_flush();
     spiflash_write(0x00000, sizeof(buf2), buf2, true, NULL, NULL);
     printf("write done\r\n");
     serial_tx_flush();
     get_status();
     printf("reading\r\n");
     serial_tx_flush();
     spiflash_read(0x00000, sizeof(buf3), buf3, NULL, NULL);
     printf("read done\r\n");
     serial_tx_flush();
     printf("data read");
     if (hex_dump_size != sizeof(buf1))
         printf(", first %d bytes", hex_dump_size);
     printf (":\r\n");
     serial_tx_flush();
     hex_dump(buf3, hex_dump_size, 0);
     spiflash_ultra_deep_power_down(true, NULL, NULL);
     serial_tx_flush();
     serial_close();
 }
Variable Documentation
uint8_t raw_serial_rx_buf[200] static
#include <demo_serial.c>
Note
These serial I/O buffers should never be accessed directly, but only through the buffer.h API. They are circular buffers, and part of the allocation is carved out for buffer control.
Definition at line 130 of file demo_serial.c.
Referenced by demo_serial().