Adesto Flash Demo: Low_Power
Low_Power
Peripheral_Functions
Macros
#define EM1_DEBUG_PORT gpioPortD
#define EM1_DEBUG_PIN 5
#define EM2_DEBUG_PORT gpioPortD
#define EM2_DEBUG_PIN 6
Functions
void set_force_em0 (bool val)
Force to EM0/Run Mode.
void enter_low_power_state (void)
Decides whether to put EFM into EM0, EM1, or EM2 based on Activity.
void low_power_init (void)
Initialize Low Power Modes.
Variables
static bool force_em0
volatile uint32_t wait_em1_count
volatile uint32_t wait_em2_count
static const gpio_init_t lp_debug_pins []
Detailed Description
Function Documentation
void set_force_em0 (bool val)
#include <low_power.c>
Force to EM0/Run Mode.
Parameters
[in] val 1 Sets to EM0 0 Clears forcing to EM0.
Definition at line 72 of file low_power.c.
 {
     force_em0 = val;
 }
void enter_low_power_state (void)
#include <low_power.c>
Decides whether to put EFM into EM0, EM1, or EM2 based on Activity.
Definition at line 82 of file low_power.c.
References spi_active().
Referenced by button1_default(), dataflash_rmw(), spi_wait_so(), spiflash_command_with_address(), spiflash_erase(), spiflash_multiple_byte_command(), spiflash_single_byte_command(), and spiflash_write().
 {
     if (force_em0)
         __ASM volatile ("wfi");
     else if (spi_active())
     {
         wait_em1_count++;
         GPIO_PinOutSet(EM1_DEBUG_PORT, EM1_DEBUG_PIN);
         EMU_EnterEM1();
         GPIO_PinOutClear(EM1_DEBUG_PORT, EM1_DEBUG_PIN);
     }
     else
     {
         wait_em2_count++;
         GPIO_PinOutSet(EM2_DEBUG_PORT, EM2_DEBUG_PIN);
         EMU_EnterEM2(true);
         GPIO_PinOutClear(EM2_DEBUG_PORT, EM2_DEBUG_PIN);
     }
 }
void low_power_init (void)
#include <low_power.c>
Initialize Low Power Modes.
Definition at line 113 of file low_power.c.
References gpio_init().
Referenced by main().
 {
     force_em0 = 0;
     wait_em1_count = 0;
     wait_em2_count = 0;
     gpio_init(lp_debug_pins, sizeof(lp_debug_pins)/sizeof(gpio_init_t));
 }
Variable Documentation
const gpio_init_t lp_debug_pins[] static
#include <low_power.c>
Initial value:
=
{
  {  gpioPortD ,  5 , gpioModePushPull,  0 },
  {  gpioPortD ,  6 , gpioModePushPull,  0 },
}
Definition at line 102 of file low_power.c.