Adesto Flash Demo: Flash Drivers
Flash Drivers
Macros
#define LED_DEBUG
#define CMD_READ_ARRAY 0x0b
#define CMD_READ_ARRAY_SLOW 0x03 /* no dummy byte, but limited to lower clock rate */
#define CMD_READ_ARRAY_DUAL 0x3b /* not used, as we don't have dual-SPI hardware */
#define CMD_PAGE_ERASE 0x81
#define CMD_RM25C_PAGE_ERASE 0x42 /* RM26C256DS only */
#define CMD_BLOCK_ERASE 0x20
#define CMD_BLOCK_ERASE_LARGE 0x52
#define CMD_BLOCK_ERASE_LARGER 0xd8
#define CMD_CHIP_ERASE 0x60
#define CMD_CHIP_ERASE2 0xc7 /* not used, exactly the same as CMD_CHIP_ERASE */
#define CMD_BYTE_PAGE_PROGRAM 0x02
#define CMD_SEQUENTIAL_PROGRAM 0xad /* not used, page program is more efficient */
#define CMD_SEQUENTIAL_PROGRAM2 0xaf /* not used, page program is more efficient */
#define CMD_BYTE_PAGE_PROGRAM_DUAL 0xa2 /* not used, as we don't have dual-SPI hardware */
#define CMD_WRITE_ENABLE 0x06
#define CMD_WRITE_DISABLE 0x04
#define CMD_PROTECT_SECTOR 0x36
#define CMD_UNPROTECT_SECTOR 0x39
#define CMD_READ_SECTOR_PROTECTION 0x3c
#define CMD_PROGRAM_OTP 0x9b
#define CMD_READ_OTP 0x77
#define CMD_READ_STATUS 0x05
#define CMD_DATAFLASH_READ_STATUS 0xd7
#define CMD_ACTIVE_STATUS_INTERRUPT 0x25
#define CMD_WRITE_STATUS_REG_BYTE_1 0x01
#define CMD_WRITE_STATUS_REG_BYTE_2 0x31
#define CMD_RESET 0xf0
#define CMD_READ_ID 0x9f
#define CMD_DEEP_POWER_DOWN 0xb9
#define CMD_RESUME_FROM_DEEP_POWER_DOWN 0xab
#define CMD_ULTRA_DEEP_POWER_DOWN 0x79
#define ARG_RESET 0xd0 /* second byte required for reset command */
#define CMD_DATAFLASH_BLOCK_ERASE 0x50 /* 8 pages, 2KB */
#define CMD_DATAFLASH_SECTOR_ERASE 0x7c
#define CMD_DATAFLASH_RMW_BUF1 0x58
#define CMD_DATAFLASH_RMW_BUF2 0x59
#define SPIFLASH_INFO_TABLE_SIZE (sizeof(spiflash_info_table) / sizeof(spiflash_info_t))
Functions
static bool addr_aligned (uint32_t addr, size_t alignment_size)
static void spiflash_spi_simple_completion (void *ref)
void spiflash_single_byte_command (uint8_t cmd, size_t rx_len, uint8_t *rx_buf, spiflash_completion_fn_t *completion, void *completion_ref)
void spiflash_multiple_byte_command (size_t tx_len, const uint8_t *tx_buf, size_t rx_len, uint8_t *rx_buf, bool hold_cs_active, spiflash_completion_fn_t *completion, void *completion_ref)
void spiflash_command_with_address (uint8_t cmd, uint32_t addr, unsigned int dummy_bytes, size_t tx_len, uint8_t *tx_buf, size_t rx_len, uint8_t *rx_buf, spiflash_completion_fn_t *completion, void *completion_ref)
void spiflash_read (uint32_t addr, size_t len, uint8_t *buffer, spiflash_completion_fn_t *completion, void *completion_ref)
static void spiflash_erase_completion1 (void *ref)
static void spiflash_erase_completion2 (void *ref)
static void spiflash_erase_completion3 (void *ref)
static void spiflash_erase_completion4 (void *ref)
static void spiflash_erase_completion5 (void *ref)
bool spiflash_erase (uint32_t addr, size_t len, uint32_t cmd_size, bool use_so_irq, spiflash_completion_fn_t *completion, void *completion_ref)
static void spiflash_write_completion1 (void *ref)
static void spiflash_write_completion2 (void *ref)
static void spiflash_write_completion3 (void *ref)
static void spiflash_write_completion4 (void *ref)
static void spiflash_write_completion5 (void *ref)
void spiflash_write (uint32_t addr, size_t len, uint8_t *buffer, bool use_so_irq, spiflash_completion_fn_t *completion, void *completion_ref)
static void dataflash_rmw_completion1 (void *ref)
static void dataflash_rmw_completion2 (void *ref)
static void dataflash_rmw_completion3 (void *ref)
void dataflash_rmw (uint32_t addr, size_t len, uint8_t *buffer, spiflash_completion_fn_t *completion, void *completion_ref)
void spiflash_set_write_enable (bool enable, spiflash_completion_fn_t *completion, void *completion_ref)
void spiflash_set_sector_protection (bool protect, uint32_t addr, spiflash_completion_fn_t *completion, void *completion_ref)
void spiflash_set_global_protect (bool protect, spiflash_completion_fn_t *completion, void *completion_ref)
void spiflash_read_status (size_t len, uint8_t *buffer, spiflash_completion_fn_t *completion, void *completion_ref)
void spiflash_write_status (uint8_t data, spiflash_completion_fn_t *completion, void *completion_ref)
void spiflash_write_status2 (uint8_t data, spiflash_completion_fn_t *completion, void *completion_ref)
void spiflash_read_id (size_t len, uint8_t *buffer, spiflash_completion_fn_t *completion, void *completion_ref)
void spiflash_deep_power_down (bool power_down, spiflash_completion_fn_t *completion, void *completion_ref)
void spiflash_ultra_deep_power_down (bool power_down, spiflash_completion_fn_t *completion, void *completion_ref)
bool spiflash_is_dataflash (void)
uint32_t dataflash_get_page_size (void)
bool dataflash_set_page_size (uint32_t page_size)
spiflash_id_t spiflash_init (int bit_rate)
uint32_t spiflash_smallest_erase_size_above (uint32_t size)
Variables
int i
int cycle_count = 0
static const uint8_t at25xe021a_id_bytes [] = { 0x1f, 0x43, 0x01, 0x00 }
static const size_t at25xe021a_protection_sector_sizes [] = { 65536, 65536, 65536, 65536 }
static const uint8_t at25xe041b_id_bytes [] = { 0x1f, 0x44, 0x02, 0x00 }
static const size_t at25xe041b_protection_sector_sizes [] = { 65536, 65536, 65536, 65536, 65536, 65536, 65536, 32768, 8192, 8192, 16384 }
static const uint8_t dataflash_cmd_set_256b_page [] = { 0x3d, 0x2a, 0x80, 0xa6 }
static const uint8_t dataflash_cmd_set_264b_page [] = { 0x3d, 0x2a, 0x80, 0xa7 }
static const uint8_t dataflash_cmd_chip_erase [] = { 0xc7, 0x94, 0x80, 0x9a }
static const uint8_t dataflash_cmd_disable_sector_protection [] = { 0x3d, 0x2a, 0x7f, 0x9a }
const spiflash_info_t spiflash_info_table []
static const spiflash_info_t * spiflash_info
static bool spiflash_use_so_irq
static bool spiflash_busy
static spiflash_completion_fn_t * spiflash_completion
static void * spiflash_completion_ref
static uint8_t spiflash_scratch_buf [257]
static const erase_info_t * erase_info_fixed
static const erase_info_t * erase_info
static uint32_t erase_addr
static size_t erase_len
static uint8_t erase_status_buf [2]
static volatile bool spiflash_erase_busy
static uint8_t * write_data
static uint32_t write_addr
static size_t write_len
static size_t write_size
static uint8_t write_status_buf [2]
static volatile bool spiflash_write_busy
Detailed Description
Macro Definition Documentation
#define LED_DEBUG
#include <spiflash.c>
Definition at line 54 of file spiflash.c.
#define CMD_READ_ARRAY 0x0b
#include <spiflash.c>
Definition at line 63 of file spiflash.c.
Referenced by spiflash_read().
#define CMD_READ_ARRAY_SLOW 0x03 /* no dummy byte, but limited to lower clock rate */
#include <spiflash.c>
Definition at line 64 of file spiflash.c.
Referenced by spiflash_read().
#define CMD_READ_ARRAY_DUAL 0x3b /* not used, as we don't have dual-SPI hardware */
#include <spiflash.c>
Definition at line 65 of file spiflash.c.
#define CMD_PAGE_ERASE 0x81
#include <spiflash.c>
Definition at line 66 of file spiflash.c.
#define CMD_RM25C_PAGE_ERASE 0x42 /* RM26C256DS only */
#include <spiflash.c>
Definition at line 67 of file spiflash.c.
#define CMD_BLOCK_ERASE 0x20
#include <spiflash.c>
Definition at line 68 of file spiflash.c.
#define CMD_BLOCK_ERASE_LARGE 0x52
#include <spiflash.c>
Definition at line 69 of file spiflash.c.
#define CMD_BLOCK_ERASE_LARGER 0xd8
#include <spiflash.c>
Definition at line 70 of file spiflash.c.
#define CMD_CHIP_ERASE 0x60
#include <spiflash.c>
Definition at line 71 of file spiflash.c.
#define CMD_CHIP_ERASE2 0xc7 /* not used, exactly the same as CMD_CHIP_ERASE */
#include <spiflash.c>
Definition at line 72 of file spiflash.c.
#define CMD_BYTE_PAGE_PROGRAM 0x02
#include <spiflash.c>
Definition at line 73 of file spiflash.c.
Referenced by spiflash_write_completion2().
#define CMD_SEQUENTIAL_PROGRAM 0xad /* not used, page program is more efficient */
#include <spiflash.c>
Definition at line 74 of file spiflash.c.
#define CMD_SEQUENTIAL_PROGRAM2 0xaf /* not used, page program is more efficient */
#include <spiflash.c>
Definition at line 75 of file spiflash.c.
#define CMD_BYTE_PAGE_PROGRAM_DUAL 0xa2 /* not used, as we don't have dual-SPI hardware */
#include <spiflash.c>
Definition at line 76 of file spiflash.c.
#define CMD_WRITE_ENABLE 0x06
#include <spiflash.c>
Definition at line 77 of file spiflash.c.
Referenced by spiflash_erase_completion1(), spiflash_set_write_enable(), and spiflash_write_completion1().
#define CMD_WRITE_DISABLE 0x04
#include <spiflash.c>
Definition at line 78 of file spiflash.c.
Referenced by spiflash_set_write_enable().
#define CMD_PROTECT_SECTOR 0x36
#include <spiflash.c>
Definition at line 79 of file spiflash.c.
Referenced by spiflash_set_sector_protection().
#define CMD_UNPROTECT_SECTOR 0x39
#include <spiflash.c>
Definition at line 80 of file spiflash.c.
Referenced by spiflash_set_sector_protection().
#define CMD_READ_SECTOR_PROTECTION 0x3c
#include <spiflash.c>
Definition at line 81 of file spiflash.c.
#define CMD_PROGRAM_OTP 0x9b
#include <spiflash.c>
Definition at line 82 of file spiflash.c.
#define CMD_READ_OTP 0x77
#include <spiflash.c>
Definition at line 83 of file spiflash.c.
#define CMD_READ_STATUS 0x05
#include <spiflash.c>
Definition at line 84 of file spiflash.c.
#define CMD_DATAFLASH_READ_STATUS 0xd7
#include <spiflash.c>
Definition at line 85 of file spiflash.c.
#define CMD_ACTIVE_STATUS_INTERRUPT 0x25
#include <spiflash.c>
Definition at line 86 of file spiflash.c.
Referenced by spiflash_erase_completion3(), and spiflash_write_completion3().
#define CMD_WRITE_STATUS_REG_BYTE_1 0x01
#include <spiflash.c>
Definition at line 87 of file spiflash.c.
Referenced by spiflash_set_global_protect().
#define CMD_WRITE_STATUS_REG_BYTE_2 0x31
#include <spiflash.c>
Definition at line 88 of file spiflash.c.
#define CMD_RESET 0xf0
#include <spiflash.c>
Definition at line 89 of file spiflash.c.
#define CMD_READ_ID 0x9f
#include <spiflash.c>
Definition at line 90 of file spiflash.c.
Referenced by spiflash_read_id().
#define CMD_DEEP_POWER_DOWN 0xb9
#include <spiflash.c>
Definition at line 91 of file spiflash.c.
Referenced by spiflash_deep_power_down().
#define CMD_RESUME_FROM_DEEP_POWER_DOWN 0xab
#include <spiflash.c>
Definition at line 92 of file spiflash.c.
Referenced by spiflash_deep_power_down(), and spiflash_ultra_deep_power_down().
#define CMD_ULTRA_DEEP_POWER_DOWN 0x79
#include <spiflash.c>
Definition at line 93 of file spiflash.c.
Referenced by spiflash_ultra_deep_power_down().
#define ARG_RESET 0xd0 /* second byte required for reset command */
#include <spiflash.c>
Definition at line 95 of file spiflash.c.
#define CMD_DATAFLASH_BLOCK_ERASE 0x50 /* 8 pages, 2KB */
#include <spiflash.c>
Definition at line 98 of file spiflash.c.
#define CMD_DATAFLASH_SECTOR_ERASE 0x7c
#include <spiflash.c>
Definition at line 99 of file spiflash.c.
#define CMD_DATAFLASH_RMW_BUF1 0x58
#include <spiflash.c>
Definition at line 101 of file spiflash.c.
Referenced by dataflash_rmw_completion1().
#define CMD_DATAFLASH_RMW_BUF2 0x59
#include <spiflash.c>
Definition at line 102 of file spiflash.c.
#define SPIFLASH_INFO_TABLE_SIZE (sizeof(spiflash_info_table) / sizeof(spiflash_info_t))
#include <spiflash.c>
Definition at line 249 of file spiflash.c.
Referenced by spiflash_init().
Function Documentation
static bool addr_aligned (uint32_t addr, size_t alignment_size) static
#include <spiflash.c>
Definition at line 264 of file spiflash.c.
Referenced by spiflash_erase(), and spiflash_erase_completion2().
 {
     return (addr & (alignment_size-1)) == 0;
 }
static void spiflash_spi_simple_completion (void * ref) static
#include <spiflash.c>
Definition at line 270 of file spiflash.c.
References spiflash_completion, and spiflash_completion_ref.
Referenced by dataflash_rmw_completion3(), spiflash_command_with_address(), spiflash_erase_completion1(), spiflash_multiple_byte_command(), spiflash_single_byte_command(), and spiflash_write_completion1().
 {
     (void) ref;
     // copy completion fn ptr and ref arg, to avoid race condition
     // if completion fn starts another spiflash command
     spiflash_completion_fn_t *completion = spiflash_completion;
     void *spiflash_ref = spiflash_completion_ref;
     spiflash_completion = NULL;
     spiflash_busy = false;
     if (completion)
         completion(spiflash_ref);
 }
void spiflash_single_byte_command (uint8_t cmd, size_t rx_len, uint8_t * rx_buf, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 286 of file spiflash.c.
References enter_low_power_state(), spi_xfer(), and spiflash_spi_simple_completion().
Referenced by dataflash_rmw_completion3(), spiflash_deep_power_down(), spiflash_erase_completion1(), spiflash_erase_completion2(), spiflash_erase_completion5(), spiflash_read_id(), spiflash_read_status(), spiflash_set_write_enable(), spiflash_ultra_deep_power_down(), spiflash_write_completion1(), and spiflash_write_completion5().
 {
     spiflash_scratch_buf[0] = cmd;
     spiflash_completion = completion;
     spiflash_completion_ref = completion_ref;
     spiflash_busy = true;
     spi_xfer(1, spiflash_scratch_buf,  // tx1
              0, NULL,                  // tx2
              true,                     // half duplex
              rx_len, rx_buf,           // rx
              false,                    // hold cs active
              spiflash_spi_simple_completion,
              NULL);
     if (! completion)
         while (spiflash_busy)
             enter_low_power_state();
 }
void spiflash_multiple_byte_command (size_t tx_len, const uint8_t * tx_buf, size_t rx_len, uint8_t * rx_buf, bool hold_cs_active, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 313 of file spiflash.c.
References enter_low_power_state(), spi_xfer(), and spiflash_spi_simple_completion().
Referenced by dataflash_rmw(), dataflash_set_page_size(), spiflash_erase(), spiflash_erase_completion2(), spiflash_erase_completion3(), spiflash_set_global_protect(), spiflash_write(), and spiflash_write_completion3().
 {
     spiflash_completion = completion;
     spiflash_completion_ref = completion_ref;
     spiflash_busy = true;
     spi_xfer(tx_len, tx_buf,  // tx1
              0, NULL,         // tx2
              true,            // half duplex
              rx_len, rx_buf,  // rx
              hold_cs_active,  // hold cs active
              spiflash_spi_simple_completion,
              NULL);
     if (! completion)
         while (spiflash_busy)
             enter_low_power_state();
 }
void spiflash_command_with_address (uint8_t cmd, uint32_t addr, unsigned int dummy_bytes, size_t tx_len, uint8_t * tx_buf, size_t rx_len, uint8_t * rx_buf, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 340 of file spiflash.c.
References spiflash_info_t::address_bytes, enter_low_power_state(), i, spi_xfer(), and spiflash_spi_simple_completion().
Referenced by dataflash_rmw_completion1(), spiflash_erase_completion2(), spiflash_read(), spiflash_set_sector_protection(), and spiflash_write_completion2().
 {
     int i = 0;
     spiflash_scratch_buf[i++] = cmd;
     if (spiflash_info->address_bytes >= 3)
         spiflash_scratch_buf[i++] = addr >> 16;
     if (spiflash_info->address_bytes >= 2)
         spiflash_scratch_buf[i++] = (addr >> 8) & 0xff;
     if (spiflash_info->address_bytes >= 1)
         spiflash_scratch_buf[i++] = addr & 0xff;
     memset(&spiflash_scratch_buf[i], 0, dummy_bytes);
     i += dummy_bytes;
     spiflash_completion = completion;
     spiflash_completion_ref = completion_ref;
     spiflash_busy = true;
     spi_xfer(i, spiflash_scratch_buf,  // tx1
              tx_len, tx_buf,                         // tx2
              true,                                   // half duplex
              rx_len, rx_buf,
              false,                    // hold cs active
              spiflash_spi_simple_completion,
              NULL);
     if (! completion)
         while (spiflash_busy)
             enter_low_power_state();
 }
void spiflash_read (uint32_t addr, size_t len, uint8_t * buffer, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 381 of file spiflash.c.
References CMD_READ_ARRAY, CMD_READ_ARRAY_SLOW, spiflash_info_t::read_slow, and spiflash_command_with_address().
Referenced by appl_read(), demo_serial(), run_read(), and run_rmw_normal().
 {
     uint8_t cmd;
     int dummy_bytes;
     if (spiflash_info->read_slow)
     {
         cmd = CMD_READ_ARRAY_SLOW;
         dummy_bytes = 0;
     }
     else
     {
         cmd = CMD_READ_ARRAY;
         dummy_bytes = 1;
     }
     spiflash_command_with_address(cmd,
                                   addr,
                                   dummy_bytes,
                                   0, NULL,      // tx
                                   len, buffer,  // rx
                                   completion,
                                   completion_ref);
 }
static void spiflash_erase_completion1 (void * ref) static
#include <spiflash.c>
Definition at line 426 of file spiflash.c.
References CMD_WRITE_ENABLE, spiflash_info_t::dataflash, spiflash_erase_completion2(), spiflash_single_byte_command(), and spiflash_spi_simple_completion().
Referenced by spiflash_erase(), spiflash_erase_completion4(), and spiflash_erase_completion5().
 {
     if (! erase_len)
     {
         spiflash_erase_busy = false;
         spiflash_spi_simple_completion(ref);
         return;
     }
     if (spiflash_info->dataflash)
         spiflash_erase_completion2(NULL);
     else
         spiflash_single_byte_command(CMD_WRITE_ENABLE,
                                      0, NULL,  // rx
                                      spiflash_erase_completion2,
                                      NULL);
 }
static void spiflash_erase_completion2 (void * ref) static
#include <spiflash.c>
Definition at line 445 of file spiflash.c.
References addr_aligned(), erase_info_t::addr_needed, erase_info_t::cmd, spiflash_info_t::dataflash, dataflash_cmd_chip_erase, spiflash_info_t::erase_info, spiflash_info_t::erase_info_count, erase_info_fixed, i, erase_info_t::size, spiflash_command_with_address(), spiflash_erase_completion3(), spiflash_multiple_byte_command(), and spiflash_single_byte_command().
Referenced by spiflash_erase_completion1().
 {
     int i;
     if (erase_info_fixed)
         erase_info = erase_info_fixed;
     else
     {
         for (i = spiflash_info->erase_info_count - 1; i >= 0; i--)
         {
             erase_info = & spiflash_info->erase_info [i];
             if ((erase_len >= erase_info->size) &&
                 addr_aligned(erase_addr, erase_info->size))
                 break;
         }
         if (i < 0)
         {
             // no suitable erase command found!
             // should never happen
             erase_info = NULL;
             while (true)
                 ;
         }
     }
     if (erase_info->addr_needed)
     {
         spiflash_command_with_address(erase_info->cmd,
                                       erase_addr,
                                       0,        // dummy bytes
                                       0, NULL,  // tx
                                       0, NULL,  // rx
                                       spiflash_erase_completion3,
                                       NULL);
     }
     else if (spiflash_info->dataflash)
     {
         // chip erase for dataflash doesn't need an address, but is a multibyte command
         spiflash_multiple_byte_command(sizeof(dataflash_cmd_chip_erase), dataflash_cmd_chip_erase,
                                        0, NULL, // rx
                                        false, // hold_cs_active
                                        spiflash_erase_completion3,
                                        NULL);
     }
     else
     {
         // chip erase doesn't need an address
         spiflash_single_byte_command(erase_info->cmd,
                                      0, NULL,  // rx
                                      spiflash_erase_completion3,
                                      NULL);
     }
 }
static void spiflash_erase_completion3 (void * ref) static
#include <spiflash.c>
Definition at line 499 of file spiflash.c.
References CMD_ACTIVE_STATUS_INTERRUPT, erase_info_t::size, spiflash_erase_completion4(), spiflash_erase_completion5(), spiflash_multiple_byte_command(), and spiflash_info_t::status_busy_level.
Referenced by spiflash_erase_completion2().
 {
     // Erase is in progress, but advance the address
     // and decrease the length in preparation for next
     // iteration.  If erase_len drops to zero, that will
     // be handled when we get to
     // spiflash_erase_completion1().
     erase_addr += erase_info->size;
     erase_len -= erase_info->size;
     if (spiflash_use_so_irq)
     {
         // use of SO is enabled, so issue ASI command
         spiflash_scratch_buf[0] = CMD_ACTIVE_STATUS_INTERRUPT;
         spiflash_scratch_buf[1] = 0x00;
         spiflash_multiple_byte_command(1, spiflash_scratch_buf,  // tx
                                        0, NULL,                  // rx
                                        true,                     // hold CS active
                                        spiflash_erase_completion4,
                                        NULL);
     }
     else
     {
         // use of SO is disabled, so start polling status register
         erase_status_buf[0] = spiflash_info->status_busy_level;  // prime pump w/ BUSY
         spiflash_erase_completion5(NULL);
     }
 }
static void spiflash_erase_completion4 (void * ref) static
#include <spiflash.c>
Definition at line 531 of file spiflash.c.
References spiflash_info_t::so_done_level, spi_wait_so(), and spiflash_erase_completion1().
Referenced by spiflash_erase_completion3().
 {
     // wait for flash chip to be done with command,
     // then invoke completion1()
     spi_wait_so(spiflash_info->so_done_level,
                     spiflash_erase_completion1,
                     NULL);
 }
static void spiflash_erase_completion5 (void * ref) static
#include <spiflash.c>
Definition at line 542 of file spiflash.c.
References spiflash_info_t::read_status_cmd, spiflash_erase_completion1(), spiflash_single_byte_command(), spiflash_info_t::status_busy_level, and spiflash_info_t::status_busy_mask.
Referenced by spiflash_erase_completion3().
 {
     if ((erase_status_buf[0] & spiflash_info->status_busy_mask) == spiflash_info->status_busy_level)
     {
         // BUSY
         spiflash_single_byte_command(spiflash_info->read_status_cmd,
                                      1,
                                      erase_status_buf,
                                      spiflash_erase_completion5,
                                      NULL);
     }
     else
     {
         // DONE
         spiflash_erase_completion1(NULL);
     }
 }
bool spiflash_erase (uint32_t addr, size_t len, uint32_t cmd_size, bool use_so_irq, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 561 of file spiflash.c.
References addr_aligned(), spiflash_info_t::dataflash, dataflash_cmd_disable_sector_protection, enter_low_power_state(), spiflash_info_t::erase_info, spiflash_info_t::erase_info_count, spiflash_info_t::has_so_irq, i, erase_info_t::size, spiflash_erase_completion1(), and spiflash_multiple_byte_command().
Referenced by appl_erase(), demo_serial(), run_erase(), and run_rmw_normal().
 {
     int i;
     bool found = false;
     spiflash_use_so_irq = use_so_irq && spiflash_info->has_so_irq;
     if (cmd_size)
     {
         // The desired erase size per command was specified.
         // Find the matching erase command, and ensure the address is
         // suitably aligned and the erase size is a multiple of the
         // command size.
         if (len % cmd_size)
             return false;
         for (i = spiflash_info->erase_info_count - 1; i >= 0; i--)
         {
             erase_info_fixed = & spiflash_info->erase_info [i];
             if (cmd_size == erase_info_fixed->size)
             {
                 found = true;
                 break;
             }
         }
         if (! found)
         {
             erase_info_fixed = NULL;
             return false;
         }
     }
     else
     {
         // No erase size per command was specified.
         // Ensure that there is a suitable choice.
         for (i = spiflash_info->erase_info_count - 1; i >= 0; i--)
         {
             erase_info = & spiflash_info->erase_info [i];
             if (len % erase_info->size)
                 continue;
             if (! addr_aligned(addr, erase_info->size))
                 continue;
             found = true;
             break;
         }
         erase_info = NULL;  // will be chosen in spiflash_erase_completion2;
         if (! found)
             return false;
     }
     erase_addr = addr;
     erase_len = len;
     spiflash_completion = completion;
     spiflash_completion_ref = completion_ref;
     spiflash_erase_busy = true;
     if (spiflash_info->dataflash)
         spiflash_multiple_byte_command(sizeof(dataflash_cmd_disable_sector_protection), dataflash_cmd_disable_sector_protection,
                                        0, NULL, // rx
                                        false, // hold_cs_active
                                        spiflash_erase_completion1,
                                        NULL);
     else
         spiflash_erase_completion1(NULL);
     // if called synchronously, wait for entire write sequence to complete
     if (! completion)
     {
         while (spiflash_erase_busy)
         {
             enter_low_power_state();
         }
     }
     return true;
 }
static void spiflash_write_completion1 (void * ref) static
#include <spiflash.c>
Definition at line 657 of file spiflash.c.
References CMD_WRITE_ENABLE, spiflash_info_t::dataflash, spiflash_single_byte_command(), spiflash_spi_simple_completion(), and spiflash_write_completion2().
Referenced by spiflash_write(), spiflash_write_completion4(), and spiflash_write_completion5().
 {
     if (! write_len)
     {
         spiflash_write_busy = false;
         spiflash_spi_simple_completion(ref);
         return;
     }
     if (spiflash_info->dataflash)
         spiflash_write_completion2(NULL);
     else
         spiflash_single_byte_command(CMD_WRITE_ENABLE,
                                      0, NULL,  // rx
                                      spiflash_write_completion2,
                                      NULL);
 }
static void spiflash_write_completion2 (void * ref) static
#include <spiflash.c>
Definition at line 676 of file spiflash.c.
References CMD_BYTE_PAGE_PROGRAM, spiflash_info_t::program_page_size, spiflash_command_with_address(), spiflash_write_completion3(), and write_len.
Referenced by spiflash_write_completion1().
 {
     write_size = write_len;
     if ((write_addr & ~(spiflash_info->program_page_size-1)) !=
         ((write_addr + write_size - 1) & ~(spiflash_info->program_page_size-1)))
         write_size = spiflash_info->program_page_size - (write_addr & (spiflash_info->program_page_size-1));
     spiflash_command_with_address(CMD_BYTE_PAGE_PROGRAM,
                                   write_addr,
                                   0, // dummy bytes
                                   write_size, write_data,  // tx
                                   0, NULL,                 // rx
                                   spiflash_write_completion3,
                                   NULL);
 }
static void spiflash_write_completion3 (void * ref) static
#include <spiflash.c>
Definition at line 693 of file spiflash.c.
References CMD_ACTIVE_STATUS_INTERRUPT, spiflash_multiple_byte_command(), spiflash_write_completion4(), spiflash_write_completion5(), spiflash_info_t::status_busy_level, and write_size.
Referenced by spiflash_write_completion2().
 {
     // Write is in progress, but advance the address
     // and decrease the length in preparation for next
     // iteration.  If write_len drops to zero, that will
     // be handled when we get to
     // spiflash_write_completion1().
     write_data += write_size;
     write_addr += write_size;
     write_len -= write_size;
     if (spiflash_use_so_irq == 1)
     {
         // use of SO is enabled, so issue ASI command
         spiflash_scratch_buf[0] = CMD_ACTIVE_STATUS_INTERRUPT;
         spiflash_scratch_buf[1] = 0x00;
         spiflash_multiple_byte_command(2, spiflash_scratch_buf,  // tx
                                        0, NULL,                  // rx
                                        true,                     // hold CS active
                                        spiflash_write_completion4,
                                        NULL);
     }
     else
     {
         // use of SO is disabled, so start polling status register
         write_status_buf[0] = spiflash_info->status_busy_level;  // prime pump w/ BUSY
         spiflash_write_completion5(NULL);
     }
 }
static void spiflash_write_completion4 (void * ref) static
#include <spiflash.c>
Definition at line 726 of file spiflash.c.
References spiflash_info_t::so_done_level, spi_wait_so(), and spiflash_write_completion1().
Referenced by spiflash_write_completion3().
 {
     // wait for flash chip to be done with command,
     // then invoke completion1
     spi_wait_so(spiflash_info->so_done_level,
                 spiflash_write_completion1,
                 NULL);
 }
static void spiflash_write_completion5 (void * ref) static
#include <spiflash.c>
Definition at line 737 of file spiflash.c.
References spiflash_info_t::read_status_cmd, spiflash_single_byte_command(), spiflash_write_completion1(), spiflash_info_t::status_busy_level, and spiflash_info_t::status_busy_mask.
Referenced by spiflash_write_completion3().
 {
     if ((write_status_buf[0] & spiflash_info->status_busy_mask) == spiflash_info->status_busy_level)
     {
         // BUSY
         spiflash_single_byte_command(spiflash_info->read_status_cmd,
                                      1,
                                      write_status_buf,
                                      spiflash_write_completion5,
                                      NULL);
     }
     else
     {
         // DONE
         spiflash_write_completion1(NULL);
     }
 }
void spiflash_write (uint32_t addr, size_t len, uint8_t * buffer, bool use_so_irq, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 756 of file spiflash.c.
References spiflash_info_t::dataflash, dataflash_cmd_disable_sector_protection, enter_low_power_state(), spiflash_info_t::has_so_irq, spiflash_multiple_byte_command(), and spiflash_write_completion1().
Referenced by appl_write(), demo_serial(), run_program(), and run_rmw_normal().
 {
     spiflash_use_so_irq = use_so_irq && spiflash_info->has_so_irq;
     write_data = buffer;
     write_addr = addr;
     write_len = len;
     spiflash_completion = completion;
     spiflash_completion_ref = completion_ref;
     spiflash_write_busy = true;
     if (spiflash_info->dataflash)
         spiflash_multiple_byte_command(sizeof(dataflash_cmd_disable_sector_protection), dataflash_cmd_disable_sector_protection,
                                        0, NULL, // rx
                                        false, // hold_cs_active
                                        spiflash_write_completion1,
                                        NULL);
     else
         spiflash_write_completion1(NULL);
     // if called synchronously, wait for entire write sequence to complete
     if (! completion)
         while (spiflash_write_busy)
             enter_low_power_state();
 }
static void dataflash_rmw_completion1 (void * ref) static
#include <spiflash.c>
Definition at line 794 of file spiflash.c.
References CMD_DATAFLASH_RMW_BUF1, dataflash_rmw_completion2(), and spiflash_command_with_address().
Referenced by dataflash_rmw().
 {
     spiflash_command_with_address(CMD_DATAFLASH_RMW_BUF1,
                                   write_addr,
                                   0, // dummy bytes
                                   write_size, write_data,  // tx
                                   0, NULL,                 // rx
                                   dataflash_rmw_completion2,
                                   NULL);
 }
static void dataflash_rmw_completion2 (void * ref) static
#include <spiflash.c>
Definition at line 805 of file spiflash.c.
References dataflash_rmw_completion3(), and spiflash_info_t::status_busy_level.
Referenced by dataflash_rmw_completion1().
 {
     // start polling status register
     write_status_buf[0] = spiflash_info->status_busy_level;  // prime pump w/ BUSY
     dataflash_rmw_completion3(NULL);
 }
static void dataflash_rmw_completion3 (void * ref) static
#include <spiflash.c>
Definition at line 812 of file spiflash.c.
References spiflash_info_t::read_status_cmd, spiflash_single_byte_command(), spiflash_spi_simple_completion(), spiflash_info_t::status_busy_level, and spiflash_info_t::status_busy_mask.
Referenced by dataflash_rmw_completion2().
 {
     // poll the status register
     // until the flash indicates that the RMW is done.
     if ((write_status_buf[0] & spiflash_info->status_busy_mask) == spiflash_info->status_busy_level)
     {
         // BUSY
         spiflash_single_byte_command(spiflash_info->read_status_cmd,
                                      1,
                                      write_status_buf,
                                      dataflash_rmw_completion3,
                                      NULL);
     }
     else
     {
         // DONE
         spiflash_write_busy = false;
         spiflash_spi_simple_completion(ref);
     }
 }
void dataflash_rmw (uint32_t addr, size_t len, uint8_t * buffer, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 833 of file spiflash.c.
References dataflash_cmd_disable_sector_protection, dataflash_rmw_completion1(), enter_low_power_state(), and spiflash_multiple_byte_command().
Referenced by run_rmw_dataflash().
 {
     write_data = buffer;
     write_addr = addr;
     write_len = len;
     spiflash_completion = completion;
     spiflash_completion_ref = completion_ref;
     spiflash_write_busy = true;
     spiflash_multiple_byte_command(sizeof(dataflash_cmd_disable_sector_protection), dataflash_cmd_disable_sector_protection,
                                    0, NULL, // rx
                                    false, // hold_cs_active
                                    dataflash_rmw_completion1,
                                    NULL);
     // if called synchronously, wait for entire write sequence to complete
     if (! completion)
         while (spiflash_write_busy)
             enter_low_power_state();
 }
void spiflash_set_write_enable (bool enable, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 860 of file spiflash.c.
References CMD_WRITE_DISABLE, CMD_WRITE_ENABLE, and spiflash_single_byte_command().
Referenced by run_program(), test_start(), and write_enable().
 {
     spiflash_single_byte_command(enable ? CMD_WRITE_ENABLE : CMD_WRITE_DISABLE,
                                  0, NULL,  // rx
                                  completion,
                                  completion_ref);
 }
void spiflash_set_sector_protection (bool protect, uint32_t addr, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 871 of file spiflash.c.
References CMD_PROTECT_SECTOR, CMD_UNPROTECT_SECTOR, and spiflash_command_with_address().
Referenced by demo_serial().
 {
     spiflash_command_with_address(protect? CMD_PROTECT_SECTOR : CMD_UNPROTECT_SECTOR,
                                   addr,
                                   0, // dummy bytes
                                   0, NULL,  // tx
                                   0, NULL,  // rx
                                   completion,
                                   completion_ref);
 }
void spiflash_set_global_protect (bool protect, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 887 of file spiflash.c.
References CMD_WRITE_STATUS_REG_BYTE_1, and spiflash_multiple_byte_command().
Referenced by test_start().
 {
     spiflash_scratch_buf[0] = CMD_WRITE_STATUS_REG_BYTE_1;
     spiflash_scratch_buf[1] = protect ? 0x3c : 0x00;
     spiflash_multiple_byte_command(2, spiflash_scratch_buf,  // tx
                                    0, NULL, // rx
                                    false,  // hold_cs_active
                                    completion,
                                    completion_ref);
 }
void spiflash_read_status (size_t len, uint8_t * buffer, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 949 of file spiflash.c.
References spiflash_info_t::read_status_cmd, and spiflash_single_byte_command().
Referenced by dataflash_get_page_size(), dataflash_set_page_size(), get_status(), and test_start().
 {
     spiflash_single_byte_command(spiflash_info->read_status_cmd,
                                  len,
                                  buffer,
                                  completion,
                                  completion_ref);
 }
void spiflash_write_status (uint8_t data, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
void spiflash_write_status2 (uint8_t data, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
void spiflash_read_id (size_t len, uint8_t * buffer, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 972 of file spiflash.c.
References CMD_READ_ID, and spiflash_single_byte_command().
Referenced by read_id(), and spiflash_init().
 {
     spiflash_single_byte_command(CMD_READ_ID,
                                  len, buffer, // rx
                                  completion,
                                  completion_ref);
 }
void spiflash_deep_power_down (bool power_down, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 984 of file spiflash.c.
References CMD_DEEP_POWER_DOWN, CMD_RESUME_FROM_DEEP_POWER_DOWN, and spiflash_single_byte_command().
Referenced by run_powerdn(), and spiflash_init().
 {
     spiflash_single_byte_command(power_down ? CMD_DEEP_POWER_DOWN : CMD_RESUME_FROM_DEEP_POWER_DOWN,
                                  0, NULL,  // rx
                                  completion,
                                  completion_ref);
 }
void spiflash_ultra_deep_power_down (bool power_down, spiflash_completion_fn_t * completion, void * completion_ref)
#include <spiflash.c>
Definition at line 995 of file spiflash.c.
References CMD_RESUME_FROM_DEEP_POWER_DOWN, CMD_ULTRA_DEEP_POWER_DOWN, and spiflash_single_byte_command().
Referenced by demo_serial(), main(), run_powerdn(), test_start(), and test_stop().
 {
     // any command can be used to resume; device will otherwise ignore the cmd
     spiflash_single_byte_command(power_down ? CMD_ULTRA_DEEP_POWER_DOWN : CMD_RESUME_FROM_DEEP_POWER_DOWN,
                                  0, NULL,  // rx
                                  completion,
                                  completion_ref);
 }
bool spiflash_is_dataflash (void)
#include <spiflash.c>
Definition at line 1006 of file spiflash.c.
References spiflash_info_t::dataflash.
Referenced by run_rmw().
 {
     return spiflash_info->dataflash;
 }
uint32_t dataflash_get_page_size (void)
#include <spiflash.c>
Definition at line 1011 of file spiflash.c.
References spiflash_info_t::dataflash, and spiflash_read_status().
Referenced by main().
 {
     uint8_t status_buf[2];
     if (! spiflash_info->dataflash)
         return false;
     spiflash_read_status(sizeof(status_buf), status_buf, NULL, NULL);
     if (status_buf[0] & 1)
         return 256;
     else
         return 264;
 }
bool dataflash_set_page_size (uint32_t page_size)
#include <spiflash.c>
Definition at line 1026 of file spiflash.c.
References spiflash_info_t::dataflash, dataflash_cmd_set_256b_page, dataflash_cmd_set_264b_page, spiflash_multiple_byte_command(), spiflash_read_status(), spiflash_info_t::status_busy_level, and spiflash_info_t::status_busy_mask.
Referenced by main().
 {
     const uint8_t *cmd;
     uint8_t status_buf[2];
     int cmd_len;
     if (! spiflash_info->dataflash)
         return false;
     if (page_size == 256)
     {
         cmd = dataflash_cmd_set_256b_page;
         cmd_len = sizeof(dataflash_cmd_set_256b_page);
     }
     else if (page_size == 264)
     {
         cmd = dataflash_cmd_set_264b_page;
         cmd_len = sizeof(dataflash_cmd_set_264b_page);
     }
     else
         return false;
     spiflash_multiple_byte_command(cmd_len, cmd,  // tx
                                    0, NULL, // rx
                                    false,  // hold_cs_active
                                    NULL,
                                    NULL);
     do
         spiflash_read_status(sizeof(status_buf), status_buf, NULL, NULL);
     while ((status_buf[0] & spiflash_info->status_busy_mask) == spiflash_info->status_busy_level);
     if (status_buf[0] & 1)
         return page_size == 256;
     else
         return page_size == 264;
 }
spiflash_id_t spiflash_init (int bit_rate)
#include <spiflash.c>
Definition at line 1064 of file spiflash.c.
References i, spiflash_info_t::id_bytes, spiflash_info_t::id_size, MAX_FLASH_ID_LEN, PART_UNKNOWN, spi_init(), spiflash_deep_power_down(), SPIFLASH_INFO_TABLE_SIZE, and spiflash_read_id().
Referenced by demo_serial(), and spiflash_setup().
 {
     int i;
     const spiflash_info_t *p;
     spi_init(bit_rate);
     spiflash_busy = false;
     spiflash_info = NULL;
     // issue a resume from deep power down synchronously
     spiflash_deep_power_down(false, NULL, NULL);
     spiflash_deep_power_down(false, NULL, NULL);
     // issue a read ID command synchronously
     spiflash_read_id(MAX_FLASH_ID_LEN, spiflash_scratch_buf, NULL, NULL);
     for (i = 0; i < SPIFLASH_INFO_TABLE_SIZE; i++)
     {
         p = & spiflash_info_table[i];
         if (memcmp(spiflash_scratch_buf, p->id_bytes, p->id_size) == 0)
         {
             spiflash_info = p;
             return i;
         }
     }
     return PART_UNKNOWN;
 }
uint32_t spiflash_smallest_erase_size_above (uint32_t size)
#include <spiflash.c>
Definition at line 1093 of file spiflash.c.
References spiflash_info_t::erase_info, spiflash_info_t::erase_info_count, i, and erase_info_t::size.
Referenced by leave_conf_erase_size(), and main().
 {
     int i;
     const erase_info_t *ei;
     for (i = 0; i < spiflash_info->erase_info_count; i++)
     {
         ei = & spiflash_info->erase_info [i];
         if (ei->size > size)
             return ei->size;
     }
     return 0;
 }
Variable Documentation
int i
#include <spiflash.c>
Definition at line 58 of file spiflash.c.
Referenced by all_ones(), demo_serial(), hex_dump(), init_buffer(), main(), numeric_choices_init_conf_erase_size(), run_rmw_normal(), ScrollText(), slider_get_choice(), slider_init_thresholds(), spiflash_command_with_address(), spiflash_erase(), spiflash_erase_completion2(), spiflash_init(), spiflash_smallest_erase_size_above(), and Test().
int cycle_count = 0
#include <spiflash.c>
Definition at line 59 of file spiflash.c.
const uint8_t at25xe021a_id_bytes[] = { 0x1f, 0x43, 0x01, 0x00 } static
#include <spiflash.c>
Definition at line 105 of file spiflash.c.
const size_t at25xe021a_protection_sector_sizes[] = { 65536, 65536, 65536, 65536 } static
#include <spiflash.c>
Definition at line 106 of file spiflash.c.
const uint8_t at25xe041b_id_bytes[] = { 0x1f, 0x44, 0x02, 0x00 } static
#include <spiflash.c>
Definition at line 108 of file spiflash.c.
const size_t at25xe041b_protection_sector_sizes[] = { 65536, 65536, 65536, 65536, 65536, 65536, 65536, 32768, 8192, 8192, 16384 } static
#include <spiflash.c>
Definition at line 109 of file spiflash.c.
const uint8_t dataflash_cmd_set_256b_page[] = { 0x3d, 0x2a, 0x80, 0xa6 } static
#include <spiflash.c>
Definition at line 111 of file spiflash.c.
Referenced by dataflash_set_page_size().
const uint8_t dataflash_cmd_set_264b_page[] = { 0x3d, 0x2a, 0x80, 0xa7 } static
#include <spiflash.c>
Definition at line 112 of file spiflash.c.
Referenced by dataflash_set_page_size().
const uint8_t dataflash_cmd_chip_erase[] = { 0xc7, 0x94, 0x80, 0x9a } static
#include <spiflash.c>
Definition at line 114 of file spiflash.c.
Referenced by spiflash_erase_completion2().
const uint8_t dataflash_cmd_disable_sector_protection[] = { 0x3d, 0x2a, 0x7f, 0x9a } static
#include <spiflash.c>
Definition at line 115 of file spiflash.c.
Referenced by dataflash_rmw(), spiflash_erase(), and spiflash_write().
const spiflash_info_t spiflash_info_table[]
#include <spiflash.c>
Definition at line 117 of file spiflash.c.
Referenced by appl_erase(), appl_read(), appl_write(), enter_conf_so(), enter_erase(), enter_id(), numeric_choices_init_conf_erase_size(), run_appl(), run_erase(), run_program(), run_read(), run_rmw_dataflash(), and run_rmw_normal().
const spiflash_info_t* spiflash_info static
#include <spiflash.c>
Definition at line 253 of file spiflash.c.
bool spiflash_use_so_irq static
#include <spiflash.c>
Definition at line 254 of file spiflash.c.
bool spiflash_busy static
#include <spiflash.c>
Definition at line 255 of file spiflash.c.
spiflash_completion_fn_t* spiflash_completion static
#include <spiflash.c>
Definition at line 256 of file spiflash.c.
Referenced by spiflash_spi_simple_completion().
void* spiflash_completion_ref static
#include <spiflash.c>
Definition at line 257 of file spiflash.c.
Referenced by spiflash_spi_simple_completion().
uint8_t spiflash_scratch_buf[257] static
#include <spiflash.c>
Definition at line 259 of file spiflash.c.
const erase_info_t* erase_info_fixed static
#include <spiflash.c>
Definition at line 411 of file spiflash.c.
Referenced by spiflash_erase_completion2().
const erase_info_t* erase_info static
#include <spiflash.c>
Definition at line 413 of file spiflash.c.
uint32_t erase_addr static
#include <spiflash.c>
Definition at line 414 of file spiflash.c.
size_t erase_len static
#include <spiflash.c>
Definition at line 415 of file spiflash.c.
uint8_t erase_status_buf[2] static
#include <spiflash.c>
Definition at line 416 of file spiflash.c.
volatile bool spiflash_erase_busy static
#include <spiflash.c>
Definition at line 417 of file spiflash.c.
uint8_t* write_data static
#include <spiflash.c>
Definition at line 643 of file spiflash.c.
uint32_t write_addr static
#include <spiflash.c>
Definition at line 644 of file spiflash.c.
size_t write_len static
#include <spiflash.c>
Definition at line 645 of file spiflash.c.
Referenced by spiflash_write_completion2().
size_t write_size static
#include <spiflash.c>
Definition at line 646 of file spiflash.c.
Referenced by spiflash_write_completion3().
uint8_t write_status_buf[2] static
#include <spiflash.c>
Definition at line 647 of file spiflash.c.
volatile bool spiflash_write_busy static
#include <spiflash.c>
Definition at line 648 of file spiflash.c.