Adesto Flash Demo: MAIN
MAIN
Data Structures
struct state_info_t
struct button_info_t
Macros
#define SLIDER_MAX 48
#define MAX_NUMERIC_CHOICES 8
#define RMW_UPDATE_BYTE_COUNT 20
#define BUFFER_SIZE 8192
Typedefs
typedef void sm_fn_t (void)
Enumerations
enum state_t {
state_init, state_id, state_config, state_erase,
state_write, state_read, state_rmw, state_appl,
state_powerdn, state_serial, state_conf_so, state_conf_erase_size,
state_conf_verify, state_conf_spi_clk, state_message, STATE_MAX
}
Functions
void spiflash_setup (void)
Initialize SPI Module and read Device ID.
void init_buffer (uint32_t buffer_offset, uint32_t len, uint32_t seed)
Initialize Buffer with data to be used with Demo.
void slider_init_thresholds (int num_choices, const int32_t *choices)
Initialize Thresholds for Slider on STK.
int32_t slider_get_choice (int32_t slider_position)
Map value passed in from Slider Library to SPI Flash Demo values.
void spiflash_button_callback (int button, bool pressed)
Callback function for Button Press detection on STK for Demo Menu.
void spiflash_demo (void)
Determines Demo State based on button press.
void test_start (void)
Starts the Demo creates an initial energy pulse by tuning ON/OFF the LED.
void test_stop (void)
Called after chosen demo has completed. Creates final energy pulse by toggling LED.
void numeric_choices_init (void)
Determines numeric choices available on STK slider based on Demo/State.
void enter_default (void)
If State Table has NULL entry these values get plugged in.
void idle_default (void)
Used to manage SLIDER and LCD Scroll.
void button0_default (void)
Used to Advance to next state.
void button1_default (void)
Normally Starts Test/Demo.
void enter_init (void)
Increment State/Default.
void enter_id (void)
Displays Flash ID on LCD.
void button1_config (void)
If in CONFIG MENU if Button1 is pressed Enters SO INTERRUPT Configuration.
void enter_erase (void)
Demo Menu: Called when entering Erase Menu, determines appropriate Erase values and Displays on LCD.
void run_erase (void)
Demo Menu: Runs Erase Demo, Gets Erase size from user selected value on slider.
void preflight_program (void)
Fills in Buffe with Data to be programmed into Flash.
void run_program (void)
Demo Menu: Runs Flash Write Demo Programs Flash, Gets Program Size from user selected value on Slider.
void run_read (void)
Demo Menu: Runs Flash Read Demo Reads Flash, Gets Read Size retrieved from user selection on Slider.
void preflight_rmw (void)
Fills Buffer for RMW Demo to be programmed into Data Flash.
void run_rmw_dataflash (void)
Demo Menu: Runs DataFlash RMW Demo from Main Menu.
void run_rmw_normal (void)
Demo Menu: Runs RMW Demo for 25XE Series from Main Menu.
void run_rmw (void)
Demo Menu: Chooses whether to run RMW for Dataflash or 25XE Series.
void appl_erase (uint32_t len)
Demo Menu: Performs Erase for Application Demo from Main Menu.
void appl_write (uint32_t len)
Demo Menu: Performs Write for Application Demo from Main Menu.
bool appl_read (uint32_t len)
Demo Menu: Performs Read for Application Demo from Main Menu.
void run_appl (void)
Demo Menu: Runs Application Demo from Main Menu.
void run_powerdn (void)
Demo Menu: Runs Serial Flash Powerdown Demo from Main Menu.
void run_serial (void)
Demo Menu: Runs Serial Output Demo from Main Menu.
void display_conf_so (void)
CONFIG Menu: Displays Active SO Selection in CONFIG Menu.
void enter_conf_so (void)
CONFIG Menu: Confirms whether Serial Memory Device has Active SO Feature.
void button1_conf_so (void)
CONFIG Menu: If PB1 is pressed when in Active SO CONFIG Menu toggles whether Active SO is enabled or not. Display Y or N on LCD.
void numeric_choices_init_conf_erase_size (void)
CONFIG MENU: Displays range of values for Erase Size in upper portion of LCD and configures Slider to allow these values to be selected.
void leave_conf_erase_size (void)
CONFIG Menu: Gets user selected Erase size based on slider value.
void display_conf_verify (void)
CONFIG Menu: Gets user selection to verify write data or not.
void enter_conf_verify (void)
CONFIG Menu: Calls function to display Verify Y/N on LCD.
void button1_conf_verify (void)
CONFIG Menu: PB1 toggles between Verify Enable/Disable.
void leave_conf_spi_clk (void)
CONFIG Menu: User Selection for SPI Clock Frequency. User can select between 2MHz or 12MHz SPI clock frequency.
void button1_cfg_done (void)
CONFIG Menu: Final PB1 Press concludes Demo Conigruation and sets state to initial state.
void enter_message (void)
Displays current info on LCD until user press Push-buttons to change or move to the next selection.
void button1_message (void)
Displays current state on LCD based on PB1 Press and location in menu.
int main (void)
Main function, initializes demo.
Variables
CMU_Select_TypeDef main_osc
uint32_t spi_freq
spiflash_id_t part
static bool use_so
static bool erase_size_choices_initialized
static uint32_t erase_size
static bool do_verify
int duration
uint32_t data_written_byte_count
uint8_t buf1 [8192]
uint8_t buf2 [8192]
uint8_t buf3 [8192]
sm_fn_t enter_default
sm_fn_t idle_default
sm_fn_t button0_default
sm_fn_t button1_default
sm_fn_t enter_init
sm_fn_t enter_id
sm_fn_t button1_config
sm_fn_t enter_erase
sm_fn_t run_erase
sm_fn_t run_read
sm_fn_t preflight_program
sm_fn_t run_program
sm_fn_t preflight_rmw
sm_fn_t run_rmw
sm_fn_t run_appl
sm_fn_t run_powerdn
sm_fn_t run_serial
sm_fn_t enter_conf_so
sm_fn_t button1_conf_so
sm_fn_t numeric_choices_init_conf_erase_size
sm_fn_t leave_conf_erase_size
sm_fn_t enter_conf_verify
sm_fn_t button1_conf_verify
sm_fn_t leave_conf_spi_clk
sm_fn_t enter_message
sm_fn_t button1_message
char * message_text
int message_number
static const state_info_t state_info [STATE_MAX]
static int32_t state_slider_position [STATE_MAX]
static int32_t numeric_choices_count [STATE_MAX]
static int32_t numeric_choices [STATE_MAX][8]
static button_info_t button_info [2]
int slider_num_choices
const int32_t * slider_choices
int32_t slider_threshold [8]
state_t state
state_t prev_state
state_t message_return_state
uint8_t ts_status_buf_1 [2]
static char erase_msg [7]
uint8_t buf1 [8192]
uint8_t buf2 [8192]
uint8_t buf3 [8192]
Detailed Description
SPI Flash Demo Pin Connections
* Pin Configurations for EFM32 STK to EMSESNSR-WSP with EMMEM
* Breakout Board.
*
*   EFM32     EFM32    STK32
*   port      port     exp      EMMEM    EMMEM
*   function  pin      pin      pin      function
*   --------  -------  -------  -------  --------
*   Vmcu               2        P1-1     Vdd
*   GND                1,19     P1-2     GND
*                      n/c      P1-3     n/c
*                      n/c      P1-4     /WP     EMMEM has jumper to Vdd
*   GPIO      PB11     11       P1-5     /HOLD   EMMEM has jumper to Vdd
*
*   US1_TX    PD0      4        P2-1     SDI
*   US1_CLK   PD2      8        P2-2     SCLK
*   US1_RX    PD1      6        P2-3     SDO
*   US1_CS    PD3      10       P2-4     nCS
*                      n/c      P2-5     n/c
*
*
* Connections from Silicon Labs starter kit to host via LEUART.
*
*   EFM32     EFM32    STL32    232R      232R
*   port      port     exp      cable     cable
*   function  pin      pin      pin       function
*   --------  -------  -------  --------  --------
*   GND                1,19     1         GND
*   LEU0_TX0  PD4      12       5         RXD
*   LEU0_RX0  PD5      14       4         TxD
*
*
Function Documentation
void spiflash_setup (void)
#include <main.c>
Initialize SPI Module and read Device ID.
Definition at line 114 of file main.c.
References fatal(), and spiflash_init().
Referenced by leave_conf_spi_clk(), and main().
 {
     part = spiflash_init(spi_freq);
     if (part == PART_UNKNOWN)
         fatal("unrecognized flash");
 }
void init_buffer (uint32_t buffer_offset, uint32_t len, uint32_t seed)
#include <main.c>
Initialize Buffer with data to be used with Demo.
Parameters
[in] buffer_offset Offset into Buffer
[in] len Length of Buffer
[in] seed Seed to help randomize data
Definition at line 318 of file main.c.
Referenced by appl_read(), appl_write(), preflight_program(), preflight_rmw(), run_program(), and run_read().
 {
     int i;
     uint8_t initial;
     initial = (seed >> 24) ^ (seed >> 16) ^ (seed >> 8) ^ seed;
     for (i = 0; i < sizeof(buf1); i++)
         buf1[buffer_offset + i] = initial + i;
 }
void slider_init_thresholds (int num_choices, const int32_t * choices)
#include <main.c>
Initialize Thresholds for Slider on STK.
Parameters
[in] num_choices Number of Choices available with slider
[in] choices Available Choices with Slider
Definition at line 342 of file main.c.
Referenced by numeric_choices_init().
 {
     int i;
     slider_num_choices = num_choices;
     slider_choices = choices;
     for (i = 0; i < num_choices; i++)
         slider_threshold[i] = ((i + 1) * SLIDER_MAX) / num_choices;
 }
int32_t slider_get_choice (int32_t slider_position)
#include <main.c>
Map value passed in from Slider Library to SPI Flash Demo values.
Parameters
[in] slider_position Position of Finger on Slider
Definition at line 360 of file main.c.
Referenced by idle_default(), leave_conf_erase_size(), leave_conf_spi_clk(), run_appl(), run_erase(), run_powerdn(), run_program(), run_read(), run_rmw_dataflash(), and run_rmw_normal().
 {
     int i;
     for (i = 0; i < (slider_num_choices - 1); i++)
         if (slider_position < slider_threshold[i])
             return slider_choices[i];
     return slider_choices[i];
 }
void spiflash_button_callback (int button, bool pressed)
#include <main.c>
Callback function for Button Press detection on STK for Demo Menu.
Parameters
[in] button Button Number
[in] pressed Is button Pressed or not
Definition at line 379 of file main.c.
Referenced by main().
 {
     button_info_t *info = & button_info[button];
     if (pressed == info->state)
         return;
     if (pressed)
         info->pressed = true;
     else
         info->released = true;
 }
void spiflash_demo (void)
#include <main.c>
Determines Demo State based on button press.
Note
This is the primary State Machine for the Serial Flash Demo
Definition at line 402 of file main.c.
References button0_default(), button1_default(), enter_default(), and idle_default().
Referenced by main().
 {
     prev_state = STATE_MAX;
     state = state_id;
     while (true)
     {
         if (state != prev_state)
         {
             if ((prev_state < STATE_MAX) && state_info[prev_state].leave_fn)
                 state_info[prev_state].leave_fn();
             prev_state = state;
             if (state_info[state].enter_fn)
                 state_info[state].enter_fn();
             else
                 enter_default();
         }
         else if (button_info[0].pressed)
         {
             button_info[0].pressed = false;
             if (state_info[state].button0_fn)
                 state_info[state].button0_fn();
             else
                 button0_default();
         }
         else if (button_info[1].pressed)
         {
             button_info[1].pressed = false;
             if (state_info[state].button1_fn)
                 state_info[state].button1_fn();
             else
                 button1_default();
         }
         else
         {
             if (state_info[state].idle_fn)
                 state_info[state].idle_fn();
             else
                 idle_default();
         }
     }
 }
void test_start (void)
#include <main.c>
Starts the Demo creates an initial energy pulse by tuning ON/OFF the LED.
Definition at line 452 of file main.c.
References delay(), led_set(), spiflash_read_status(), spiflash_set_global_protect(), spiflash_set_write_enable(), and spiflash_ultra_deep_power_down().
Referenced by button1_default().
 {
     // make sure SPI flash is in ultra deep power down
 //  spiflash_ultra_deep_power_down(true, NULL, NULL);
     // disable LCD
     SegmentLCD_AllOff();
     SegmentLCD_Disable();
     CAPLESENSE_Init(true); // Disable slider sensing
     // pulse LED on 50ms
     led_set(0, 1);
     delay(50);
     led_set(0, 0);
     // delay 50ms
     delay(50);
     // wake part up
     spiflash_ultra_deep_power_down(false, NULL, NULL);      //XXX verify if we need both of these...?
     spiflash_ultra_deep_power_down(false, NULL, NULL);
     // Necessary for erase and write commands.
     // XXX could add a bool field to state_info to control whether this is done
     spiflash_set_write_enable(true, NULL, NULL);
     spiflash_set_global_protect(false, NULL, NULL);
     spiflash_read_status(2, ts_status_buf_1, NULL, NULL);
 }
void test_stop (void)
#include <main.c>
Called after chosen demo has completed. Creates final energy pulse by toggling LED.
Definition at line 490 of file main.c.
References delay(), led_set(), and spiflash_ultra_deep_power_down().
Referenced by button1_default().
 {
     // put part in ultra deep power down
     spiflash_ultra_deep_power_down(true, NULL, NULL);
     delay(50); // delay 50ms
     // pulse LED on 50ms
     led_set(0, 1);
     delay(50);
     led_set(0, 0);
     // enable LCD
     SegmentLCD_Init(false); // Enable LCD without voltage boost
     // force display update
     prev_state = STATE_MAX;
 }
void numeric_choices_init (void)
#include <main.c>
Determines numeric choices available on STK slider based on Demo/State.
Definition at line 514 of file main.c.
References slider_init_thresholds().
Referenced by enter_default(), and enter_erase().
 {
     if (state_info[state].numeric_choices_init_fn)
         state_info[state].numeric_choices_init_fn();
     else
     {
         numeric_choices_count[state] = state_info[state].numeric_choices_fixed_count;
         memcpy(numeric_choices[state], state_info[state].numeric_choices_fixed, sizeof(numeric_choices[state]));
     }
     if (numeric_choices_count[state])
     {
           CAPLESENSE_Init(false); // Init slider sensing
           slider_init_thresholds(numeric_choices_count[state],
                                  numeric_choices[state]);
     }
     else
     {
         SegmentLCD_NumberOff();
         CAPLESENSE_Init(true); // Not slider sensing
     }
 }
void enter_default (void)
#include <main.c>
If State Table has NULL entry these values get plugged in.
Definition at line 542 of file main.c.
References numeric_choices_init().
Referenced by spiflash_demo().
 {
     SegmentLCD_Write((char *) state_info[state].name);
     // cast because SegmentLCD_Write doesn't have const qualifier
     numeric_choices_init();
 }
void idle_default (void)
#include <main.c>
Used to manage SLIDER and LCD Scroll.
Definition at line 554 of file main.c.
References EM2Sleep(), lcd_scroll_update(), and slider_get_choice().
Referenced by spiflash_demo().
 {
     if (numeric_choices_count[state])
     {
         int32_t val;
         val = CAPLESENSE_getSliderPosition();
         if (val >= 0)
             state_slider_position[state] = val;
         SegmentLCD_Number(slider_get_choice(state_slider_position[state]));
     }
     else
     {
         lcd_scroll_update();
     }
     EM2Sleep(325);
 }
void button0_default (void)
#include <main.c>
Used to Advance to next state.
Definition at line 576 of file main.c.
References lcd_scroll_stop().
Referenced by spiflash_demo().
 {
     lcd_scroll_stop();
     if (state_info[state].next)
         state = state_info[state].next;
     else
         state += 1;
 }
void button1_default (void)
#include <main.c>
Normally Starts Test/Demo.
Definition at line 590 of file main.c.
References enter_low_power_state(), test_start(), and test_stop().
Referenced by spiflash_demo().
 {
     if (! state_info[state].run_fn)
         return;
     // wait for button 1 release
     while (button_info[1].state)
         enter_low_power_state();
     if (state_info[state].preflight_fn)
         state_info[state].preflight_fn();
     test_start();
     state_info[state].run_fn();
     test_stop();
 }
void enter_init (void)
#include <main.c>
Increment State/Default.
Definition at line 615 of file main.c.
 {
     // For now, nothing needs to be done here.
     state++;
 }
void enter_id (void)
#include <main.c>
Displays Flash ID on LCD.
Definition at line 626 of file main.c.
References lcd_scroll_start().
 {
     lcd_scroll_start(spiflash_info_table[part].name);
     SegmentLCD_NumberOff();
 }
void button1_config (void)
#include <main.c>
If in CONFIG MENU if Button1 is pressed Enters SO INTERRUPT Configuration.
Definition at line 637 of file main.c.
 {
     state = state_conf_so;
 }
void enter_erase (void)
#include <main.c>
Demo Menu: Called when entering Erase Menu, determines appropriate Erase values and Displays on LCD.
Definition at line 650 of file main.c.
References fatal(), and numeric_choices_init().
 {
     uint32_t device_size = spiflash_info_table[part].device_size;
     memcpy(erase_msg, "ER     ", 7);
     if (erase_size == device_size)
         memcpy(erase_msg + 3, "Chip", 4);
     else switch (erase_size)
     {
     case 64:
         memcpy(erase_msg + 3, "64b", 3);
         break;
     case 256:
         memcpy(erase_msg + 3, "256b", 4);
         break;
     case 2048:
         memcpy(erase_msg + 3, "2K", 2);
         break;
     case 4096:
         memcpy(erase_msg + 3, "4K", 2);
         break;
     case 32768:
         memcpy(erase_msg + 3, "32K", 3);
         break;
     case 65536:
         memcpy(erase_msg + 3, "64K", 3);
         break;
     default:
         fatal("unknown erase size");
     }
     SegmentLCD_Write((char *) erase_msg);
     numeric_choices_init();
 }
void run_erase (void)
#include <main.c>
Demo Menu: Runs Erase Demo, Gets Erase size from user selected value on slider.
Note
Determines total size of device from Device Table in spiflash.c
Definition at line 692 of file main.c.
References fatal(), slider_get_choice(), and spiflash_erase().
 {
     uint32_t slider = slider_get_choice(state_slider_position[state]);
     uint32_t size = 1024 * slider;
     int32_t count = size;
     data_written_byte_count = 0;
     uint32_t device_size = spiflash_info_table[part].device_size;
     uint32_t addr = 0;
     while (count > 0)
     {
         if (! spiflash_erase(addr, erase_size, erase_size, use_so, NULL, NULL))
             fatal("erase error");
         addr += erase_size;
         if (addr >= device_size)
             addr = 0;
         count -= erase_size;
     }
     message_text = "ER done";
     message_number = slider;
     message_return_state = state;
     state = state_message;
 }
void preflight_program (void)
#include <main.c>
Fills in Buffe with Data to be programmed into Flash.
Definition at line 724 of file main.c.
References init_buffer().
 {
     init_buffer(0, BUFFER_SIZE, 0xdeadbeef);
 }
void run_program (void)
#include <main.c>
Demo Menu: Runs Flash Write Demo Programs Flash, Gets Program Size from user selected value on Slider.
Note
Determines Device Minimum Page size and Total Size of Device from Device Table in spiflash.c
Definition at line 738 of file main.c.
References init_buffer(), slider_get_choice(), spiflash_set_write_enable(), and spiflash_write().
 {
     uint32_t slider = slider_get_choice(state_slider_position[state]);
     uint32_t size = 1024 * slider;
     int32_t count = size;
     data_written_byte_count = 0;
     uint32_t program_page_size = spiflash_info_table[part].program_page_size;
     uint32_t device_size = spiflash_info_table[part].device_size;
     uint32_t addr = 0;
     uint32_t buffer_offset = 0;
     while (count > 0)
     {
         if (do_verify)
             init_buffer(buffer_offset, program_page_size, addr);
         spiflash_set_write_enable(true, NULL, NULL);
         spiflash_write(addr, program_page_size, & buf1[buffer_offset], use_so, NULL, NULL);
         addr += program_page_size;
         if (addr >= device_size)
             addr = 0;
         buffer_offset += program_page_size;
         if (buffer_offset >= sizeof(buf1))
             buffer_offset = 0;
         count -= program_page_size;
     }
     data_written_byte_count = addr;
     message_text = "Wr done";
     message_number = slider;
     message_return_state = state;
     state = state_message;
 }
void run_read (void)
#include <main.c>
Demo Menu: Runs Flash Read Demo Reads Flash, Gets Read Size retrieved from user selection on Slider.
Note
Determines Device Minimum Page size and Total Size of Device from Device Table in spiflash.c
Definition at line 784 of file main.c.
References init_buffer(), slider_get_choice(), and spiflash_read().
 {
     uint32_t slider = slider_get_choice(state_slider_position[state]);
     uint32_t size = 1024 * slider;
     int32_t count = size;
     uint32_t program_page_size = spiflash_info_table[part].program_page_size;
     uint32_t device_size = spiflash_info_table[part].device_size;
     uint32_t addr = 0;
     uint32_t buffer_offset = 0;
     while (count > 0)
     {
         if (do_verify)
             init_buffer(buffer_offset, program_page_size, addr);
         spiflash_read(addr, program_page_size, & buf2[buffer_offset], NULL, NULL);
         addr += program_page_size;
         if (do_verify && (addr <= data_written_byte_count))
         {
             if (memcmp (buf1 + buffer_offset, buf2 + buffer_offset, program_page_size) != 0)
             {
                 message_text = "DataErr";
                 message_number = addr >> 10;
                 if (message_number > 9999)
                     message_number = 9999;
                 message_return_state = state;
                 state = state_message;
                 return;
             }
         }
         if (addr >= device_size)
             addr = 0;
         buffer_offset += program_page_size;
         if (buffer_offset >= sizeof(buf2))
             buffer_offset = 0;
         count -= program_page_size;
     }
     message_text = "READ dn";
     message_number = slider;
     message_return_state = state;
     state = state_message;
 }
void preflight_rmw (void)
#include <main.c>
Fills Buffer for RMW Demo to be programmed into Data Flash.
Note
RMW command only needs this for dataflash, not for normal SPI flash
Definition at line 840 of file main.c.
References init_buffer().
 {
     init_buffer(0, BUFFER_SIZE, 0xdeadbeef);
 }
void run_rmw_dataflash (void)
#include <main.c>
Demo Menu: Runs DataFlash RMW Demo from Main Menu.
Note
Gets choice from slider value, Device Minimum Erase Size, and Total Size of device is read from Device Table in spiflash.c
Definition at line 855 of file main.c.
References dataflash_rmw(), and slider_get_choice().
Referenced by run_rmw().
 {
     uint32_t slider = slider_get_choice(state_slider_position[state]);
     uint32_t size = slider;
     int32_t count = size;
     uint32_t program_page_size = spiflash_info_table[part].program_page_size;
     uint32_t device_size = spiflash_info_table[part].device_size;
     uint32_t addr = 0;
     uint32_t offset = 0;  // offset within block to update
     while (count > 0)
     {
         dataflash_rmw(addr + offset, RMW_UPDATE_BYTE_COUNT, buf1 + offset, NULL, NULL);
         addr += program_page_size;
         if (addr > device_size)
             addr = 0;
         offset += RMW_UPDATE_BYTE_COUNT;
         if ((offset + RMW_UPDATE_BYTE_COUNT) > program_page_size)
             offset = 0;
         count --;
     }
     message_text = "RMW dn";
     message_number = slider;
     message_return_state = state;
     state = state_message;
 }
void run_rmw_normal (void)
#include <main.c>
Demo Menu: Runs RMW Demo for 25XE Series from Main Menu.
Note
Gets choice from slider value, Device Minimum Erase Size, and Total Size of device is read from Device Table in spiflash.c
Definition at line 896 of file main.c.
References slider_get_choice(), spiflash_erase(), spiflash_read(), and spiflash_write().
Referenced by run_rmw().
 {
     uint32_t slider = slider_get_choice(state_slider_position[state]);
     uint32_t size = slider;
     int32_t count = size;
     uint32_t erase_size = spiflash_info_table[part].erase_info[0].size;
     uint32_t device_size = spiflash_info_table[part].device_size;
     uint32_t addr = 0;
     uint32_t offset = 0;  // offset within block to update
     while (count > 0)
     {
         int i;
         spiflash_read(addr, erase_size, buf2, NULL, NULL);
         // modify data
         for (i = 0; i < RMW_UPDATE_BYTE_COUNT; i++)
             buf2[offset + i]++;
         // erase and write back
         spiflash_erase(addr, erase_size, erase_size, use_so, NULL, NULL);
         spiflash_write(addr, erase_size, buf2, use_so, NULL, NULL);
         addr += erase_size;
         if (addr > device_size)
             addr = 0;
         offset += RMW_UPDATE_BYTE_COUNT;
         if ((offset + RMW_UPDATE_BYTE_COUNT) > erase_size)
             offset = 0;
         count --;
     }
     message_text = "RMW dn";
     message_number = slider;
     message_return_state = state;
     state = state_message;
 }
void run_rmw (void)
#include <main.c>
Demo Menu: Chooses whether to run RMW for Dataflash or 25XE Series.
Definition at line 944 of file main.c.
References run_rmw_dataflash(), run_rmw_normal(), and spiflash_is_dataflash().
 {
     if (spiflash_is_dataflash())
         run_rmw_dataflash();
     else
         run_rmw_normal();
 }
void appl_erase (uint32_t len)
#include <main.c>
Demo Menu: Performs Erase for Application Demo from Main Menu.
Note
Looks up Device Size from Serial Memory Table
Parameters
[in] len Size of Serial Memory being used. Looked up from Serial Memory Table
Definition at line 961 of file main.c.
References fatal(), and spiflash_erase().
Referenced by appl_write().
 {
     uint32_t device_size = spiflash_info_table[part].device_size;
     if (len > device_size)
         len = device_size;
     if (! spiflash_erase(0, len, 0, use_so, NULL, NULL))
         fatal("erase error");
 }
void appl_write (uint32_t len)
#include <main.c>
Demo Menu: Performs Write for Application Demo from Main Menu.
Note
Looks up Program Page Size and Device Size from Serial Memory Table
Parameters
[in] len How much memory to write
Definition at line 979 of file main.c.
References appl_erase(), init_buffer(), and spiflash_write().
Referenced by run_appl().
 {
     uint32_t program_page_size = spiflash_info_table[part].program_page_size;
     uint32_t device_size = spiflash_info_table[part].device_size;
     uint32_t addr = 0;
     uint32_t buffer_offset = 0;
     uint32_t count = len;
     while (count)
     {
         if (addr == 0)
             appl_erase(len - addr);
         init_buffer(buffer_offset, program_page_size, addr);
         spiflash_write(addr, program_page_size, & buf1[buffer_offset], use_so, NULL, NULL);
         data_written_byte_count += program_page_size;
         addr += program_page_size;
         if (addr >= device_size)
             addr = 0;
         buffer_offset += program_page_size;
         if (buffer_offset >= sizeof(buf1))
             buffer_offset = 0;
         count -= program_page_size;
     }
 }
bool appl_read (uint32_t len)
#include <main.c>
Demo Menu: Performs Read for Application Demo from Main Menu.
Note
Looks up Program Page Size and Device Size from Serial Memory Table
Parameters
[in] len How much memory to read
Definition at line 1012 of file main.c.
References init_buffer(), and spiflash_read().
Referenced by run_appl().
 {
     uint32_t program_page_size = spiflash_info_table[part].program_page_size;
     uint32_t device_size = spiflash_info_table[part].device_size;
     uint32_t addr = 0;
     uint32_t buffer_offset = 0;
     uint32_t count = len;
     while (count)
     {
         init_buffer(buffer_offset, program_page_size, addr);
         spiflash_read(addr, program_page_size, & buf2[buffer_offset], NULL, NULL);
         if (memcmp(buf1 + buffer_offset, buf2 + buffer_offset, program_page_size) != 0)
         {
             return false;
         }
         addr += program_page_size;
         if (addr >= device_size)
             addr = 0;
         buffer_offset += program_page_size;
         if (buffer_offset >= sizeof(buf2))
             buffer_offset = 0;
         count -= program_page_size;
     }
     return true;
 }
void run_appl (void)
#include <main.c>
Demo Menu: Runs Application Demo from Main Menu.
Note
Looks up Device Size from Serial Memory Table
Definition at line 1047 of file main.c.
References appl_read(), appl_write(), and slider_get_choice().
 {
     uint32_t slider = slider_get_choice(state_slider_position[state]);
     uint32_t size = 1024 * slider;
     uint32_t addr;
     uint32_t device_size = spiflash_info_table[part].device_size;
     uint32_t bytes_per_iter;
     bool read_status;
     if (size > device_size)
         bytes_per_iter = device_size;
     else
         bytes_per_iter = size;
     addr = 0;
     while (size)
     {
         data_written_byte_count = 0;
         appl_write(bytes_per_iter);
         read_status = appl_read(bytes_per_iter);
         if (! read_status)
         {
             message_number = addr / spiflash_info_table[part].program_page_size;
             if (message_number > 9999)
                 message_number = 9999;
             break;
         }
         size -= bytes_per_iter;
         addr += bytes_per_iter;
     }
     if (read_status)
     {
         message_text = "Appl dn";
         message_number = slider;
     }
     else
     {
         message_text = "ReadErr";
     }
     message_return_state = state;
     state = state_message;
 }
void run_powerdn (void)
#include <main.c>
Demo Menu: Runs Serial Flash Powerdown Demo from Main Menu.
Note
Slider position determines whether device is put into DEEP SLEEP or ULTRA DEEP SLEEP
Definition at line 1099 of file main.c.
References oneshot_done(), oneshot_start_s(), slider_get_choice(), spiflash_deep_power_down(), and spiflash_ultra_deep_power_down().
 {
     uint32_t slider = slider_get_choice(state_slider_position[state]);
     // test deep power down
     if(slider == 0){
         spiflash_deep_power_down(true, NULL, NULL);
         oneshot_start_s(1);
         while( ! oneshot_done() );
         EMU_EnterEM3(true);
         message_text = "DPD dn";
         spiflash_deep_power_down(false, NULL, NULL);
     }
     else{
         spiflash_ultra_deep_power_down(true, NULL, NULL);
         oneshot_start_s(1);
         while( ! oneshot_done() );
         EMU_EnterEM3(true);
         message_text = "UDPD dn";
         spiflash_ultra_deep_power_down(false, NULL, NULL);
     }
     button_info[1].pressed = false;
     message_number = slider;
     message_return_state = state;
     state = state_message;
 }
void run_serial (void)
#include <main.c>
Demo Menu: Runs Serial Output Demo from Main Menu.
Note
Prints out data that is Wrote/Read via LPUART, can be viewed via terminal Window. Use EMCOM-FT230 plugged into USB-UART Slot closest to 20pin Expansion Header.
Definition at line 1134 of file main.c.
References demo_serial().
 {
     demo_serial();
 }
void display_conf_so (void)
#include <main.c>
CONFIG Menu: Displays Active SO Selection in CONFIG Menu.
Note
User chooses whether Active SO Interrupt is used by Pressing PB1. If the Serial Memory Device does not have Active SO feature this selection will not be displayed in the CONFIG Menu.
Definition at line 1148 of file main.c.
Referenced by button1_conf_so(), and enter_conf_so().
 {
     char *s;
     if (use_so)
         s = "SO    Y";
     else
         s = "SO    N";
     SegmentLCD_Write(s);
 }
void enter_conf_so (void)
#include <main.c>
CONFIG Menu: Confirms whether Serial Memory Device has Active SO Feature.
Note
Looks up in Serial Memory Table whether Device being used has Active SO feature or not. If it does it will display on LCD.
Definition at line 1166 of file main.c.
References display_conf_so().
 {
     if (! spiflash_info_table[part].has_so_irq)
     {
         state++;
         return;
     }
     display_conf_so();
 }
void button1_conf_so (void)
#include <main.c>
CONFIG Menu: If PB1 is pressed when in Active SO CONFIG Menu toggles whether Active SO is enabled or not. Display Y or N on LCD.
Definition at line 1182 of file main.c.
References display_conf_so().
 {
     use_so = ! use_so;
     display_conf_so();
 }
void numeric_choices_init_conf_erase_size (void)
#include <main.c>
CONFIG MENU: Displays range of values for Erase Size in upper portion of LCD and configures Slider to allow these values to be selected.
Note
Due to display limitations (four digit numeric only), values in kilobytes are shown as the number of kilobytes, but values of 64 or 256 bytes are shown as zero (i.e., display rounded to 0 kibibytes)
Definition at line 1199 of file main.c.
 {
     int i;
     if (erase_size_choices_initialized)
         return;
     numeric_choices_count[state] = 0;
     for (i = 0; i < spiflash_info_table[part].erase_info_count; i++)
     {
         numeric_choices[state][i] = spiflash_info_table[part].erase_info[i].size >> 10;
         numeric_choices_count[state] += 1;
     }
     for (i = 0; i < numeric_choices_count[state]; i++)
     {
         int32_t choice = numeric_choices[state][i];
         if (((erase_size < 1024) && (choice == 0)) ||
             ((erase_size >= 1024) && (choice == erase_size >> 10)))
         {
             state_slider_position[state] = slider_threshold[i] - 1;
             break;
         }
     }
 }
void leave_conf_erase_size (void)
#include <main.c>
CONFIG Menu: Gets user selected Erase size based on slider value.
Note
Due to display limitations (four digit numeric only), values in kilobytes are shown as the number of kilobytes, but values of 64 or 256 bytes are shown as zero (i.e., display rounded to 0 kibibytes)
Definition at line 1235 of file main.c.
References slider_get_choice(), and spiflash_smallest_erase_size_above().
 {
     int choice = slider_get_choice(state_slider_position[state_conf_erase_size]);
     // due to display limitations (numeric only), values in kibibytes are shown as the
     // number of kibibytes, but values of 64 or 256 bytes are shown as zero
     // (i.e., display rounded to 0 kibibytes)
     if (choice)
         erase_size = 1024 * choice;
     else
         erase_size = spiflash_smallest_erase_size_above(0);
     SegmentLCD_NumberOff();
 }
void display_conf_verify (void)
#include <main.c>
CONFIG Menu: Gets user selection to verify write data or not.
Note
Verify if Enabled will read back the data that was wrote and verify against the initial data in the buffer that was used for write.
Definition at line 1256 of file main.c.
Referenced by button1_conf_verify(), and enter_conf_verify().
 {
     char *s;
     if (do_verify)
         s = "VFT   Y";
     else
         s = "VFY   N";
     SegmentLCD_Write(s);
 }
void enter_conf_verify (void)
#include <main.c>
CONFIG Menu: Calls function to display Verify Y/N on LCD.
Definition at line 1271 of file main.c.
References display_conf_verify().
 {
     display_conf_verify();
 }
void button1_conf_verify (void)
#include <main.c>
CONFIG Menu: PB1 toggles between Verify Enable/Disable.
Definition at line 1281 of file main.c.
References display_conf_verify().
 {
     do_verify = ! do_verify;
     display_conf_verify();
 }
void leave_conf_spi_clk (void)
#include <main.c>
CONFIG Menu: User Selection for SPI Clock Frequency. User can select between 2MHz or 12MHz SPI clock frequency.
Note
2MHz SPI operation runs from internal 14MHz clock. Fast wakeup from Sleep Modes 12MHz SPI operation runs from external 48MHz XTAL. Requires longer time to wakeup from sleep modes to allow HFCLK to stabilize.
Definition at line 1297 of file main.c.
References slider_get_choice(), and spiflash_setup().
 {
     CMU_Select_TypeDef new_main_osc;  // cmuSelect_HFRCO or cmuSelect_HFXO
     spi_freq = 1000000 * slider_get_choice(state_slider_position[state_conf_spi_clk]);
     SegmentLCD_NumberOff();
     if (spi_freq == 2000000)
         new_main_osc = cmuSelect_HFRCO;
     else
         new_main_osc = cmuSelect_HFXO;
     if (new_main_osc == main_osc)
         return;  // not changed
     main_osc = new_main_osc;
     CMU_ClockSelectSet(cmuClock_HF, main_osc);
     if (main_osc == cmuSelect_HFRCO)
         CMU_OscillatorEnable(cmuSelect_HFXO, false, false); // stop HFXO
     else
         CMU_OscillatorEnable(cmuSelect_HFRCO, false, false); // stop HFRCO
     spiflash_setup();
 }
void button1_cfg_done (void)
#include <main.c>
CONFIG Menu: Final PB1 Press concludes Demo Conigruation and sets state to initial state.
Definition at line 1330 of file main.c.
 {
     state = state_id;
 }
void enter_message (void)
#include <main.c>
Displays current info on LCD until user press Push-buttons to change or move to the next selection.
Definition at line 1341 of file main.c.
 {
     SegmentLCD_Write(message_text);
     SegmentLCD_Number(message_number);
 }
void button1_message (void)
#include <main.c>
Displays current state on LCD based on PB1 Press and location in menu.
Definition at line 1352 of file main.c.
References lcd_scroll_stop().
 {
     lcd_scroll_stop();
     state = message_return_state;
 }
int main (void)
#include <main.c>
Main function, initializes demo.
Configures Clocks, GPIO/GPIO Interrupts for Push-buttons, Configures LEDs, initializes Low Power States, Enables LCD, Enables Capsense/Slider, configures SPI/spiflash setup, calls main spiflash_demo from while(1)
Definition at line 1367 of file main.c.
References button_init(), dataflash_get_page_size(), dataflash_set_page_size(), delay_init(), EM2Sleep(), fatal(), gpio_irq_init(), led_init(), low_power_init(), spiflash_button_callback(), spiflash_demo(), spiflash_setup(), spiflash_smallest_erase_size_above(), spiflash_ultra_deep_power_down(), and xTimerForWakeUp.
 {
   int i;
   CHIP_Init();  // Chip errata
   main_osc = cmuSelect_HFRCO;
   spi_freq = 2000000;
   // start HFRCO
   CMU_ClockSelectSet(cmuClock_HF, main_osc);
   CMU_ClockEnable(cmuClock_HFPER, 1);
   CMU_ClockEnable(cmuClock_GPIO, true);
   // Start LFXO, and use LFXO for low-energy modules
   CMU_ClockEnable(cmuClock_CORELE, true);
   CMU_ClockSelectSet(cmuClock_LFA, cmuSelect_LFXO);
   CMU_ClockSelectSet(cmuClock_LFB, cmuSelect_LFXO);
   CMU_ClockEnable(cmuClock_LESENSE, 1);
   CMU_ClockDivSet(cmuClock_LESENSE, cmuClkDiv_1);
   CMU_ClockEnable(cmuClock_ACMP0, 1);
   CMU_ClockEnable(cmuClock_ACMP1, 1);
   RTCDRV_Init();
   RTCDRV_AllocateTimer( &xTimerForWakeUp);
   delay_init();
   gpio_irq_init();
   led_init();
   button_init(spiflash_button_callback);    //Manages Button States
   low_power_init();
   SegmentLCD_Init(false); // Enable LCD without voltage boost
   for (i = 0; i < STATE_MAX; i++)       //Configure Slider to Default
       state_slider_position[i] = 0;
   CAPLESENSE_Init(true); // Init slider sensing but in sleep
   spiflash_setup();     //Configures SPI Port and Reads Flash ID
   use_so = false;
   erase_size_choices_initialized = false;
   erase_size = spiflash_smallest_erase_size_above(256);
   do_verify = false;
   // if the part is a DataFlash, make sure it is set to 256b pages
   if (dataflash_get_page_size() == 264)
   {
       if (! dataflash_set_page_size(256))
           fatal("Can't set DataFlash page size");
   }
   spiflash_ultra_deep_power_down(true, NULL, NULL);     //Puts Flash into Ultra Deep Powerdown
   SegmentLCD_Write("Fl Demo");      //TODO possibly remove...?
   EM2Sleep(250);
   data_written_byte_count = 0;
   while (true)
     spiflash_demo();
   return 0;
 }