Adesto Flash Demo: Delay
Delay
AppManagement
Application Delay and timing functions.
Macros
#define RTC_DIVIDER (32)
#define RTC_CLOCK (32768U)
#define MSEC_TO_TICKS_DIVIDER (1000U * RTC_DIVIDER)
#define MSEC_TO_TICKS_ROUNDING_FACTOR (MSEC_TO_TICKS_DIVIDER / 2)
#define MSEC_TO_TICKS(ms)
Functions
void delay_init (void)
Delay Initialization.
static void delay_callback (RTCDRV_TimerID_t id, void *user)
Delay Callback function.
void delay (uint32_t ms)
Delay ms function.
Variables
static RTCDRV_TimerID_t delay_timer
static volatile bool delay_done
Detailed Description
Application Delay and timing functions.
Macro Definition Documentation
#define MSEC_TO_TICKS (ms)
#include <delay.c>
Value:
((((uint64_t)(ms) * RTC_CLOCK)    \
                                            + MSEC_TO_TICKS_ROUNDING_FACTOR ) \
                                          / MSEC_TO_TICKS_DIVIDER )
Definition at line 60 of file delay.c.
Function Documentation
void delay_init (void)
#include <delay.c>
Delay Initialization.
Definition at line 72 of file delay.c.
References fatal().
Referenced by main().
 {
     if (ECODE_EMDRV_RTCDRV_OK != RTCDRV_AllocateTimer(& delay_timer))
         fatal("can't allocate delay timer");
 }
static void delay_callback (RTCDRV_TimerID_t id, void * user) static
#include <delay.c>
Delay Callback function.
Parameters
[in] id RTC Timer Instance.
[in] *user
Definition at line 89 of file delay.c.
Referenced by delay().
 {
     delay_done = true;
 }
void delay (uint32_t ms)
#include <delay.c>
Delay ms function.
Parameters
[in] ms 32bit Time in ms for delay
Definition at line 102 of file delay.c.
References delay_callback(), and fatal().
Referenced by test_start(), and test_stop().
 {
     uint32_t ticks;
     ticks = MSEC_TO_TICKS(ms);
     delay_done = false;
     if (ECODE_EMDRV_RTCDRV_OK != RTCDRV_StartTimer(delay_timer,
                                                    rtcdrvTimerTypeOneshot,
                                                    ticks,
                                                    delay_callback,
                                                    0))
         fatal("can't initialize delay timer");
     while (! delay_done)
         EMU_EnterEM2(true);
 }