Adesto Flash Demo: LEUART
LEUART
Peripheral_Functions
UART definitions and functions.
.
Macros
#define PASTE_(A, B) A##B
#define PASTE(A, B) PASTE_(A, B)
#define PASTE3_(A, B, C) A##B##C
#define PASTE3(A, B, C) PASTE3_(A, B, C)
#define SPORT PASTE(LEUART, LEUART_NUM)
#define SERIAL_ROUTE_TXPEN LEUART_ROUTE_TXPEN
#define SERIAL_ROUTE_RXPEN LEUART_ROUTE_RXPEN
#define SERIAL_ROUTE_LOCATION_SHIFT _LEUART_ROUTE_LOCATION_SHIFT
#define SERIAL_TX_IRQn PASTE3(LEUART, LEUART_NUM, _IRQn)
#define SERIAL_RX_IRQn PASTE3(LEUART, LEUART_NUM, _IRQn)
#define SERIAL_TX_IRQHandler PASTE3(LEUART, LEUART_NUM, _TX_IRQHandler)
#define SERIAL_RX_IRQHandler PASTE3(LEUART, LEUART_NUM, _RX_IRQHandler)
#define SERIAL_IRQHandler PASTE3(LEUART, LEUART_NUM, _IRQHandler)
#define serial_cmuclock1 cmuClock_CORELE
#define serial_cmuclock2 PASTE(cmuClock_LEUART, LEUART_NUM)
#define serial_reset LEUART_Reset
#define serial_initasync LEUART_Init
#define serial_baudrateset LEUART_BaudrateSet
#define serial_intclear LEUART_IntClear
#define serial_intenable LEUART_IntEnable
#define STATUS_TXC LEUART_STATUS_TXC
#define IF_RXDATAV LEUART_IF_RXDATAV
#define IF_TXBL LEUART_IF_TXBL
#define IEN_RXDATAV LEUART_IEN_RXDATAV
#define IEN_TXBL LEUART_IEN_TXBL
#define INIT_STRUCT LEUART_Init_Typedef
#define RX_PORT gpioPortD
#define RX_PIN 5
#define TX_PORT gpioPortD
#define TX_PIN 4
#define LEUART_NUM 0
#define SERIAL_LOC 0
Functions
void LEUART0_RX_IRQHandler (void)
Serial RX IRQ Handler.
void LEUART0_TX_IRQHandler (void)
Serial TX IRQ Handler.
void LEUART0_IRQHandler (void)
void serial_blocking_write_char (char c)
Write Character to Serial Port - Blocking.
void serial_blocking_write_str (const char *p)
Write String to Serial Port - Blocking.
void serial_close (void)
Reset Serial Port.
void serial_init (int bit_rate, uint8_t *raw_rx_buf, size_t raw_rx_buf_size, uint8_t *raw_tx_buf, size_t raw_tx_buf_size)
Initialize Serial Port and TX/RX Buffers.
void serial_tx_flush (void)
Clear Transmit Buffer.
int RETARGET_WriteChar (char c)
Write Character to Serial Port.
int RETARGET_ReadChar (void)
Read Character from Serial Port.
Variables
static buf_t * serial_tx_buf
static buf_t * serial_rx_buf
const gpio_init_t serial_pins []
LEUART_Init_TypeDef sportInit
Detailed Description
UART definitions and functions.
.
Macro Definition Documentation
#define SPORT PASTE(LEUART, LEUART_NUM)
#include <serial.c>
*   The defines below are intended to allow any Leopard Gecko or Giant Gecko
*   LEUART, UART, or USART number and location to be used, but only LEUART0 location 0
*   has been tested.
*
*   Define only one of LEUART_NUM, UART_NUM, or USART_NUM, depending on
*   which kind of hardware port is to be used, with a numeric value
*   corresponding to which instance of that kind of hardware port is
*   to be used.
*
*   SERIAL_LOC specifies which set of GPIO pins the serial port should
*  use, of the choices available for the selected hardware port.
*
Definition at line 84 of file serial.c.
Referenced by LEUART0_RX_IRQHandler(), LEUART0_TX_IRQHandler(), serial_blocking_write_char(), serial_close(), and serial_init().
Function Documentation
void LEUART0_RX_IRQHandler (void)
#include <serial.c>
Serial RX IRQ Handler.
Definition at line 336 of file serial.c.
References buf_full(), buf_write_byte(), and SPORT.
 {
     if (SPORT->IF & IF_RXDATAV)
     {
         uint8_t data = SPORT->RXDATA;
         buf_write_byte(serial_rx_buf, data);
         if (buf_full(serial_rx_buf))
             SPORT->IEN &= ~ IEN_RXDATAV;  // disable rx interrupt
     }
 }
void LEUART0_TX_IRQHandler (void)
#include <serial.c>
Serial TX IRQ Handler.
Definition at line 352 of file serial.c.
References buf_read_byte(), and SPORT.
 {
     if (SPORT->IF & IF_TXBL)
     {
         uint8_t data;
         if (buf_read_byte(serial_tx_buf, & data))
             SPORT->TXDATA = data;
         else
             SPORT->IEN &= ~ IEN_TXBL;  // disable tx interrupt
     }
 }
void serial_blocking_write_char (char c)
#include <serial.c>
Write Character to Serial Port - Blocking.
Parameters
[in] c Character to write
Definition at line 379 of file serial.c.
References buf_write_char(), and SPORT.
Referenced by RETARGET_WriteChar(), and serial_blocking_write_str().
 {
     while (! buf_write_char(serial_tx_buf, c))
     {
         ;
     }
     SPORT->IEN |= IEN_TXBL;  // enable tx if not already going
 }
void serial_blocking_write_str (const char * p)
#include <serial.c>
Write String to Serial Port - Blocking.
Parameters
[in] *p Pointer to String to write
Definition at line 395 of file serial.c.
References serial_blocking_write_char().
 {
     while (*p)
         serial_blocking_write_char(*p++);
 }
void serial_close (void)
#include <serial.c>
Reset Serial Port.
Definition at line 457 of file serial.c.
References SPORT.
Referenced by demo_serial().
 {
     serial_reset(SPORT);
 }
void serial_init (int bit_rate, uint8_t * raw_rx_buf, size_t raw_rx_buf_size, uint8_t * raw_tx_buf, size_t raw_tx_buf_size)
#include <serial.c>
Initialize Serial Port and TX/RX Buffers.
Parameters
[in] bit_rate Baud Rate
[in] *raw_rx_buf Pointer to Receive Buffer
[in] raw_rx_buf_size Size of RX buffer
[in] *raw_tx_buf Pointer to Transmit Buffer
[in] raw_tx_buf_size Size of TX buffer
Definition at line 477 of file serial.c.
References gpio_init(), init_buf(), and SPORT.
Referenced by demo_serial().
 {
     serial_rx_buf = init_buf(raw_rx_buf, raw_rx_buf_size);
     serial_tx_buf = init_buf(raw_tx_buf, raw_tx_buf_size);
     CMU_ClockEnable(cmuClock_GPIO, true);
 #ifdef serial_cmuclock1
     CMU_ClockEnable(serial_cmuclock1, true);
 #endif
     CMU_ClockEnable(serial_cmuclock2, true);
     gpio_init(serial_pins, sizeof(serial_pins)/sizeof(gpio_init_t));
     serial_reset(SPORT);
     serial_initasync(SPORT, &sportInit);
     SPORT->ROUTE = SERIAL_ROUTE_TXPEN | SERIAL_ROUTE_RXPEN | (SERIAL_LOC << SERIAL_ROUTE_LOCATION_SHIFT);
     if (bit_rate)
 #if defined(LEUART_NUM)
         serial_baudrateset(SPORT, 0, bit_rate);
 #else
         serial_baudrateset(SPORT, 0, bit_rate, usartOVS16);
 #endif
     serial_intclear(SPORT, IF_RXDATAV | IF_TXBL);
     serial_intenable(SPORT, IF_RXDATAV);
     NVIC_ClearPendingIRQ(SERIAL_RX_IRQn);
     NVIC_EnableIRQ(SERIAL_RX_IRQn);
 #if SERIAL_RX_IRQn != SERIAL_TX_IRQn
     NVIC_ClearPendingIRQ(SERIAL_TX_IRQn);
     NVIC_EnableIRQ(SERIAL_TX_IRQn);
 #endif
 }
void serial_tx_flush (void)
#include <serial.c>
Clear Transmit Buffer.
Definition at line 522 of file serial.c.
References buf_empty().
Referenced by demo_serial(), get_status(), and write_enable().
 {
     while (! buf_empty(serial_tx_buf))
         ;
 }
int RETARGET_WriteChar (char c)
#include <serial.c>
Write Character to Serial Port.
Parameters
[in] c Character to write
Definition at line 535 of file serial.c.
References serial_blocking_write_char().
 {
     serial_blocking_write_char(c);
     return 0;
 }
int RETARGET_ReadChar (void)
#include <serial.c>
Read Character from Serial Port.
Definition at line 546 of file serial.c.
 {
     return 0;
 }
Variable Documentation
const gpio_init_t serial_pins[]
#include <serial.c>
Initial value:
=
{
    {  gpioPortD ,  4 , gpioModePushPull,  1 },
    {  gpioPortD ,  5 , gpioModeInputPull, 1 },
}
Definition at line 419 of file serial.c.
LEUART_Init_TypeDef sportInit
#include <serial.c>
Initial value:
=
{
  .enable       = leuartEnableRx | leuartEnableTx,
  .refFreq      = 0,
  .baudrate     = 9600,
}
Definition at line 426 of file serial.c.