Adesto Flash Demo: Buffer
Buffer
AppManagement
Buffer definitions, initializations, and handler routines
.
Data Structures
struct buf
Typedefs
typedef struct buf buf_t
typedef struct buf buf_t
Functions
buf_t * init_buf (uint8_t *raw_buf, size_t size)
Buffer Initialization.
bool buf_full (buf_t *buf)
Checks if buffer is full.
bool buf_empty (buf_t *buf)
Checks if buffer is empty.
bool buf_write_byte (buf_t *buf, const uint8_t data)
Buffer Write Byte.
bool buf_read_byte (buf_t *buf, uint8_t *data)
Buffer Read Byte.
bool buf_write_char (buf_t *buf, const char c)
Buffer Write Char.
bool buf_read_char (buf_t *buf, char *c)
Buffer Read Char.
Detailed Description
Buffer definitions, initializations, and handler routines
.
Function Documentation
buf_t * init_buf (uint8_t * raw_buf, size_t size)
#include <buffer.c>
Buffer Initialization.
Parameters
[in] *raw_buf Pointer to buffer
[in] size Size of Buffer
Returns
buf
Definition at line 69 of file buffer.c.
Referenced by serial_init().
 {
     buf_t *buf = (buf_t *) raw_buf;
     memset(buf, 0, size);
     buf->size = size - sizeof(buf_t);
     buf->count = 0;
     buf->write_idx = 0;
     buf->read_idx = 0;
     return buf;
 }
bool buf_full (buf_t * buf)
#include <buffer.c>
Checks if buffer is full.
Parameters
[in] *buf Pointer to buffer
Returns
TRUE/FALSE
Definition at line 88 of file buffer.c.
Referenced by LEUART0_RX_IRQHandler().
 {
     return buf->count == buf->size;
 }
bool buf_empty (buf_t * buf)
#include <buffer.c>
Checks if buffer is empty.
Parameters
[in] *buf Pointer to buffer
Returns
TRUE/FALSE
Definition at line 101 of file buffer.c.
Referenced by serial_tx_flush().
 {
     return buf->count == 0;
 }
bool buf_write_byte (buf_t * buf, const uint8_t data)
#include <buffer.c>
Buffer Write Byte.
Parameters
[in] *buf Pointer to buffer
[in] data Byte/data to write
Returns
true if successful
Definition at line 116 of file buffer.c.
Referenced by buf_write_char(), and LEUART0_RX_IRQHandler().
 {
     if (buf->count >= buf->size)
         return false;  // no room
     buf->data[buf->write_idx++] = data;
     if (buf->write_idx >= buf->size)
         buf->write_idx = 0;
     INT_Disable();
     buf->count++;
     INT_Enable();
     return true;
 }
bool buf_read_byte (buf_t * buf, uint8_t * data)
#include <buffer.c>
Buffer Read Byte.
Parameters
[in] *buf Pointer to buffer
[in] *data Pointer to data variable to write to
Returns
true if successful
Definition at line 139 of file buffer.c.
Referenced by buf_read_char(), and LEUART0_TX_IRQHandler().
 {
     if (buf->count == 0)
         return false;  // no data
     *data = buf->data[buf->read_idx++];
     if (buf->read_idx >= buf->size)
         buf->read_idx = 0;
     INT_Disable();
     buf->count--;
     INT_Enable();
     return true;
 }
bool buf_write_char (buf_t * buf, const char c)
#include <buffer.c>
Buffer Write Char.
Parameters
[in] *buf Pointer to buffer
[in] c Char to write
Returns
true if successful
Definition at line 162 of file buffer.c.
References buf_write_byte().
Referenced by serial_blocking_write_char().
 {
   return buf_write_byte(buf, (uint8_t) c);
 }
bool buf_read_char (buf_t * buf, char * c)
#include <buffer.c>
Buffer Read Char.
Parameters
[in] *buf Pointer to buffer
[in] *c Pointer to char to store read char
Returns
true if successful
Definition at line 177 of file buffer.c.
References buf_read_byte().
 {
     return buf_read_byte(buf, (uint8_t *) c);
 }