Adesto Flash Demo: LCD_Scroll
LCD_Scroll
LCD_Functions
Functions
void fatal (const char *s)
Scroll Character String on LCD.
void lcd_scroll_start (const char *s)
Start LCD Scroll of Character String.
void lcd_scroll_update (void)
Update LCD Display.
void lcd_scroll_stop (void)
Stop LCD Scroll.
Variables
static int lcd_scroll_length
static int lcd_scroll_position
static const char * lcd_scroll_message
Detailed Description
Function Documentation
void fatal (const char * s)
#include <fatal.c>
Scroll Character String on LCD.
Parameters
[in] *s Pointer to character string
Definition at line 62 of file fatal.c.
References EM2Sleep(), lcd_scroll_start(), and lcd_scroll_update().
Referenced by appl_erase(), delay(), delay_init(), enter_erase(), main(), oneshot_init(), oneshot_start_s(), run_erase(), and spiflash_setup().
 {
     lcd_scroll_start(s);
     while (true)
     {
         EM2Sleep(250);
         lcd_scroll_update();
     }
 }
void lcd_scroll_start (const char * s)
#include <lcd_scroll.c>
Start LCD Scroll of Character String.
Parameters
[in] *s Pointer to Character String
Definition at line 66 of file lcd_scroll.c.
References lcd_scroll_update().
Referenced by enter_id(), and fatal().
 {
     lcd_scroll_length = strlen(s);
     if (lcd_scroll_length < 7)
     {
         SegmentLCD_Write((char *) s);
         lcd_scroll_length = 0;
     }
     else
     {
         lcd_scroll_message = s;
         lcd_scroll_position = 0;
         lcd_scroll_update();
     }
 }
void lcd_scroll_update (void)
#include <lcd_scroll.c>
Update LCD Display.
Definition at line 88 of file lcd_scroll.c.
Referenced by fatal(), idle_default(), and lcd_scroll_start().
 {
     if (! lcd_scroll_length)
         return;
     SegmentLCD_Write((char *) (lcd_scroll_message + lcd_scroll_position));
     lcd_scroll_position++;
     if (lcd_scroll_position >= lcd_scroll_length)
         lcd_scroll_position = 0;
 }
void lcd_scroll_stop (void)
#include <lcd_scroll.c>
Stop LCD Scroll.
Definition at line 104 of file lcd_scroll.c.
Referenced by button0_default(), and button1_message().
 {
     lcd_scroll_length = 0;
 }