Adesto Flash Demo: LCD_Test
LCD_Test
LCD_Functions
Macros
#define VBOOST_SUPPORT 1
#define DEMO_MODE_NONE 0x0
#define DEMO_MODE_EM3 0x1
#define DEMO_MODE_EM4 0x2
Functions
void GPIO_IRQInit (void)
Initialize GPIO interrupt on PC14.
void checkVoltage (void)
Check input voltage and enable vboost if it drops too low.
void RtcTrigger (RTCDRV_TimerID_t id, void *user)
Callback function lighting the "Antenna symbol".
void EM1Sleep (uint32_t msec)
Sleeps in EM1 in given time unless some other IRQ sources has been enabled.
void EM2Sleep (uint32_t msec)
Sleeps in EM2 in given time unless some other IRQ sources has been enabled.
void EM3Sleep (void)
Sleeps in EM3 until GPIO interrupt is triggered.
void EM4Sleep (void)
Sleeps in EM4 until reset.
void ScrollText (char *scrolltext)
LCD scrolls a text over the display, sort of "polled printf".
void BlinkTest (void)
LCD Blink Test.
void Test (void)
LCD Test Routine, shows various text and patterns.
Variables
static char * stext = "Silicon Labs "
static uint16_t emMode = 0x0
static bool inEM3 = false
bool oldBoost = false
RTCDRV_TimerID_t xTimerForWakeUp
RTCDRV_TimerID_t xTimerForWakeUp
Detailed Description
Function Documentation
void GPIO_IRQInit (void)
#include <lcdtest.c>
Initialize GPIO interrupt on PC14.
Referenced by Test().
void checkVoltage (void)
#include <lcdtest.c>
Check input voltage and enable vboost if it drops too low.
Definition at line 189 of file lcdtest.c.
Referenced by Test().
 {
   bool vboost;
   /* Initialize voltage comparator, to check supply voltage */
   VDDCHECK_Init();
   /* Check if voltage is below 3V, if so use voltage boost */
   if (VDDCHECK_LowVoltage(2.9))
   {
     vboost = true;
   }
   else
   {
     vboost = false;
   }
   /* Disable Voltage Comparator */
   VDDCHECK_Disable();
   if (vboost != oldBoost)
   {
     SegmentLCD_Init(vboost);
     /* Use Antenna symbol to signify enabling of vboost */
     SegmentLCD_Symbol(LCD_SYMBOL_ANT, vboost);
     oldBoost = vboost;
   }
 }
void RtcTrigger (RTCDRV_TimerID_t id, void * user)
#include <lcdtest.c>
Callback function lighting the "Antenna symbol".
Definition at line 69 of file lcdtest.c.
Referenced by EM1Sleep().
 {
   ( void)id;
   ( void)user;
   /* Just a few No-OPerations to have a place to put a breakpoint */
   SegmentLCD_Symbol(LCD_SYMBOL_EFM32, 1);
 }
void EM1Sleep (uint32_t msec)
#include <lcdtest.c>
Sleeps in EM1 in given time unless some other IRQ sources has been enabled.
Parameters
msec Time in milliseconds
Definition at line 83 of file lcdtest.c.
References RtcTrigger(), and xTimerForWakeUp.
Referenced by Test().
 {
   /* Wake us up after msec (or joystick pressed) */
   NVIC_DisableIRQ(LCD_IRQn);
   /* Tell AEM we're in EM1 */
   RTCDRV_StartTimer( xTimerForWakeUp, rtcdrvTimerTypeOneshot, msec, RtcTrigger, NULL);
   EMU_EnterEM1();
   NVIC_EnableIRQ(LCD_IRQn);
 }
void EM2Sleep (uint32_t msec)
#include <lcdtest.c>
Sleeps in EM2 in given time unless some other IRQ sources has been enabled.
Parameters
msec Time in milliseconds
Definition at line 99 of file lcdtest.c.
References xTimerForWakeUp.
Referenced by BlinkTest(), fatal(), idle_default(), main(), ScrollText(), and Test().
 {
   /* Wake us up after msec (or joystick pressed) */
   NVIC_DisableIRQ(LCD_IRQn);
   RTCDRV_StartTimer( xTimerForWakeUp, rtcdrvTimerTypeOneshot, msec, NULL, NULL);
   EMU_EnterEM2(true);
   NVIC_EnableIRQ(LCD_IRQn);
 }
void EM3Sleep (void)
#include <lcdtest.c>
Sleeps in EM3 until GPIO interrupt is triggered.
Definition at line 112 of file lcdtest.c.
Referenced by Test().
 {
   inEM3 = true;
   SegmentLCD_Disable();
   EMU_EnterEM3(true);
   SegmentLCD_Init(false);
   inEM3 = false;
 }
void EM4Sleep (void)
#include <lcdtest.c>
Sleeps in EM4 until reset.
Definition at line 125 of file lcdtest.c.
Referenced by Test().
 {
   EMU_EnterEM4();
   /* we will never wake up again here - reset required */
 }
void ScrollText (char * scrolltext)
#include <lcdtest.c>
LCD scrolls a text over the display, sort of "polled printf".
Definition at line 135 of file lcdtest.c.
References EM2Sleep().
Referenced by Test().
 {
   int  i, len;
   char buffer[8];
   buffer[7] = 0x00;
   len       = strlen(scrolltext);
   if (len < 7) return;
   for (i = 0; i < (len - 7); i++)
   {
     memcpy(buffer, scrolltext + i, 7);
     SegmentLCD_Write(buffer);
     EM2Sleep(200);
   }
 }
void BlinkTest (void)
#include <lcdtest.c>
LCD Blink Test.
Definition at line 154 of file lcdtest.c.
References EM2Sleep().
Referenced by Test().
 {
   SegmentLCD_EnergyMode(0, 1);
   SegmentLCD_EnergyMode(1, 1);
   SegmentLCD_EnergyMode(2, 1);
   SegmentLCD_EnergyMode(3, 1);
   SegmentLCD_EnergyMode(4, 1);
   /* 2 minutes to midnight */
   SegmentLCD_Number(2358);
   SegmentLCD_Symbol(LCD_SYMBOL_COL10, 1);
   SegmentLCD_Symbol(LCD_SYMBOL_GECKO, 1);
   SegmentLCD_Symbol(LCD_SYMBOL_EFM32, 1);
   SegmentLCD_Write(" EFM32 ");
   LCD->BACTRL |= LCD_BACTRL_BLINKEN;
   while (LCD->SYNCBUSY) ;
   EM2Sleep(2000);
   SegmentLCD_EnergyMode(4, 0);
   EM2Sleep(62);
   SegmentLCD_EnergyMode(3, 0);
   EM2Sleep(62);
   SegmentLCD_EnergyMode(2, 0);
   EM2Sleep(62);
   SegmentLCD_EnergyMode(1, 0);
   EM2Sleep(62);
   SegmentLCD_EnergyMode(0, 0);
   LCD->BACTRL &= ~LCD_BACTRL_BLINKEN;
   while (LCD->SYNCBUSY) ;
 }
void Test (void)
#include <lcdtest.c>
LCD Test Routine, shows various text and patterns.
Definition at line 222 of file lcdtest.c.
References BlinkTest(), checkVoltage(), EM1Sleep(), EM2Sleep(), EM3Sleep(), EM4Sleep(), GPIO_IRQInit(), ScrollText(), stext, and xTimerForWakeUp.
 {
   int i, numberOfIterations = 0;
   /* Initialize GPIO */
   GPIO_IRQInit();
   /* Initialize RTC timer. */
   RTCDRV_Init();
   RTCDRV_AllocateTimer( &xTimerForWakeUp);
   /* Loop through funny pattern */
   while (1)
   {
     SegmentLCD_AllOff();
 #if VBOOST_SUPPORT
     checkVoltage();
 #endif
     if (emMode != DEMO_MODE_NONE)
     {
       SegmentLCD_Symbol(LCD_SYMBOL_PAD0, 1);
       SegmentLCD_Symbol(LCD_SYMBOL_PAD1, 1);
     }
     else
     {
       for (i = 100; i > 0; i--)
       {
         SegmentLCD_Number(i);
         EM2Sleep(10);
       }
       SegmentLCD_NumberOff();
       SegmentLCD_Symbol(LCD_SYMBOL_GECKO, 1);
       SegmentLCD_Symbol(LCD_SYMBOL_EFM32, 1);
       SegmentLCD_Write(" Leopard ");
       EM2Sleep(500);
       SegmentLCD_Write(" Gecko ");
       EM2Sleep(1000);
       SegmentLCD_AllOn();
       EM2Sleep(1000);
       SegmentLCD_AllOff();
     }
     if (emMode != DEMO_MODE_NONE)
     {
       SegmentLCD_Symbol(LCD_SYMBOL_PAD0, 1);
       SegmentLCD_Symbol(LCD_SYMBOL_PAD1, 1);
     }
     else
     {
       SegmentLCD_Write("OOOOOOO");
       EM2Sleep(62);
       SegmentLCD_Write("XXXXXXX");
       EM2Sleep(62);
       SegmentLCD_Write("+++++++");
       EM2Sleep(62);
       SegmentLCD_Write("@@@@@@@");
       EM2Sleep(62);
       SegmentLCD_Write("SILICON");
       EM2Sleep(250);
       SegmentLCD_Write("@@LICON");
       EM2Sleep(62);
       SegmentLCD_Write(" @@ICON");
       EM2Sleep(62);
       SegmentLCD_Write(" L@@CON");
       EM2Sleep(62);
       SegmentLCD_Write(" LA@@ON");
       EM2Sleep(62);
       SegmentLCD_Write(" LAB@@N");
       EM2Sleep(62);
       SegmentLCD_Write(" LABS@@");
       EM2Sleep(62);
       SegmentLCD_Write(" LABS @");
       EM2Sleep(250);
       SegmentLCD_Write("-EFM32-");
       EM2Sleep(250);
       /* Various eye candy */
       SegmentLCD_AllOff();
       if (emMode != DEMO_MODE_NONE)
       {
         SegmentLCD_Symbol(LCD_SYMBOL_PAD0, 1);
         SegmentLCD_Symbol(LCD_SYMBOL_PAD1, 1);
       }
       for (i = 0; i < 8; i++)
       {
         SegmentLCD_Number(numberOfIterations + i);
         SegmentLCD_ARing(i, 1);
         EM2Sleep(20);
       }
       for (i = 0; i < 8; i++)
       {
         SegmentLCD_Number(numberOfIterations + i);
         SegmentLCD_ARing(i, 0);
         EM2Sleep(100);
       }
       for (i = 0; i < 5; i++)
       {
         SegmentLCD_Number(numberOfIterations + i);
         SegmentLCD_Battery(i);
         SegmentLCD_EnergyMode(i, 1);
         EM2Sleep(100);
         SegmentLCD_EnergyMode(i, 0);
         EM2Sleep(100);
       }
       SegmentLCD_Symbol(LCD_SYMBOL_ANT, 1);
       for (i = 0; i < 4; i++)
       {
         SegmentLCD_EnergyMode(i, 1);
         EM2Sleep(100);
       }
       SegmentLCD_Symbol(LCD_SYMBOL_ANT, 0);
       SegmentLCD_Battery(0);
     }
     /* Energy Modes */
     SegmentLCD_NumberOff();
     SegmentLCD_Symbol(LCD_SYMBOL_GECKO, 1);
     SegmentLCD_Symbol(LCD_SYMBOL_EFM32, 1);
     if ((emMode != DEMO_MODE_EM3) && (emMode != DEMO_MODE_EM4))
     {
       ScrollText("Energy Mode demo, Press PB0 for EM3 or PB1 for EM4       ");
     }
     SegmentLCD_Write("  EM0  ");
     SegmentLCD_Number(0);
     SegmentLCD_EnergyMode(0, 1);
     SegmentLCD_EnergyMode(1, 1);
     SegmentLCD_EnergyMode(2, 1);
     SegmentLCD_EnergyMode(3, 1);
     SegmentLCD_EnergyMode(4, 1);
     RTCDRV_Delay(4000);
     SegmentLCD_Write("  EM1  ");
     SegmentLCD_Number(1111);
     SegmentLCD_EnergyMode(0, 0);
     EM1Sleep(4000);
     SegmentLCD_Write("  EM2  ");
     SegmentLCD_Number(2222);
     SegmentLCD_EnergyMode(1, 0);
     EM2Sleep(4000);
     /* Check if somebody has pressed one of the buttons */
     if (emMode == DEMO_MODE_EM3)
     {
       ScrollText("Going down to EM3, press PB0 to wake up    ");
       SegmentLCD_Write("  EM3  ");
       SegmentLCD_Number(3333);
       RTCDRV_Delay(1000);
       /* Wake up on GPIO interrupt */
       EM3Sleep();
       SegmentLCD_Number(0000);
       SegmentLCD_Write("--EM0--");
       RTCDRV_Delay(500);
       SegmentLCD_Symbol(LCD_SYMBOL_PAD0, 0);
       SegmentLCD_Symbol(LCD_SYMBOL_PAD1, 0);
       emMode = DEMO_MODE_NONE;
     }
     /* Check if somebody's joystick down */
     if (emMode == DEMO_MODE_EM4)
     {
       ScrollText("Going down to EM4, press reset to restart    ");
       SegmentLCD_Write("  EM4  ");
       SegmentLCD_Number(4444);
       RTCDRV_Delay(1000);
       /* Wake up on reset */
       EM4Sleep();
     }
     SegmentLCD_EnergyMode(0, 0);
     SegmentLCD_EnergyMode(1, 0);
     SegmentLCD_EnergyMode(2, 0);
     SegmentLCD_EnergyMode(3, 0);
     SegmentLCD_EnergyMode(4, 0);
     /* Scrolltext */
     ScrollText(stext);
     /* Blink and animation featurs */
     BlinkTest();
     numberOfIterations++;
   }
 }
Variable Documentation
char* stext = "Silicon Labs " static
#include <lcdtest.c>
Demo scroll text
Definition at line 47 of file lcdtest.c.
Referenced by Test().
RTCDRV_TimerID_t xTimerForWakeUp
#include <lcdtest.c>
Timer used for bringing the system back to EM0.
Definition at line 60 of file lcdtest.c.
Referenced by EM1Sleep(), EM2Sleep(), main(), and Test().
RTCDRV_TimerID_t xTimerForWakeUp
#include <lcdtest.h>
Timer used for bringing the system back to EM0.
Definition at line 60 of file lcdtest.c.
Referenced by EM1Sleep(), EM2Sleep(), main(), and Test().